== Chapter II.

[.chapter-synopsis]
* Visit to North Carolina Yearly Meeting.footnote:[John Hall, living near Mt. Pleasant, was his companion.]

Tenth Month, 1834.
Having for some time felt my mind drawn to visit in gospel
love the meetings of North Carolina Yearly Meeting,
as way might open, and having the concurrence of my friends,
I left my dear wife and children on the 13th of the month,
in which parting opportunity the stream of
Divine life was felt uniting our hearts together.
We proceeded towards Hopewell, Virginia.
The night previous to reaching that place,
a circumstance occurred at our Inn which was very distressing to me.
A short time before we arrived,
a company of movers with their horses had put up for the night.
When we arrived,
a colored boy came immediately to our assistance and took our horses to the stable.
A young man of the company of movers forbade his taking them in,
though there was room sufficient;
which he proceeding to do was immediately knocked down by the white man with a stone,
and was taken up for dead; but by morning was so far revived as to whisper.
This circumstance,
together with the wicked conversation of some present about buying and selling negroes,
had liked to have caused me a sleepless night.

+++[+++At Hopewell he wrote to his family as follows:+++]+++

[.embedded-content-document.letter]
--

We have had our health well since we left home, and have got along comfortably,
except the feeling of distress that has attended in passing through a land of slavery.

People here talk of buying and selling negroes with as
little apparent feeling as we would of selling a horse.
My mind has been kept in such a calm that every doubt
has been removed respecting our present engagement,
so much so that I could not wish myself anywhere else;
and I humbly hope our gracious Lord and Master will be
near to direct and support in every time of trial.
Our dear children are often the objects of my remembrance.
May you all be kept in the hollow of the Lord`'s holy hand.

[.signed-section-signature]
Joseph Edgerton.

--

We arrived at Deep River after a laborious travel of about thirteen days, I trust,
under feelings of thankfulness to the Preserver of men for his many mercies;
and my mind has been afresh turned to look at the motives which drew
me from my outward habitation to go into a distant land;
which was nothing short of an apprehension that it was the will of my Divine Master.
O, that it may please Him to whom I have committed my dear wife and children,
to keep them in the hollow of his holy hand,
and be near to guide by his counsel in our present engagement.

I feel myself a child for such a service.
May I increasingly come to know that all my springs are
in Him who is the strength of his people.

+++[+++He again writes:--+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
New Garden, Guilford Co., N. C, Eleventh Month, 1834.

[.salutation]
My dear Wife:

My spirit salutes you this morning in near and dear affection,
though far separated in person, and may inform you that I am well,
and have enjoyed good health since leaving home.
My dear companion`'s health is also good.
The Meeting for Sufferings was held on Sixth-day;
the Select Yearly Meeting on Seventh-day,
and on Second-day the Meeting for Discipline commenced.
Our dear friend, Nathan Hunt, addressed me in this encouraging language:
"`My dear brother, go on cheerfully in the work of the Lord,
and you will get through to your humbling admiration.`"
And I can acknowledge that his presence has been vouchsafed to us, unworthy as we are;
and ability has been furnished for the portion of labor allotted us.
Many are the trials meted out to those who engage rightly in this great service,
at a time when so many of the members of our Society
are contenting themselves with a name to live,
while they remain in a state of death and darkness.
I have felt it to be a very great undertaking that we are engaged in,
and nothing short of Divine power can abilitate for it.
I have often to recur to you and my dear relatives and friends at home, whose prayers,
I have no doubt, have been put up for me,
that I may be preserved in the service that is called for at my hands,
which has been a strength many times to my
drooping mind in the prospect of arduous labor.
The desire of my heart has been that I might be entirely given up to the will of the Lord.
The Yearly Meeting has been large, and, so far, favored.
It has, I think, been a solid meeting, and the business conducted in harmony.

[.signed-section-closing]
Your loving husband.

[.signed-section-signature]
Joseph Edgerton.

--

Seventh-day, 8th of Eleventh Month.--Attended Hopewell Monthly Meeting.
A time of close exercise;
but ability being afforded to perform the portion of labor allotted, we left in peace.
My mind has often been clothed with a feeling of my own
unworthiness and the greatness of the work;
under the consideration whereof my mind is bowed in awful prostration,
desiring that He whose mercies are over all his works,
may condescend to be near for my support under every trial,
and enable me to keep so devoted to his service,
that all his commandments may be obeyed--that my soul may be even as a weaned child,
weaned from all dependence upon my own attainments, confiding in Him alone,
through whose Divine and wonder working power, transgressors are taught his ways,
and sinners converted unto Him.

Second-day,
at Union.--My mind was impressed with the necessity of the members of
our religious Society keeping their habitations in the truth,
and felt peace of mind in dropping some close remarks.
Set out on Third-day morning towards Surrey County,
and arrived at Fawbush Creek late in the evening,
and attended their meeting on Fourth-day, which was a time of deep exercise to me.

My soul is often clothed with sadness on account of the lukewarmness
that prevails in many of the members of our Society;
and the situation of those who go forth rightly on Gospel errands,
seems to me to be very similar to that of some formerly,
who taking their lives in their hands,
went through the enemy`'s camp to bring water from Bethlehem`'s well to thirsty souls.
Some very close remarks were dropped to some who were but
stumbling blocks in the way of serious inquirers after truth.

Fifth-day, at Deep Creek.--The forepart was laborious,
but towards the conclusion life arose,
so that I humbly hope it was a time of instruction to many.
First-day attended meeting at Newberry.
A very stormy day.
It continued to rain and freeze, until it became the most extraordinary sleet I ever saw,
the timber being so loaded with ice that it is very much broken,
and by the obstruction of rain, ice, and fallen timber in the roads,
travelling is impracticable; so we have felt the necessity of a fresh supply of patience.
Being thus weather-bound,
I have been led to view that which drew me from my home and near and dear friends,
whose feeling sympathy I had;
and I have no doubt their prayers are put up to the Preserver of men
for my preservation and safe return to them and my dear family,
with the reward of peace.
May it be my experience,
for I am confirmed in the belief that it is only
through Divine mercy that this can be obtained.

Being thus unexpectedly detained for near two days,
it proved a time of deep baptism to me, such as I have rarely, if ever, experienced.
My soul was ready to cry out in the language of David:
"`I sink in deep mire where there is no standing!`"
But through Divine mercy, light broke forth,
so that all within me was bowed in awful prostration.
O, may I never forget his matchless and unmerited blessings,
conferred on me, an unworthy worm of the dust.

I believe it is in the counsels of that wisdom that cannot err,
that fiery trials are meted out,
not only to prepare to sympathize with and to
speak to the states of others similarly proved,
but also to feel the necessity of an entire dependence upon
that Arm of Divine power which alone can qualify for service.
O,
that I may be so attentive to the voice of the Good
Shepherd as to be preserved out of the mixture,
that the pure spring of life may be kept to.

+++[+++Eleventh Month 22nd, 1834, he again writes:+++]+++

[.embedded-content-document.letter]
--

[.salutation]
My dear Wife:

We have been very closely engaged
every day except two that we had to lie by,
in consequence of the sleet.
We have been favored to get along, to the relief and peace of our minds.
Many baptisms are our portion.
The languid state of our Society in many places is, as Samuel Fothergill observes,
like pensively musing on a scroll that is written within and without with lamentation,
mourning and woe;
so that the situation of those who go forth in the Lord`'s
service is very similar to that of some of David`'s worthies,
who taking their lives in their hands,
passed through the camp of the uncircumcised and brought water
from the well of Bethlehem to the thirsty soul.
But my gracious Master has been good to me,
not only in affording ability to perform what He requires,
but in giving that peace which passes understanding.
We are now through the meetings of New Garden and Deep River Quarters.
Friends in this country have no fire in their meetinghouses;
I have seen but one that had any opportunity of warming it.

[.signed-section-closing]
I remain affectionately,

[.signed-section-signature]
Joseph Edgerton.

--

Fourth-day, 26th.--Had a meeting at Kennet;
a time of close labor to some lukewarm professors.
Went to Springfield, and attended meeting there on Sixth-day,
and a very favored meeting it was.
The Lord`'s power rose into dominion over all,
and praises ascended unto Him who alone gave the victory.

Seventh-day attended the Quarterly Meeting at New Salem,
which was a time of deep exercise; but in some close labor to the lukewarm professors,
with encouragement to the wrestling seed, relief was obtained.

Fourth-day at Providence.
A time of close labor with some lukewarm professors.
At Salem, life was low;
but by close attention strength was afforded to minister in the ability that God gives,
to the relief of my mind.
At Marlborough our gracious Master was near to strengthen for his service.
The states of the people were spoken to, I trust, in the ability which He gives.
At Uharee, which was an open time, the doctrines of the Gospel were opened, and, I trust,
it was a time of instruction to many.

Second-day, at Bethel; a time that I hope will be remembered by some.
Ability was afforded to labor for the growth and establishment of the
members of our religious Society upon the immovable foundation,
Jesus Christ himself being the chief corner-stone.
The meeting ended in solemn prayer to God.
May the many mercies of which we are made partakers,
animate us to follow Him with increased dedication,
and not be dismayed at any prospect of service required by our gracious Master,
who has hitherto helped us.

The meeting at Piney Ridge was a time of deep exercise and close labor.
At Holly Spring truth rose into dominion, and the stream of Gospel love flowed forth,
to the refreshment of many.
May the praise be returned to God, to whom alone it is due.
Fifth-day, rode to Long`'s settlement,
and in the afternoon had the few Friends there together;
and that evening went to the house of Joshua Johnson,
where we had an opportunity in the family.
I had to labor closely against a worldly spirit.
I have often thought there is no state harder to reach,
than that wherein the Divine witness is so buried in the rubbish,
and not allowed to rise.
To awaken these is a miracle, indeed; and yet, in passing from house to house,
I have endeavored to declare the whole counsel of God,
however humiliating to the creature.

+++[+++After attending Cane Creek Monthly Meeting, and the meetings of South Fork,
Spring Meeting and Eno, he set out for Contentney,
and arrived in the neighborhood on Fifth day evening.+++]+++
Seventh day, attended Contentney Monthly Meeting, and at meeting there on First-day,
which was owned by the Head of the Church.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Twelfth Month 10th, 1834.

[.salutation]
My dear Wife:

We are now at uncle William Edgerton`'s,
after a laborious travel among the meetings of New Garden, Deep River,
Southern and Western Quarterly Meetings; having been engaged every day for five weeks,
except two in time of the sleet.
I think we endeavored to improve the time to the best advantage;
and I have thought it right to do so,
remembering the strong claims that my dear family have upon me,
and shall rejoice when the time comes that a release from further service is proclaimed,
and liberty given to return to them.
In relation to our getting along in the great work in which we are engaged,
we feel that we have cause for thankfulness to
Him who has afforded help in every time of trial,
strengthening for the service that He required.
And although in many places where we have been, our minds were clothed with mourning,
under a sense that the seed of immortal life is borne down and oppressed,
even as a cart loaded with sheaves, yet, in most places,
there is a remnant that is as the salt of the earth,
to whom my spirit has been nearly united in the bonds of Gospel fellowship.

We expect to set off in the morning for Core Sound.
It would have been pleasant to the creature, to have been excused from going there,
a distance of 120 miles.
But a release from it I could not feel.
They have a Monthly Meeting at that place, though very small.

--

+++[+++Under date, Twelfth Month 17th, he writes in the same letter:+++]+++--

[.embedded-content-document.letter]
--

We have been this day to Neuse Meeting, where my father and mother went many years;
and a very favored meeting we had.
The Lord has a remnant here who, I trust,
will be abilitated to support the testimonies of our Society.
Very often does my mind visit you,
knowing that your time is very closely taken up with your domestic duties,
but trust the Eternal God will be your refuge, and underneath the Everlasting Arms,
to comfort and refresh your drooping spirit.
He has been good to me, even strength in weakness, riches in poverty,
and a present help in the needful time,
that I feel encouraged to trust in Him and persevere in the work.
Our dear children are often the object of my tender solicitude.
I want you, dear children, to do all you can to make your dear mother comfortable,
and do nothing to grieve her.

[.signed-section-closing]
I remain affectionately,

[.signed-section-signature]
Joseph Edgerton.

--

At Nahunta and Neuse River, both favored meetings, particularly in the latter;
many hearts were prepared to return praise to Zion`'s King.
At Core Sound Meeting, Holy Help was near;
so that I thought I was fully compensated for all my fatigue in getting there.
At Rich Square, on First-day, a time of deep baptism.
O, that the Lord, who alone can subdue all things unto himself, may,
in the way that is consistent with that wisdom that cannot err, carry on the work,
until our dependence is wholly placed upon Him who works wonders in the heavens above,
and in the earth beneath,--who makes the clouds his chariots,
and walks on the wings of the wind, and can sanctify the most severe dispensations,
and make them ministers of his will.
O! Great and eternal Jehovah, you have been pleased to be near in the time of need,
and to abilitate for your service hitherto,
will you be pleased to continue your all-sustaining Arm underneath.
Then will I teach transgressors your way, and sinners, through your Divine Power,
shall be converted unto you; that so everlasting praise may be rendered unto you,
the Lord God, and the Lamb, our adorable redeemer, not only now,
but henceforth and forevermore.

+++[+++At Perquimans County, Twelfth Month 31st, 1834, he wrote:+++]+++

[.embedded-content-document.letter]
--

[.salutation]
My dear Wife:

My heart is often clothed with breathing desires for our children,
that they may be kept in innocency; that as they advance in years,
they may grow in grace.
And, my dear, I assuredly believe your reward is sure.
You may have many trials, both within and without,
yet the Eternal God is your refuge and underneath are the everlasting arms.
May you be encouraged and enabled to lift up your head above the waves.
I feel the need of the prayers of the living ministers of the Church,
which I have no doubt have been beneficial to me, as the path is a tribulated one,
and at times it seems as if every step taken is upon enchanted ground.
But the good Shepherd has been near to support; and oh,
that He may continue his care over me, and preserve me from dangers,
both within and without, for it is of his mercy; therefore,
may the praise be ascribed unto Him alone to whom it is due.

It is a comfort, notwithstanding my feelings are at times as described above,
to find a remnant that are concerned for the testimonies and
discipline of our religious Society in this land,
and to mingle in fellowship with them.
My mind is often turned towards Friends of our Yearly Meeting,
with desires that the Head of the Church might preserve us from the snares of the enemy,
and draw us nearer unto himself and unto one another;
that by walking by the same rule and minding the same thing,
we might grow up a royal priesthood, a holy nation, a peculiar people,
showing forth the praises of Him who has called us;
that everything that might prove prejudicial to the peace and prosperity of Society,
might be kept down, and we experience Jerusalem, a quiet habitation.

I must conclude, hoping in the Lord`'s time we shall be favored to meet,
to our comfort and his praise.

[.signed-section-signature]
Joseph Edgerton.

--

Attended meetings at Beech Spring, Piney Ridge, Newbegun Creek,
Little River and Symond`'s Creek,
in all of which ability was afforded for required service.

At Elizabeth City my mind was clothed with mourning under a
sense of the low state of Society in these parts;
but by laboring honestly, relief was obtained.
Sutton`'s Creek Monthly Meeting was also a time
of close labor to some lukewarm professors;
though encouragement flowed forth to the exercised remnant.
The meeting at Wells, on First-day, the 11th, was a time of great suffering to me.
Truth was under oppression, even as a cart loaded with sheaves.
And now, feeling released from further service in this land,
we set off from the house of David White for home, the 12th of First Month, 1835,
under a sense of the Lord`'s abundant mercy,
who has been pleased to be near and support in every time of trial,
and has given ability for the work whereunto He has called.

+++[+++After his return, he writes:+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Barnesville, Belmont County, Ohio, Second Month 7th, 1835.

[.salutation]
Dear Cousins, Thomas and Elizabeth Kennedy:

Here by my own fireside,
and enjoying the company of my dear family and friends,
my mind is often turned towards friends of North Carolina,
many of whom my spirit feels nearly united to in the bonds of Gospel fellowship.
I may inform, that from Rich Square we proceeded to Perquimans and Pasquotank,
taking all the meetings of Friends, and got through on First-day,
the 11th of First Month, and set our faces towards home the 12th,
under a sense of the Lord`'s gracious dealings towards us, unworthy as we are,
in affording Divine aid in this variously-trying journey.

Our hearts were prepared to return thanksgiving and praise unto Him to whom it is due;
and I was favored to reach home on the 29th, where I found my dear wife and family well,
to our mutual comfort and consolation.
May his great and worthy name be honored and adored,
through whose power alone we were preserved from dangers, both within and without,
and brought back again to our families and friends, with the reward of peace.
A peaceful poverty seems to be the clothing of my mind, and desires have been raised,
that whether the great and good Master may ever call forth in his service again or not,
I may be so devotedly given up to wait at the King`'s gate, that his will may be done;
as I apprehend, there can be no higher anthem sung by mortal man than, "`Not, my will,
but yours be done.`"
My dear friends in that part of the Lord`'s heritage have often been fresh in my memory,
together with many favored meetings we had when in your land;
the great Head of the Church being pleased to be near,
bringing us as members of the same body unto near unity with each other;
our hearts at times being made to rejoice because of his goodness.
And those who had not come to the like happy experience,
were often the objects of feeling concern, that they,
through the effectual working of the Lord`'s power,
might be brought into the same living body,
of which Christ is the Head,--to know a being children of Jerusalem that is above,
and is free, which, says the great apostle, is the mother of us all;
for all who come to know a being made free by Christ the Son, are free, indeed.

I want your encouragement in the line of allotted duty.
Our Divine Master will support in every time of trial,
and will abilitate for every service required.
I feel much for Neuse Meeting; doubtless the Lord`'s mercies are extended to you,
and He would turn his hand upon some of you in a
particular manner if faithfulness were abode in;
and fit for his work and service, to the praise of his great Name.
Yes, I believe He would gather the lambs with his arms and carry them in his bosom,
and gently lead those that are under a living exercise.
Thus He would raise up testimony-bearers that would not
be ashamed to confess their Lord and Master before men.
I should be glad to hear of Joseph Everett`'s endeavoring to have his negroes
removed to free governments while life and health are afforded;
time is very uncertain.

[.signed-section-closing]
I remain your affectionate cousin,

[.signed-section-signature]
Joseph Edgerton.

--

+++[+++The following is taken from a copy of a letter to his valued friend, Nathan Hunt:+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Second Month 27th, 1835.

[.salutation]
Dear Friend:

I often thought when travelling through your land,
that the faithfulness of Friends there in regard to our testimony against slavery,
has been blessed;
and I think there is cause for encouragement to embrace every
opportunity that wisdom and prudence would dictate,
to plead the cause of that oppressed part of our fellow men.
And although your efforts in memorializing the Legislature on their
behalf may not have met with that success which was desired,
yet I do not think that should discourage you from doing what appears to be your duty.
I am confirmed in the belief that,
notwithstanding all the opposition that is made by men of corrupt minds,
the cause is gaining ground;
even those who hold slaves are becoming more and more uneasy;
the witness for God is not easily removed into a corner.
I have felt, both while there and since, much for my friends of North Carolina,
and hope that our religious Society in other parts of the heritage,
will manifest a brotherly participation in the concern,
not only by rendering their assistance in a pecuniary point of view,
but in sympathy for you who are called upon to test the ground
of our testimony against slavery more conspicuously;
that so there might be a harmoniously joining together, and through the Divine blessing,
be instrumental, in some degree,
in removing from our favored nation that load of guilt that is attached to slavery.

I have had to recur to many of my dear friends in that land,
to whom we felt nearly united in the bonds of Gospel fellowship; and, no doubt,
the language has been reciprocal at times,
where there has been admittance granted to the throne of grace, in sweet remembrance,
"`The Lord hear you in the day of trouble; the name of the God of Jacob defend you,
send you help from his sanctuary, and strengthen you out of Zion.`"

It is a privilege that the living members of the Church have,
of eating of the same spiritual meat and drinking of
the same spiritual and Divine fountain,
and herein their unity and fellowship is known.
Give my love affectionately to inquiring friends in your freedom,
particularly to your son Thomas, his dear wife and children, your daughter Abigail,
and her husband.

I wish your Boarding School concern good success.
Many Friends, I think,
are not aware of the great advantage of having their children placed in such a school,
under the immediate care and superintendence of the Yearly Meeting.
Ours progresses slowly.
It is to be hoped, that in the course of the ensuing season,
more active operations will be gone into for the accomplishment of the object.

[.signed-section-signature]
Joseph Edgerton.

--

Third Month 15th,
1835.--In reviewing the various trials attendant on my late engagement in a distant land,
together with the numberless blessings that I have been the unworthy partaker of,
all within me capable of feeling,
has been bowed in awfulness before Him through whose fatherly care, by day and by night,
preservation was experienced.
May his great name be magnified and adored, who is the good Shepherd,
leading forth his dependent children in the work whereunto He calls them.

Oh, that I may be preserved so near the spring of Divine life,
that I may be kept out of the mixture;
that whether or not the Lord should ever make use of such a poor, unworthy creature,
as an instrument in the support of that cause which is
dignified with immortality and crowned with eternal life,
that the work of sanctification may go on, until the dross and the tin,
and even the reprobate silver may be removed out of the way.
I have, in viewing the languid state of our Society in many places,
felt my mind clothed with mourning to see so many come so far
short of the mark of the high calling of God in Christ Jesus,
being settled in a state of lukewarmness, for whom my feelings have often been awakened,
lest the dreadful sentence pronounced against the
Laodicean Church should ultimately fall upon them.
Yet notwithstanding this,
my faith is at times strengthened to believe that the
Lord will carry on his work in the earth;
and if those who have long been visited and invited to the supper refuse the offer,
and go one to his farm, another to his merchandise,
others will be called in from the highways and hedges,
who will not be ashamed to acknowledge their Lord and Master before men.

+++[+++The following is an extract from a letter addressed to John Hall,
who accompanied him in his late visit:+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
First Month 3rd, 1836.

[.salutation]
Dear Friend, John Hall:

I have many times remembered you since being at your house,
and feelings of sympathy and brotherly affection have been afresh excited by
the reading of your acceptable letter to sister Mary Edgerton,
which I was glad to have the opportunity of; and I can say,
that my faith remains unshaken in that Arm of Power that gathered our
religious Society from the various forms and ceremonies of the world,
and of professing Christians, to be a separate and distinct people.
And by the illuminations of the day-spring from on high,
with which they were very eminently favored, they saw that,
through the dark night of apostacy from primitive
purity that had overtaken the primitive Church,
many corruptions had made their way into it.
Hence they believed it to be their religious duty to bear testimony
to the purity and spirituality of the religion of Jesus Christ.
And these testimonies were so dear to them,
that the most cruel persecutions could not deter
them from that which they saw to be their duty;
and herein they were willing to prove by their conduct,
that to fulfill the will of their Lord and Master,
and thereby maintain a conscience void of offence towards God and man,
was more to them than any worldly consideration, or even liberty or life itself;
and through the fresh openings of Divine light and life in their souls,
they were enabled to hold up a pure and perfect standard of Christian doctrine,
which will remain unsullied to the latest period.

Dear John,
my spirit has at times been broken into tenderness in
the remembrance of the state of Society,
and mental desires have arisen to the Shepherd of
Israel that He may be pleased to remember his heritage,
that his humble dependent children and servants in every part thereof that
are earnestly contending for the faith once delivered to the saints,
may by that invincible Arm of Power be supported;
that He may indeed be a spirit of judgment to those who sit in judgment,
and strength to them that turn the battle to the gate.
And in the midst of mournfully distressing feelings that do attend,
my faith has at times been renewed in our Holy Head, whose watchful care,
both by day and by night, is towards the tried and tribulated seed of Jacob;
whose promise is,
"`Can a woman forget her sucking child that she should not have compassion on her son?
Yes, she may forget, yet will I not forget you, says the Lord.`"

My dear brother,
I desire your encouragement as well as other faithful Friends who keep to that
which was our foundation when it pleased the Lord to gather us to be a people,
and which is, and will remain to be an impregnable fortress,
against which present and succeeding storms will ever beat in vain.
I feel for you in your peculiarly trying situation,
and hope you will be enabled to do or to suffer,
as may be consistent with the Divine will, and much suffering is your portion,
I have no doubt.
My wife joins me in love to you, your dear wife and children.

[.signed-section-signature]
Joseph Edgerton.

--

+++[+++Extract from a letter to his brother:+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Third Month 11th, 1836.

[.salutation]
Dear Brother and Sister:

I often have to recur
to opportunities that we have had together,
before you moved to Indiana, wherein not only the ties of natural relationship were felt,
but also that threefold cord or bond of Gospel fellowship,
which rendered your company and society very pleasant to us.
And these reflections upon the occurrences and feelings of days that are past,
have at times been attended with desires that we might be preserved
in a state of humble dependence upon the Lord Jesus Christ,
who has said: "`Except you be converted and become as little children,
you shall not enter into the kingdom of heaven.`"
Oh, for this state of humility, wherein the pride and haughtiness of man is bowed down,
the man`'s part broken, and the Lord alone exalted; then, and not till then,
can we come to realize that Scripture language:
"`All your children shall be taught of the Lord,
and great shall be the peace of your children,`" and experience our
feeble steps to be in that path which "`no fowl knows,
the vulture`'s eye has not seen it, the lion`'s whelps have not trodden in it,
nor the fierce lion passed by it.`"
That it is entirely beyond the conception of the natural man,
comparable to the vulture`'s eye, though he may by the aid of reason,
with which he is richly furnished,
be able in his researches to comprehend deep and hidden mysteries in the laws of nature,
yet all attempts to comprehend the mysteries of the heavenly kingdom will be in vain.
And in this an eminent apostle speaks very plainly, where he says:
"`The natural man receives not the things of the Spirit of God, neither, indeed,
can he know them, because they are spiritually discerned.`"
It is a way cast up for the ransomed of the Lord to walk in (through
the mediation of the Lord Jesus Christ,)
who "`shall return and come to Zion with songs and everlasting joy upon their heads;
they shall obtain joy and gladness, and sorrow and sighing shall flee away.`"
The more we come to experience this heavenly condition,
the more we shall see of the weakness and insufficiency,
and even corruption of human nature;
and though we may have been favored in some degree to run in the way of his holy will,
yet that acknowledgment will arise:
"`It is not by works of righteousness which we have done, but according to his mercy,
He has saved us, by the washing of regeneration and the renewing of the Holy Spirit.`"
Then the invaluable pages of Holy Scripture will be dear to us,
and the precious truths therein contained will be unfolded
from time to time to our edification and comfort,
by the Spirit of Truth, which has been sent to teach us all things,
and bring all things to our remembrance.

My sincere desire is that we may be firmly established upon that foundation
which our religious Society was gathered to and settled upon,
which will prove a fortress against which all storms, both present and to come,
will beat in vain, and so be found faithful in the occupancy of the talent received,
to the peace of our own minds and to the glory of the great Name.

[.signed-section-closing]
I am your affectionate brother,

[.signed-section-signature]
Joseph Edgerton.

--
