== Chapter III.

[.chapter-synopsis]
* Visit to Indiana Yearly Meeting.

Ninth Month 23rd,
1836.--Having felt drawings in my mind to pay a visit in the
love of the Gospel to Friends in Indiana Yearly Meeting,
and having the concurrence of my friends at home,
I took a solemn leave of my dear family and friends under a
humbling sense of the love and mercy of our Heavenly Father;
and ability was afforded to offer up supplication to the Shepherd of
Israel for his support and protection in every time of trial,
and that He would enable his humble followers to trust in his eternal Name.
My kind friend, Edmund Bailey, feeling a concern to accompany me, we set out,
and arrived at Richmond, Indiana, on the 30th. Attended the Yearly Meeting,
which commenced on Seventh-day following, which was a solid, instructive season.

Seventh-day, the 8th of 10th Month.--Set out towards Blue River Quarter;
attended meetings at Milton and Bethel,
in both which ability was given to relieve my mind,
though mourning and lamentation were the covering thereof.
At Hopewell Meeting,
ability was vouchsafed to labor honestly for the gathering of a number present,
to the teaching of the minister of the true tabernacle, which the Lord has pitched,
and not man.
Attended meetings at Walnut Ridge, Little Blue River, Sand Creek and Driftwood,
in all of which I was enabled to discharge what I had in commission.
May I be kept in such a state of humble dependence upon my blessed Master,
that I may be preserved out of the mixture;
that self may never attempt to take the Lord`'s jewels and deck itself withal;
but that the creature may be kept in such a state of humility,
that every crown may be cast at the feet of my blessed Lord and Master,
with the acknowledgment: "`Great and marvellous are your works, Lord God Almighty;
just and true are all your ways, King of saints.`"

Second-day, rode to Old Blue River.
Third-day, attended their Monthly Meeting, to satisfaction;
and feeling impressions of duty towards the inhabitants of Salem,
notice was given for a meeting in the evening,
which was largely attended by those not of our Society, who were very orderly.
My dear friend, James Hadley, being on a religious visit, joined in the concern,
and through the mercy and gracious assistance of our Divine Master,
it was a favored meeting, and, I trust, the cause of truth did not suffer by it.
The awfulness of the responsibility that attaches to one engaged in the gospel embassy,
is at times very humbling to my mind.
May the Lord, whom I desire to serve, be pleased to preserve,
through heights and through depths, and enable me faithfully to serve Him through all,
being so attentive to his voice,
that on the one hand none of the intimations of his holy will may be shrunk from;
and on the other, that there may not be a going forward without his command;
that so his will may be done; and then, should there be,
through the help of our holy Leader, the crown given as the reward of faithfulness,
all will be laid at the feet of our adorable Captain,
under whose banner we have been engaged, with the humble acknowledgment:
"`That not unto us, O, Lord!--but to your name`" be the glory and praise,
forever and ever.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Tenth Month 21st, 1836.

[.salutation]
My dear Wife:

My heart salutes you this evening in the fresh Sowings of endeared love,
which runs through my heart as a stream, and is attended with a hope,
that He whom I desire to serve, will be pleased to support us in this separation,
and preserve us under his almighty wing in such a humble and dependent state,
that we may be enabled to run the ways of the great
Master`'s requirings with cheerfulness and resignation.
I have been favored to keep pretty cheerful most of the time,
the blessed Master condescending to go before; indeed,
I could not go without the sensible feeling of his presence,
which has been vouchsafed to us beyond what we could have expected.

[.signed-section-signature]
Joseph Edgerton.

--

Seventh-day 22nd, at Quarterly Meeting; and on First-day,
had a public meeting at the same place,
which were owned by the good Shepherd,--particularly the latter was a favored
opportunity,--the meeting closing under a solemn feeling of the Lord`'s goodness,
under which supplication was offered up to Him who is worthy to receive glory, honor,
thanksgiving and praise.
Many hearts were broken into tenderness; and on taking leave of each other,
tears flowed freely.
May the praise be returned unto Him to whom it is due.
That afternoon, had a public meeting at Paoli; my dear friend, James Hadley,
who has been with us for some days, was well engaged,
and I have a hope the blessed cause did not suffer by it.
Third-day, attended meeting at Indian Creek, which was a laborious time.
Oh, the dryness of nominal professors.
I have often thought it the hardest state to reach of any;
but ability was vouchsafed in a very close way to relieve my mind.

From there, rode towards Honey Creek, through mud and water,
in many places up to the horses`' bodies;
and a very narrow escape I had of being much hurt by my horse falling down in a swamp,
and was very near being on me.
Under a sense of the Lord`'s mercy and providential care over me,
may my soul bow in awful prostration before Him who is worthy to be worshipped,
honored and obeyed; and may I be so devoted to the will of my gracious Lord and Master,
that all his requisitions may be complied with.
On reaching Honey Creek, had a meeting there with the few Friends of that place,
and some of the neighbors, which proved a very relieving opportunity,
which is a rich reward for all the fatigue in getting there.

After meeting, set out for Sugar River Monthly Meeting, to be held on Seventh-day,
where we arrived in time,
and peace of mind was vouchsafed as a reward for honest labor to a lukewarm condition;
with encouragement to the mourners in Zion.
We attended meetings at Sugar Plain, Sugar River, Flint and Pine Creek,
in all of which ability was given to throw off the burden that rested on my mind,
and a portion of that peace which passes the understanding of the natural man was,
through the mercy of our holy Leader, vouchsafed.

One other signal deliverance I will mention.
As I was riding with my companion and other Friends, from Sugar River to Flint,
and going across a swamp, my horse mired very deep, and fell and threw me over his head;
but through mercy I was preserved from being hurt, though I got entirely wet,
except my head; but having my clothing with me, we soon went on again,
under a feeling of thankfulness to the Preserver
of men for his watchful providence over me.
May my heart return thanks and praise unto Him who is glorious in holiness,
fearful in praise, doing wonders.

Sixth, attended Select Preparative Meeting at Vermillion, and Seventh-day,
Monthly Meeting at Elwood; but my mind was not so relieved as would have been desirable,
and, probably, might have been the case if I had been more instant in season;
but as it was not willfully done, I passed away pretty comfortably.
First-day, Vermillion and Hopewell Meetings were both relieving opportunities,
though very close labor went forth to the careless sons
and daughters who are sitting at ease in Zion.
Third-day, was at Rocky Run Meeting, at Bloomfield Select Preparative, and Fourth-day,
at the Monthly Meeting, which was a laborious time.
Fifth-day, at Poplar Grove and Rush Creek, which were owned by the good Master`'s presence.
The Select Quarter was a low time; but peace was vouchsafed as a reward for faithfulness,
in some close remarks dropped among them.
The Meeting for Discipline was a time of very close labor;
the seed of life being in such a state of suffering,
that the harps of those who at times were prepared to utter the praises of the Lord,
were for a time hung upon the willows:
but ability was afforded in a remarkably close manner to throw off the exercise,
which I do esteem a great favor.

Had a public meeting at the same place (Bloomfield) on First-day forenoon,
which was a favored season, and ended in solemn supplication.
That afternoon, had a meeting in the town of Rockville,
to which came a large number of those not of our religious Society,
who were very attentive, and the meeting ended well.

[.offset]
+++[+++Here he wrote to his wife:+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Eleventh Month 15th, 1836.

[.salutation]
My dear Wife:

Your letter was very acceptable,
and I could but take notice that the very day
that you entered so deeply into feeling with me,
was a very trying day to me.
We were that day at Milton and Bethel, and the cup of suffering rather exceeded.
I thought it remarkable.
I hope we shall still be preserved alive in the root of immortal life,
where we may be favored to feel each other,
and rejoice in the mercies of our gracious Lord and Master,
who is still disposed to hear the cries of the poor and the sighs of the needy.

[.signed-section-closing]
Your affectionate husband,

[.signed-section-signature]
Joseph Edgerton.

--

Attended White Lick Monthly Meeting, which was a good meeting;
then a meeting at Fairfield, not so favored.
At the Select Quarterly Meeting, silent; and the Quarterly Meeting,
which was a favored time.

First-day, having had a prospect of a public meeting in this place, in the forenoon,
also one for the youth in the afternoon, the appointment was made,
and a day of favor it proved.
He who saw fit to call forth into his harvest, was pleased to favor with his presence,
and to be mouth and wisdom, tongue and utterance, to my humbling admiration.
May the Lord alone be exalted.
Worthy is He to be waited for, followed, worshipped and adored by all his people,
for they experience Him to be their strength in weakness, riches in poverty,
and a present help in the needful time.
Second-day, at West Union; a favored, good meeting.
A number of our friends were with us at our kind friend, David Lindley`'s,
to whom our spirits were closely united in the heavenly relationship.
We parted in much brokenness of spirit,
with mental breathing of soul to the Preserver of men for his all-supporting care,
and that we might be kept in the hollow of his hand,
and finally be granted an admission into the mansions of eternal rest.

We attended meetings at Spring, Mill Creek, Sugar Grove, Fairfield,
Easton and Lick Branch, in all of which the blessed Master`'s presence was near,
giving ability to sound an alarm among them, particularly at the two last-mentioned;
peace was my portion.
Rode to Indianapolis.
Had a meeting with the few Friends there, with some of their neighbors;
and in the evening had a meeting in the town for the inhabitants;
which were relieving in some degree, and, I trust,
the cause of truth did not suffer by it.

Before setting off for Westfield,
we had a very solemn parting at the house of Jacob and Esther Willets,
with several other Friends.
Arrived that evening in the neighborhood of Richland.
Had a meeting on Third-day morning at that place, and in the afternoon at Westfield,
both of which were seasons of suffering, particularly the former,
the seed of life being borne down.
My spirit was clothed with mourning,
under the awful consideration of the state of those who are dead while they live;
thus they glide along in a state of insensibility to their eternal interest.
The reward of peace was afforded in the discharge of duty in an alarming manner.

Fourth-day, at Hinkle`'s Creek; a day of favor.
Openness was felt to declare the way of life and salvation to the few Friends,
and a number not in membership;
the meeting ended with solemn supplication to
the Father and Fountain of all our sure mercies.
Fifth-day, had a meeting at Fall Creek, in which the life of truth was very low;
but ability was afforded in a close, short testimony, to throw off the burden,
and peace of mind was vouchsafed.

First-day, attended meeting at Clear Spring, to satisfaction.
Next at Duck Creek and Elm Grove; the former was a trying meeting.
Ability was given to sound an alarm among them in a very close manner.
At Spiceland Meeting; was a time of suffering to me.
At Rich Square, the lukewarm and worldly-minded were solemnly warned.
There is, perhaps,
no state harder to reach than that in which the world and the
things of the world have gained the ascendency in the heart.

Sixth, attended the Select Meeting at Westfield; seventh-day, the Quarterly Meeting,
which was a season of renewed favor, the power of the Lord being present,
giving ability to proclaim the unsearchable riches of Christ.

First-day, a public meeting at the same place, which was also a time of favor.
We next attended New Hope, Elk and Orange Meetings.
Life was at a very low state, being so little of the essence of religion known,
that I thought the ways of Zion do mourn because none come to her solemn feasts.
From there to Richmond, to our kind friends, J. and J. Smith`'s.

[.offset]
+++[+++Here he wrote:+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Richmond, Twelfth Month 15th, 1836.

[.salutation]
My dear Wife:

The fatigue and danger of getting about have been great;
though when compared with the awful service in which we are engaged,
it sinks into insignificance.
It is, indeed,
very humiliating to the creature to feel constrained to go about in this way,
exposing ourselves and appointing meetings,
and at the same time sensible that of ourselves we can do nothing.
This is walking by faith, and not by sight.
But I can acknowledge to the praise of Him who has called us,
that He has not forsaken in the hour of utmost need, but has been strength in weakness,
riches in poverty, and, I believe, will still continue to guide and guard us,
as we confide in Him as a little child does in its earthly parent;
guiding us by his counsel,
and guarding us from dangers on the right hand and on the left.

Many are the baptisms that are meted out to us in passing through this land,
and I can say I looked for it before I left my home;
and I have found in my measure the truth of that gracious assurance:
"`My grace is sufficient for you, for my strength is made perfect in weakness.`"
In most places we have found some who, like the few names in Sardis,
are desirous to walk before the Lord in such a
way that their garments may be kept undefiled;
to these we have been brought very near, under the feeling of that language:
"`One is your Master, even Christ;
and all you are brethren;`" and we have had all the
encouragement from these that could be desired,
which at times has a tendency to bear up;
but that which is never-failing is above all things to be desired.
May the Lord in his mercy be pleased to continue to be our
Director and Preserver in this long and arduous service,
to his praise and the peace of our minds, and permit us to return to you;
for I can appeal to Him who is the Searcher of hearts,
that it was from sincere apprehensions of duty to Him,
and through the constraining power of Christ,
that I was made willing to leave all that was dear in this life,
and endeavor to follow Him through distant lands.
May his great and worthy name be exalted forever and ever.
It is great in Israel; in Salem also is his tabernacle, and his dwelling-place in Zion.

My heart is full of endeared affection for you, that if I were to try to put it on paper,
my sheet would be too short; but I may say that I have felt,
and do feel you in that which is more than natural, even in the seed of immortal life,
in which, I hope, we shall be kept firmly established upon that Rock,
against which nothing shall ever be able to prevail;
being permitted not only to partake together of the afflictions of the gospel,
but also to have the song that is ever new put into our mouths, even praises to our God,
who has dealt marvellously with us.
May I be preserved in such a state of humble dependence upon Him,
that his holy will respecting me may be done,
and all the praise be ascribed unto Him to whom it is due.
We have attended the meetings of four Quarterly Meetings, and about one-half of the fifth.

First-day, the 18th.--We attended the Monthly Meeting of New Garden yesterday.
Our blessed Lord and Master was pleased to own us therein,
giving ability for service required,
a part of which was in a close and searching manner to the careless
sons and daughters whose eyes are blinded by the god of this world.
The peace vouchsafed therefor was such as richly
compensated for the cold and hardship attendant thereon.
May my soul dwell under the remembrance of his many mercies,
for they are indeed great and marvellous beyond what I could ask or think.

I informed in my last of my prospect of going to Mississinewa;
the road at that time was so bad we declined it,
and for a time I was in hopes of getting clear of it; but for some days it has returned,
and if it continues with me, we may probably go.
I do not forget our dear children, though I do not say much to them, my sheet forbids it;
but, in a word, my love is to you;
and those who are the oldest I want to be good examples to the younger,
and do all you can to help your dear mother.
There are several subjects that I should gladly have touched upon,
that were mentioned in your letter, but I have not room.
Suffice it to say, my spirit is with the living in our Yearly Meeting,
who keep to the original ground.
May they be supported in every trial.
I conclude in near and dear affection to you, the beloved partner of my life, and remain,

[.signed-section-closing]
Your loving husband,

[.signed-section-signature]
Joseph Edgerton.

--

Seventh-day, attended the Monthly Meeting at New Garden,
in which our blessed Master was pleased to own us in his service,
giving the victory over the powers of darkness,
whereby many hearts were bowed under a renewed sense of the goodness of the Lord.
My soul was humbled in an awful feeling of the love of
Him who has called forth into his service,
which was a rich compensation for the fatigue of travelling through the cold.
First-day, were at White Water, which was a time of favor.

Next, West Grove, Fairfield and Springfield Meetings, all of which were favored,
particularly the latter, in which truth rose into dominion,
and the meeting ended in prayer and praise to Him whose is the kingdom,
the power and the glory, forever and ever.
The meetings at West River, Nettle Creek, Flat Rock and Westbury,
were also favored with the good Master`'s presence.
Rode from there to the settlement on the Mississinewa River;
got to Muncy Town that evening, on White River, and found that the river was so high,
that it was past fording;
which caused me to examine the ground to see
whether I had been mistaken in turning this way.
On trying the matter as well as I could, I became settled and quiet.
We were informed of a mill-pond whereon some had crossed that day.
We felt willing to go on it, and crossed on the ice safely,
and felt thankful to the Preserver of men for this and numberless other favors.
May my soul never forget all, nor any of his benefits, but be preserved in a humble,
feeling sense of his abundant goodness towards us.

Here we attended meetings at Back Creek, Deer Creek, Mississinewa,
and again at Back Creek,
in all of which the good Master was pleased to be near and afford
ability for his service in a very close and searching manner to the
careless sons and daughters who were invited to come,
in the language: "`I counsel you to buy of me gold tried in the fire,
that you may be rich; and white raiment, that you may be clothed,
that the shame of your nakedness do not appear.`"
And to an exercised remnant the language of encouragement flowed freely.
The reward of peace was vouchsafed to my soul,
which is a rich compensation for all my fatigue
and exercise over the rough and icy roads.

Set out on Fourth-day morning towards White River.
It was a beautiful morning as to the outward, and through Divine mercy,
was an emblem of the feeling which pervaded my mind,
which was as a morning without clouds.
After arriving we attended meetings at Callier Creek, Sparrow Creek, Dunkirk,
White River and Jerries,
in all of which the good Master furnished ability for his service;
some of which was in a very close and searching manner to the lukewarm professors.
My mind, I think, was never so sensibly clothed with distress and mourning,
on account of the situation of this class who are taken
up with the gifts and forgetting the Giver.
The language of the mournful Jeremiah might be adopted:
"`The ways of Zion do mourn because none come to her solemn feasts.`"
The language of encouragement flowed to a remnant who are in good
degree concerned to seek after durable riches and righteousness.
May my soul bow in awful prostration before Him who is glorious in holiness,
fearful in praises, doing wonders.

First-day, 1st of First Month, 1837.--Were at Arba, which was a satisfactory meeting.
Next day, at Lynn and Cherry Grove; the former was a time of renewed favor.
My great Master was pleased to open the spring of gospel life and to
furnish ability to declare the exceeding riches of Christ.
The latter was silent.
I think I never saw more sensibly the necessity of an example of silence.
It is greatly to be lamented that in some places there is a ministry exercised which,
at best, is but in the will of man, and, therefore,
instead of being living ministers of the gospel of life, they are ministers of death;
which is very trying to the rightly exercised.

Third-day, at Center and Newport;
the latter was a good meeting--the power of truth arose into dominion over all.
The meeting ended in solemn supplication.
May my soul remember the many mercies of our God, and not forget any of his benefits.
Next attended meetings at Concord, Dover, Chester and Woodbury,
in all of which there was strength given to declare the goodness of our God;
and in a particular manner, at Chester, ability was granted to proclaim,
the day of the Lord unto the disobedient and
worldly-minded who are in a state of separation from God.
At Smyrna Meeting, the life of truth was very low;
yet a door of utterance was opened in a short, close testimony, in which I had peace.

First-day, were at Southfork; the blessed Master`'s presence was with us;
but at West Branch it was a low time, although ability was given to clear my mind,
and left them in peace.
At Lick Branch and Union, my mind was clothed with mourning; indeed,
it has been much so since being in this Quarter,
under a feeling of the great declension from ancient purity.
The love of the world having gained the ascendency, a door is opened,
and among others a root of bitterness has sprung up, whereby many are defiled.
In the latter meeting, my soul was drawn into vocal supplication unto the Lord,
on behalf of his Church,
that He would be pleased to remember his heritage in every part thereof;
that inasmuch as He had been pleased to gather us to be a people,
and has manifested his power and goodness in preserving us from age to age,
that He would still continue his guardian care over us, and draw us nearer unto himself;
that the clouds that hang over us might be dispelled;
that He would in his mercy enable his humble,
dependent children to contend earnestly for the faith once delivered to the saints,
that so there might be an increase of that living, upright zeal,
which is called for at our hands.
The reward of peace was given,
for which my soul returned thanksgiving and praise unto Him to whom it is due.
Fourth-day, at Concord,
in which I was raised to declare the unsearchable riches of Christ, and,
to a worldly-minded state, an awfully alarming warning,
who have made to themselves gods of gold and silver.
The iniquity and danger of their situation was opened to them,
and they were invited to turn about and embrace the
offers of love that have been long extended to them,
that they might be gathered into the fold of eternal rest.

At Mill Creek, the presence of Him whom I desire to serve was afforded,
and strength given to raise my voice in testimony to the goodness of
Him who is of purer eyes than to behold iniquity with approbation,
and who requires purity of heart.
Left them in peace.
At Randolph,
my gracious Master was pleased to raise my voice as a
trumpet to declare unto Jacob his transgressions,
and to Israel his sins; and although life seemed low for some time,
yet it gradually arose, and a sword was given me,
and ability to use it in a very close way upon a spirit
of indifference concerning the one thing needful,
being taken up with the money-getting spirit.
The danger of their situation was clearly pointed out to them, and they invited to come,
taste, and see that the Lord is good;
that they might be raised out of darkness into God`'s marvellous light,
and be enabled to walk before Him in the way that is well-pleasing in his sight.
And encouragement flowed freely to the true laborers for their help and strength;
that they might be enabled to persevere in the race set before them,
maintaining a daily watch whereby they might experience preservation from every snare,
looking forward to the mark for the prize of the high calling of God in Christ Jesus.
From there we went to Miami Quarter, and attended Sugar Creek Meeting.

[.offset]
+++[+++Here he wrote to his wife:+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
First Month 14th, 1837.

[.salutation]
My dear Wife:

Your sweet and consoling letter was strengthening to me.
I have no doubt we have been made to drink together, though far separated,
both of the cup of suffering and rejoicing, feeling with and for each other;
and at times under the influence of his spirit who helps our infirmities,
enabled to put up our petitions unto Him who remains to be good to his people,
and unto whom we can appeal, that the separation,
privations and trials to which we have been exposed,
have been from a settled conviction that it was his blessed will,
being united to each other in the seed of immortal life, where, I trust,
we shall be preserved on that immovable foundation, united to the living in our Israel,
who are waiting for the consolation thereof, who are at this time of great treading down,
clothed with mourning and weeping, as between the porch and the altar, saying:
"`Spare your people, O, Lord!--and give not your heritage to reproach.`"

I feel much for my dear friends at and about home in their peculiar trials.
I hope they will be favored with that wisdom which is from above,
whereby they will be directed aright in every step they take,
and not be driven by any of E. B.`'s threats from the ancient ground.
My faith is unshaken, that as we keep there we shall be preserved a people to his praise;
and though many may fall on the right hand and on the left, we shall,
through Divine mercy,
have to experience that "`He that dwells in the secret place of the Most High,
shall abide under the shadow of the Almighty,
that no evil shall befall nor any plague come nigh.`"
My dear children,
it did my heart good to hear that you felt interested
in helping your dear mother in my absence,
for I know her trials are great, many ways.
I hope and believe you will continue to be kind and obedient to her;
and if it is the Lord`'s will to bring us together again,
we shall meet under feelings of thankfulness unto Him
who rules in heaven above and in the earth beneath.
I must conclude, and remain to you, my dear, in the fellowship of the Gospel,
your loving and affectionate husband, and to you, my dear children,
your tender and affectionate father,

[.signed-section-signature]
Joseph Edgerton.

--

First-day, at Springborough.
I left with peace of mind.
Rode that evening to Miami, where my mind was closely proved,
and retired to rest under feelings of mental poverty, dispensed, no doubt,
to show that the excellency of the power is of God, and not of us.
Awoke in the morning under the calming influence of heavenly love.
Second-day, at Waynesville and Turtle Creek,
in both of which my good Master was pleased to be near,
and to own us by his life-giving power and presence; particularly in the latter.
May the praise be ascribed unto Him who is matchless in wisdom, in might,
dominion and power.

We arrived at Cincinnati on Third-day evening,
and were kindly received by our dear friend, William Crossman.
Were at their Monthly Meeting on Fifth-day; and in the evening, had a public meeting;
both seasons of favor, particularly the latter.
Sixth-day, rode back to Miami,
and attended meetings at Harveysburg and Caesar`'s Creek on Seventh-day;
in both of which the great Master was pleased to
manifest himself by the breaking of bread;
the latter was eminently crowned with his presence,
and the meeting closed with solemn supplication unto Him who is glorious in holiness,
fearful in praises, doing wonders.

First-day, at Richland, where, after a considerable time of silence, I was raised up,
and led on the subject of the different dispensations,
that which was given by Moses and that which came by Jesus Christ;
wherein was opened the great difference between them, and that John the Baptist was of,
and belonged to the former.
For some time there appeared to be great opposition; but towards the close,
truth got the victory; and after the meeting closed,
I observed a female who was so broken down,
that she had much ado to refrain from weeping aloud.
May the Lord be praised for all his works.

Second-day, were at Newbury Monthly Meeting,
which was owned by the Master`'s presence being near,
to heal and restore to perfect soundness all who come unto Him in living faith.

Third-day, at Clear Spring, wherein the stream of life was very low;
but ability was given to labor in a very close manner to a self-righteous state;
and I had to tell them that Satan had been among them,
and had drawn them from that state of littleness
that some of them had experienced in days past.
They were admonished to come to that situation, of mind,
in which true charity might be maintained, each esteeming others better than themselves.
Towards the close of the meeting,
information was given that a committee from the
Quarterly Meeting wished to introduce a subject,
and desired the shutters might be raised, which was done,
and the state of the meeting thrown open, by which it appeared,
that meeting had been under the care of a committee for twelve months.
It appeared they had let in a spirit of contention,
and coldness towards each other had ensued.
It was very humbling to me to learn the situation of
the meeting as opened by the committee,
which had just before been laid before them.
Another instance of the correctness of ministers
not being filled up with information beforehand.
Had I known of this difficulty before, it would have been an embarrassment to me.
May the Lord be praised for all his works.

Next, attended Fall Creek and Fairfield Monthly Meetings, to satisfaction.
Attended the Select Quarter, and also the Quarterly Meeting,
which was crowned with the presence of the Head of the Church.
First-day, at Walnut Creek, which was a crowded meeting, and a very open time;
ability being furnished to declare the unsearchable riches of Christ,
which was humiliating to the creature.

Third-day, the 21st, had a meeting at Green Plain; then left in peace,
and rode to Carmel, where we had a meeting on Fifth-day, which was,
through the Lord`'s mercy, a favored opportunity.
Sixth-day, at Westland and Goshen; both favored meetings, particularly the former,
the Lord being pleased to own us in his service.
From there we rode to Columbus.

[.offset]
+++[+++And thus closes the account of this visit,
except what is contained in the following extract from a letter to his wife,
dated Second Month 3rd, 1837:+++]+++

[.embedded-content-document.letter]
--

When I last wrote you we were at Miami.
We proceeded to Cincinnati, where my dear companion was taken sick with a prevailing cold.
He was quite poorly, so he was confined to his bed,
which was as close a trial of the kind as I ever met with,
as I had three meetings appointed near Waynesville.
The thought of having to leave him behind,
added to the exercise which attended in that place;
not having his company at either of those meetings, was a close and proving dispensation.
But He who remains to be all-powerful, was pleased to utter the language:
"`Peace! Be still,`" and my poor tossed mind was centered in a peaceful quiet.
I attended the Monthly Meeting, and had a public meeting in the evening,
which was a good meeting.
I left next morning under feelings of gratitude and
praise unto Him who has dealt bountifully with me,
and rode to James Smith`'s, where I was very kindly received by them,
being weary with riding so far through the mud,
and he kindly offered to go with me until Edmund was able.

I have for some time past felt my mind drawn
towards the poor convicts in the State prison;
and although a trial, feeling myself to be but a child,
yet I do desire to be obedient to my blessed Master`'s will,
who has been with us and has done great things for us, whereof we are glad.
From there we expect to go to Alum Creek, and through the meetings thereaway; and then,
I think, if we should be favored to get along as well as we have done,
we may be at home by the 19th or 20th of the month.
Edmund`'s horse is some lame, by which we may be detained,
but I hope way will be made for us, as has been the case many times;
and under feelings of gratitude be it spoken,
we have been favored to get along to the relief and peace of our own minds;
strength being given to throw off the burden, in many instances in a very close way.

[.signed-section-signature]
Joseph Edgerton.

--

[.offset]
+++[+++Extract from a letter to Nathan Hunt:--+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ninth Month 8th, 1838.

[.salutation]
Dear Friend:

My mind has often of latter time been turned
towards you in the sweet remembrance of that unity,
which in my measure it was given me to feel with you when in your land;
and I feel freedom to say,
I hope you will be favored to experience that everlasting Name which
has been your morning light and the strength of your meridian day,
to be also your evening song; being as the shadow of a great rock in a weary land,
that none of the trials which may be permitted to attend, either present or to come,
may have a tendency to depress your feelings too much.

It is indeed a day of peculiar trial to the Church;
the enemy has been very busy in drawing off thousands
of this Society into a disesteem of the Holy Scriptures,
denying the blessed doctrines they contain; and then by turning his snare over,
has drawn many into a spirit that would place them
above that which they declare themselves to be,
designating them the primary rule of faith and practice,
and so falling back again very near to that
which our worthy forefathers were gathered from.
Others who have not gone quite so far are reasoning and contending
about the resurrection of the dead and day of judgment,
coming very near the doctrine of many other religious societies.
But while ours has, and does freely own every part of Christian doctrine,
they deem it unsafe for them to adopt those gross views,
but rather keep to Scripture language that a spiritual body is raised.
Here our forefathers were preserved in inward quiet,
choosing rather to enjoy the fruits of the Spirit in silent waiting before the Lord,
for the arising of that power which they experienced to be
able to raise them from dead works to serve the living God.
In this humble, retired state,
there was no desire to become wise above that which is written,
knowing that secret things belong unto the Lord our God;
but those things which are revealed unto us and to our children.
Thus were they blessed, growing stronger and stronger in the power of an endless life.
Oh, that it might be the experience of all who are making the same high profession;
then it might be said, "`No enchantment can prevail against Jacob,
nor divination against Israel.`"

[.signed-section-signature]
Joseph Edgerton.

--
