== Chapter IV.

[.chapter-synopsis]
Visit to the Yearly Meetings of Philadelphia, New York and New England; Extending to New Brunswick and Nova Scotia.

Having for some time felt my mind drawn to travel to the eastward,
I opened a prospect thereof in our Monthly Meeting, in the First Month, 1839;
and the way being open therefor,
I proceeded to arrange my business in order to leave home.
Being in limited circumstances, it was no small exercise to me;
but I was enabled to commit my dear wife and tender children into the Lord`'s holy hand,
and set out on the 30th of Third Month following, under a solemn covering,
wherein earnest prayers were put up for preservation, in the language:
"`The Lord hear you in the day of trouble; the name of the God of Jacob defend you,
send you help from the sanctuary,
and strengthen you out of Zion;`" which I have no doubt was mutual,
wherein we were enabled to commit, each other into his holy care and keeping.
William Dewees bearing me company,
we were favored to arrive at Westland on Third-day evening, 2nd of Fourth Month,
and went to see our dear friend, Mildred Ratcliff, whom we found very low in body,
but strong in the faith, saying:
"`I feel renewed evidence that I have not followed cunningly devised fables, but real,
substantial truth.`"

Fourth-day, travelled on,
and reached a small meeting of Friends in the
neighborhood of Monallen (where Abel Thomas once lived),
which was held at George Wilson`'s, where,
if we were favored with a true sense of their state, religion is at a very low ebb;
but the reward of peace was given for the allotted portion of close labor.
Second-day, the 8th, proceeded on our way, and arrived at Hannah Gibbons`' on Third-day.
My companion having been unwell for several days past, I had to leave him here,
which was no small trial to me.
Fourth-day, attended Lampeter Meeting, and journeyed on in the evening to Robert Moore`'s,
where I was kindly received and lodged.

Reached the city of Philadelphia on Sixth-day, and may say, that on my way,
as well as on getting there,
my mind was clothed with mourning on account of the unsettled state of the Church,
so that my spirit was brought into very great suffering.
At the Meeting for Ministers and Elders, on Seventh-day; and First-day, at Arch street,
in the forenoon, and Orange street in the afternoon.
Through Divine mercy,
the outgoings of the evening were crowned with peace
and praise unto Him who is the Helper of his people.

Extract of a letter to his wife, as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Second-day morning, 15th of Fourth Month, 1839.

[.salutation]
My dear Wife:

My heart overflows with that tender love,
which has been experienced by us reciprocally,
whereby we are each enabled to enter into feeling for the other;
and truly I have thought, I stand in need of your sympathy and prayers.
The conflicts have been very great since being in this city;
but our blessed Lord has been pleased to be near to support under them.
I may inform you that my health is good, and has been since leaving home.

My dear companion was taken so ill on the way with an attack of pleurisy,
that I had to leave him, and travel on to attend the Yearly Meeting,
and you will easily conclude what my feelings were.
He, however, mended so as to come in on the cars Seventh-day, and is now with me,
considerably recruited.
I can truly say, that I seek not great things for myself,
but feel like only a child in the work.
I have found many dear, sympathizing friends,
and have esteemed it a favor to be brought near to them in spirit.
Had I the privilege of personal communication,
I could say some things which prudence forbids placing on paper, respecting our poor,
shattered Society.
May the Lord be pleased to be near unto those who are
earnestly contending for the doctrines and testimonies which
have been maintained ever since we have been a people,
that through his Divine power the true standard may be
lifted up against him who is the enemy of the Church.
I very often visit you in near affection,
desiring that our blessed Lord may be pleased to be near unto,
and bear up your mind above the waves.
My soul can acknowledge, He is good to his people.
He blesses the "`provision`" of Zion, "`and will satisfy her poor with bread.`"
May we each be preserved in our allotments,
sweet and green in the covenant of Divine life,
where we may have a place in the minds of the Lord`'s faithful children,
who abide with the seed of life, though it may be in suffering, that in his own time,
we may reign with Him, and be one another`'s joy in the Lord.

[.signed-section-signature]
Joseph Edgerton.

--

Second-day, the Meeting for Discipline commenced; which, though trying to the living,
He who gathered us to be a people, was pleased to extend his preserving Arm around,
to the comfort of those who are earnestly contending
for the faith once delivered to the saints.
Fifth-day, at the North Meeting; a season of renewed favor.
Sixth-day, the Yearly Meeting closed.
Seventh day, visited several Friends in the city.
First-day, attended Twelfth street meeting, to satisfaction; and in the afternoon,
at Arch street; silent.
Had the reward of peace, under a belief that I was in my place therein.

Second-day morning,
22nd of Fourth month.--Took leave of our very kind friends in the city,
in a feeling of that sweet unity of spirit which is the bond of peace,
where the members of the militant Church drink together of the refreshing waters of life,
and are as epistles written in each other`'s hearts; being each other`'s joy in the Lord.

Crossed the Delaware river into New Jersey, and rode to Henry Warrington`'s.

Third-day, at Westfield and Chester; the latter a trying meeting.
Fourth-day, at Rancocas in the morning, to satisfaction;
and at Burlington in the afternoon; silent; and left the meeting with peace,
believing that an example of silence was my place.
Fifth-day, at Mount Holly and Easton; favored meetings, particularly the latter.
May my soul bow in reverent gratitude to our holy Head,
who is unto his dependent children mouth and wisdom, tongue and utterance.

Sixth-day, the 26th, at Evesham, which was a good meeting;
the doctrines of the Gospel were, I trust, opened in the "`demonstration of the Spirit,
and of power.`"
May the praise be ascribed unto Him to whom it is due.
Two young women came to me and took leave, desiring a place in my remembrance,
which was spoken with feeling.
The language arose with me: "`May the Lord bless you.`"
In the afternoon, at Upper Evesham, which was large, but not so favored as the former.

Seventh-day, at Cropwell.
On sitting down with them,
it was given me in my measure to experience the situation of the prophet,
in "`sitting where the people sat.`"
No strength to come at anything.
But as I waited patiently,
I was renewedly made sensible of the necessity of these baptisms, to prepare,
through holy Help, to speak to the states of those present.
The power of Truth, in time, arose, and the meeting ended well.
May the Lord be pleased to keep me in a low, dependent state, willing to suffer with Him,
not daring to "`stir up, nor awake my love till He please.`"
First-day, at Haddonfield and New Town; the latter silent, and I thought it a low time.

Second-day, 29th, at Woodbury, to satisfaction; and lodged at Joseph Whitall`'s;
a valuable Friend and minister.
Third-day, went in company with J. W., to Piles grove, a small poor meeting.
Fourth-day, 1st of Fifth Month, at Salem Monthly Meeting, to satisfaction;
rode to John Sheppard`'s and attended Monthly Meeting on Fifth-day.
Rode to William Scattergood`'s and had an evening meeting at Millville,
and a humble hope was granted that the cause of Truth did not suffer by it.

Having felt my mind exercised about a meeting at Port-Elizabeth, there was one appointed,
and we rode to said place, which proved a relieving opportunity.
Seventh-day, rode to Grcat-Egg-Harbor, and attended that meeting on First-day forenoon,
and Galloway in the afternoon, to the peace of my mind.
Third-day, at meeting at Little-Egg-Harbor, which was an open time.
Fourth-day, at Barnegat.
I thought the life of Truth at a low ebb.
Sixth-day, at Upper Springfield; an open time in testimony in a very close manner.
In the afternoon, at Mansfield.
Seventh-day in the afternoon, at Crosswicks; a low time.
First-day, at Trenton and Stonybrook; both of which were favored seasons.

Fourth-day, attended the select Quarterly Meeting at Shrewsbury, and Fifth day,
the Meeting for Discipline; and feeling some attraction towards the inhabitants,
a meeting was appointed for this afternoon, which was a favored opportunity,
ending in solemn prayer unto Him whose is the power, the praise and the glory forever,
Amen.
Rode to Plainfield, and attended meeting there on First-day forenoon,
and at Rahway in the afternoon.
Second-day, rode to New York to John Wood`'s, and wrote; an extract of which is as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
New York, Fifth Month 20th, 1839.

[.salutation]
My dearly beloved Wife:

My spirit salutes you in that
sweet unity which often runs through my heart unto you,
even a portion of that love wherewithal you are loved of our Heavenly Father; desiring,
as for myself, that "`the eternal God may be your refuge,
and underneath the everlasting arms,`" to
support through nil the trials which may attend.
I may say, that as respects our getting along,
we have great cause to acknowledge the goodness of our blessed Lord and Master;
feeling in every step thus taken the truth of the expression:
"`Who is sufficient for these things?`"
yet, in waiting for the arising of the seed of life at times,
when there appears very little opportunity of coming at anything;
in the blessed Master`'s own time, light has sprung up and strength has been given;
sometimes in a very close way, to the relief of our minds;
and thus we have passed along through the State of New Jersey.
We have attended all the meetings therein, and had two with those not of our Society,
to the relief and peace of our minds.

Last Fourth-day we met with Thomas and Elizabeth Robson,
which was very agreeable and strengthening to us; for, in passing through this land,
my mind is often clothed with mourning on
account of the weakness apparent in many places;
yet, it is a comfort to find a seed in most places,
that are "`grieved for the afflictions of Joseph,`"
whose spirits travail for better days.
It is very acceptable and strengthening also,
to hear of the lively feeling you were favored with,
in remembrance of me in a distant land,
wherein ability was experienced to commit me to the care and
keeping of Him whose mercies are over all his works.
Shall I say,
I have thought I have been made to partake of the
benefit of the prayers of my friends at home?
The few lines from were very acceptable.

My dear daughter, I desire your growth in grace; and in order thereto,
you must be attentive to that which shows you what is right and what is wrong;
and you will feel it your duty to do the right; and as you do so, you will feel peace,
and love in your heart; and try to do so always.
Thus your mind will expand,
and you will see the need of guarding against all that is wrong.
We are sometimes, if not on the watch, drawn off into lightness and talking,
and sometimes into fretfulness, but as we are desirous to live as we ought,
we shall be enabled to conduct so through the course of
the day as to feel peace when we lie down at night.
O, the sweet peace such are made to feel!
I well remember how it was with me when I was a boy;
I was under so much concern about getting along rightly that I
thought when going to bed at night I could not go to sleep
without turning my mind unto my heavenly Father,
and if I had not done as I ought,
I was strengthened to pray to Him on my pillow to forgive my folly,
and enable me to do better next time; and then He would give me peace and comfort.
I mention this for your instruction, for I feel at this time, as I often do,
that I could have no greater joy in my children, than to see them walking in the Truth,
submitting to its restraining power,
desiring nothing but that which is consistent with plainness;
there is no way that we can appear so beautiful as to be plain--decent, neat and plain.
Let your dear sisters read this, and may the Lord direct your hearts into His fear,
and into a patient waiting for Him; thus you will be preserved in innocency,
and if it please Him to permit us to meet again,
I trust it may be to our mutual rejoicing.

If the paternal feeling thus conveyed may but be blessed to the strengthening of you,
my dear children, in the path of virtue,
and thereby add a little to the strength of your dear mother,
in the arduous task that devolves upon her, my desire will be answered.

[.signed-section-signature]
Joseph Edgerton.

--

Third-day, 21st of Fifth Month, crossed over to Long Island,
and was at meeting at Westbury the next day--a good time.
Fifth-day, at Flushing, which was a very trying meeting,
under a sense of a worldly spirit; but in waiting patiently,
in the blessed Master`'s time, strength was given to throw off the burden.
In the evening returned to the city, and attended select Yearly Meeting on Seventh-day,
which was an exercising time.
The mind clothed with mourning on account of the low state of the church.
The meeting on the whole was a time of great exercise, owing particularly,
to a ministry that was not of the immediate putting forth of the Head of the Church;
which, if permitted, is calculated to destroy the vital interests of the church.

The Meeting for Discipline commenced on Second-day, the 27th,
and continued by adjournments till Sixth-day; which was in degree, favored; yet,
if I was led into a true sense of the state of it, it was a low state of the church.
I was favored to leave in peace, having been enabled to lay down the burden.
May praise be returned to Him, who is waiting to be gracious unto His people.

First-day, 2nd of Sixth Month, at Mamaroneck Meeting--a low time;
but our blessed Master was pleased to appear in His own time,
and gave ability to deliver what appeared to be right.
In the afternoon, at Purchase; a time of favor.

Second-day, at Shappaqua, which was a season of divine favor.
Next, at Croton Valley and Amawalk.
The Lord was pleased to be near and to crown with His holy presence;
"`comforting the mourners in Zion, and the heavyhearted in Jerusalem.`"
May everlasting praise be given to Zion`'s King, who reigns forever and forevermore.
Lodged at William Underbill`'s, who was very kind to us, he going with us several days.

Fifth-day, at Croton, a small meeting, and very few of that number rightly concerned.
In the evening at Peekskill; an open time.

Seventh-day, at Oblong in the forenoon, which was a low time;
seemed hard to come at anything.
In waiting patiently, light at length sprung up, and it was a relieving opportunity.
In the afternoon, at the Branch.
The life of Truth was very low,
if I was favored with a true sense of the state of the meeting.

First-day, were at New Milford, which was an open time in testimony,
though the life of Truth did not rise so high as at some seasons.
Rode to Hartford;
and feeling my mind drawn to have a meeting there in a house belonging to Friends,
we accordingly had one appointed, and though very small,
the reward of peace was given for this act of dedication.
Set out in the afternoon towards Providence, where we arrived on Fourth-day evening,
and were at meeting there on Fifth-day, to satisfaction; several Friends being present,
who were on their way to Yearly Meeting.

Sixth-day, at Somerset in the forenoon, which was a good meeting,
and ended in prayer and thanksgiving unto our holy Head.
May the praise be ascribed unto Him to whom, indeed, it is due forever and forevermore.
In the evening, at Fall River, which was an open time in testimony.

Seventh-day, at the Select Yearly Meeting; rather a low time.
A few words near the conclusion, to the relief of my mind,
and to the satisfaction of faithful Friends.

First-day, at public meeting at Portsmouth in the forenoon,
wherein the doctrines of the Gospel were opened, I trust, in some degree of authority.
In the afternoon, at Newport; silent, as to myself,
but Elizabeth Robson and John Wood were acceptably engaged.

Meeting for business commenced on Second-day,
and continued by adjournment till Sixth-day,
during which we were favored with several good meetings;
the Lord being pleased to unite the living members together in the bonds of the Gospel.

Seventh day, attended Westport Monthly Meeting; and in the evening,
an appointed meeting at a Baptist meeting-house, which was an open time,
and the people very orderly and tender.

First-day, at Little Compton in the forenoon; and in the evening at Center;
both favored meetings, particularly the latter.

Second-day, at Newtown and Smith`'s Neck; the former a relieving opportunity,
but the latter not so much so.

Third-day, at Allen`'s Neck in the forenoon;
and feeling my mind drawn towards the inhabitants of Westport,
we had a meeting appointed there in the evening.
We crossed over in a boat, the river being a mile wide; and owing to the tide being down,
we had some anxiety lest we should not get over in time, but we succeeded well,
and reached the place in good season, to which a considerable number came,
who were quiet and orderly;
and through the continued mercy of the "`Shepherd of Israel,`" we had a good meeting.

Fourth-day, at Dartmouth Monthly Meeting, which was very crowded;
I suppose one thousand persons were present.
The blessed Master was pleased to be near, being mouth and wisdom, tongue and utterance,
to declare the unsearchable riches of Christ.
In the Meeting for Discipline,
my mind was much exercised on account of the low state of things amongst them,
but was favored in a close manner to throw off the burden.

Fifth-day, attended the Monthly Meeting of New Bedford, which was a very exercising time.
My mouth was sealed until in the Meeting for Discipline, way was made tor my relief.
Feeling drawn to visit Women`'s Meeting, it was readily granted,
which also conduced to my relief;
so that my soul can acknowledge that it is good to wait the Lord`'s time.

Sixth-day, at Long Plain and Acushnet, to the relief of our minds.
We called to see our ancient friend, John R. Davis, and found him in a very sweet,
lively state of mind, which was to us like a brook by the way.
Mourning is much my lot of late, on account of the dear young people,
who seem to have taken wings and very much left the Society.
Seventh-day, at Rochester, a poor little meeting.

First-day, at a meeting at Sandwich, which was, I trust, a time of instruction to some.
In the evening had a meeting in the town, which was very large.
My poor frame was made to tremble under a sense of the awfulness of the occasion;
but through Holy Help, I trust, the good cause did not suffer by it.

Second-day, rode to Falmouth, and in the evening had a meeting there, which was,
through the goodness of Israel`'s Shepherd, a good meeting.

On Third-day morning, took steamboat at Woods-Hole for Nantucket,
a distance of forty miles, where we arrived at Prince Gardner`'s, who met us at the wharf.

Here he writes to his wife, as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Nantucket, Seventh Month 2nd, 1839.

[.salutation]
My dear Wife:

In that near and tender affection which time nor distance can erase,
I again salute you, under a lively remembrance of your affectionate kindness,
as also your sympathy and travail of spirit with me in this arduous engagement,
being a companion in tribulation in the Gospel;
and I can acknowledge that it is very helpful and strengthening to be
made sensible of the exercise and prayers of my dear friends at home,
as well as abroad.

We are now at the house of our kind friend, Prince Gardner, on this island,
in usual health, though we were much fatigued,
having been very closely engaged since New England Yearly Meeting.
I remember your kind hint about overdoing the matter,
and wish to be careful in this respect;
but very often do I remember the strong claims
which you and the dear children have upon me;
and I have felt a liberty, as strength holds out and way opens for it,
to improve the time diligently.
I can acknowledge, "`Hitherto the Lord has helped us.`"
May my soul bow in humble prostration before Him.
Fell in with our dear friends, T. and E. Robson, and Daniel Wheeler,
coming to this island, which was very grateful to us,
including many other dear friends with whom we became acquainted at the Yearly Meeting.

My dear love is to our children; my heart overflows there with.
I desire, dear children, that you may "`know the God of your`" dear father and mother,
"`and serve Him with a perfect heart and a willing mind;`" for I can say from experience,
that He is good to his servants,--to those who
are willing to submit to his restraining power;
to these He gives the rich reward of peace,
even a reward that the world cannot give nor take away.

[.signed-section-signature]
Joseph Edgerton.

--

Fourth-day, at the Select Quarterly Meeting;
a time of close exercise in "`searching the camp.`"
Felt the reward of peace for allotted service.

Fifth-day, at the Meeting for Discipline, which was a favored season.
Adjourned to four in the afternoon.
Friends from Westport did not arrive until the afternoon sitting,
in consequence of contrary winds.
Our dear friends, Elizabeth Robson and Daniel Wheeler, had good service.

Sixth-day.
Attended a meeting appointed by the former, to satisfaction.

Seventh-day, my dear friend, Elizabeth Robson, and myself,
having felt drawn towards the select members,
concluded to have a meeting with them this morning,
in which weighty service the Lord was pleased to be
near and strengthen to labor honestly among them,
to the relief and peace of our minds.

In the evening had a meeting with the colored people, to satisfaction;
also had a good meeting on First-day forenoon;
and having felt my mind drawn in gospel love to the poor seamen,
a general invitation was extended to them for a meeting this evening,
in which the blessed Master was pleased to be near, being mouth and wisdom,
tongue and utterance; and his great and holy name was exalted over all.
Dear E. Robson was lively in supplication.

Second-day morning, left peacefully, and had a very pleasant passage to the Continent.
Rode to Yarmouth and lodged, and were at meeting there on Third-day,
which was an open relieving time.
From there to Moses Rogers`', near Pembroke, and were very kindly received.
Attended meeting there on Fifth-day, to satisfaction;
and in the evening had a meeting at M. R.`'s house,
which was an open time in declaring the unsearchable riches of Christ;
I trust in some degree of gospel authority.
The people were quiet and orderly,
and the meeting ended in prayer and thanksgiving unto Him, "`who is glorious in holiness,
fearful in praises, doing wonders.`"
May my soul bow before Him to whom all praise is due.

The following is an extract of a letter written to P. and A. S., at this place:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Seventh Month 12th, 1839.

[.salutation]
Dear Uncle and Aunt:

Having a little leisure this evening,
after a travel of thirty-eight miles today; and something, I trust,
of that feeling of unity which has been our experience in days past to flow towards you,
as also your children, I write.
And although we have been much engaged in the service,
for which I have been made willing to leave all that is near and dear in this life,
I have often felt my mind turned towards my dear friends at home;
not doubting that many of them can reciprocate the language:
"`The Lord hear you in the day of trouble, the name of the God of Jacob defend you,
send you help from the sanctuary, and strengthen you out of Zion.`"

Indeed,
I think I should not be overrating the matter were I to say I have been
sensible of the benefit of the unity and exercise of my dear friends at home.
Many are the baptisms permitted to attend in such an embassy as this,
whereby He is showing that this treasure, dispensed in earthen vessels,
is of his own immediate preparing and pouring forth,
that the excellency of the power may be of God, and not of us;
that all the praise may be given unto Him who is "`Head over all things to his Church.`"

Notwithstanding the state of the church is such (if I have had a true sense
of it) that in many places the mournful language would be applicable,
"`By whom shall Jacob arise, for he is small;`" yet a remnant is preserved,
and appears firmly attached to the good old way--the
way of Truth as professed by our religious Society;
that it affords hope in the midst of discouragement.
In traveling in New England,
I have been struck with the great difference in the feeling
manifested toward Friends how compared with that of many years ago;
there now appears great openness in most places.
We have had several crowded meetings amongst those not of our Society, and mostly open,
relieving opportunities, giving ground to hope the cause did not suffer thereby.

I may acknowledge (to the good Master`'s praise
be it spoken,) the "`little meal in the barrel,
and the oil in the cruse,`" have not failed; but have been renewed from time to time,
so that we have been enabled to proceed, to the relief and peace of our minds.
The Yearly Meeting of New England was a favored one.
The important subjects that came before it were disposed of in the wisdom of Truth,
and in much harmony, except that of the abolition of slavery,
in which a spirit appeared that wanted more liberty to
join in the popular associations of the world.
But through holy help, it was in a good degree chained down,
and the meeting issued suitable advice to its members
similar to that given forth by our own Yearly Meeting.

[.signed-section-closing]
I remain your friend,

[.signed-section-signature]
Joseph Edgerton.

--

Seventh-day, had a meeting at Mansfield, which was an open time.
Rode to Providence in the afternoon,
and were at the Boarding-school on First-day morning to satisfaction;
and in the evening at Friends`' Meeting house, which was a time of close baptism;
though feeling, as I thought, a little opening to arise,
I delivered what appeared to be right, but felt no relief thereby.
May I be preserved in the hollow of the Lord`'s holy hand.

Third-day, at Cumberland and Lower Smithfield,
and I thought the state of religion was at a low ebb.
Attended a small meeting at Burrelville on Fourth-day to satisfaction;
and at Smithfield on Fifth-day, to the relief and peace of my own mind.

Sixth-day, at Mendon and North Mendon; the latter silent.
The people looked anxious, and finally disappointed,
yet I felt calm and quiet under a belief that I
was in my place in setting a sign among them.
May I ever be preserved in a humble waiting state,
willing to be accounted a "`fool for Christ`'s sake.`"
Set out in the morning for Pomphret, and called at the house of B. Joslin,
who with his wife and daughter are members, remote from any meeting,
having come into Society by request some years ago;
and feeling my mind drawn to sit with them in the family,
I trust it was a season of instruction.
The daughter is under a religious concern of mind,
and I felt it my duty to press the necessity of supporting the
testimonies of our Society with consistency.

Pursued our journey and arrived at Pomphret in the evening,
and attended meeting there on First-day: a low time as to the life of religion.
A great portion of the few Friends there seemed so in the world,
that my mind was clothed with mourning under a sorrowful sense thereof.

Second-day, 22nd, had a meeting at Plainfield, which, although a trying one,
peace was my reward for endeavoring to discharge my duty faithfully.
A little parting opportunity with the family where we dined proved a relieving time.

Third-day, at meeting at Foster and Situate; the former a low time;
my mind still clothed with mourning; the evening meeting was a good one,
and my head was lifted above the waves.
May my soul bow in awful prostration before the Lord for his
extension of mercy in raising me from that state of suffering
to the place where I could sing of his mercies.
Set out in the morning for Coventry, and had a meeting appointed there in the evening,
which, I trust, was a time of instruction.

Fifth-day, at meeting at Cranston, a favored time;
and feeling drawings in my mind to Warwick, had a meeting there in the evening,
which was a season of renewed favor.
May the Lord be praised for all his works, for He alone is worthy.

Sixth-day, attended Greenwich and Wickford, to satisfaction;
the former would have been more so had due care
been taken in extending notice as desired.

Seventh-day, at Richmond in the afternoon; the life of religion very low,
being very hard to come at any settlement; yet, in time the spring opened;
and the meeting ended well.
A noted Baptist minister observed to me "`he supposed I
was on a religious visit through this country.`"
I told him I was.
He replied, "`That good Master you have been telling us about will give you your reward;
may He strengthen you in it.
I think I love Him, but I often feel very cold here (raising his hand to his breast),
but I think it is for lack of watching unto prayer.`"

First-day, at Hopkinton,
where I was led to set forth the necessity of knowing the fallow-ground broken up,
whereby the seed of the kingdom might grow and bring forth fruit, "`some thirty,
some sixty, and some one hundred-fold.`"
Dined with our dear friend, John Wilbur,
and attended a meeting at Pawtucket in the evening, to a good degree of satisfaction.

Second-day forenoon, at Westerly, which was a good meeting;
and at South Kingston in the afternoon, where the blessed Master was near.

Third-day, at meeting on the Island of Conanicut,
in which the good Shepherd was pleased to be near,
and enabled me to declare the "`unsearchable riches of Christ.`"
In the course of the meeting,
I was led to speak of the nature and qualification of a true gospel ministry;
and after the close, a Baptist man said:
"`You have been telling us about the right qualification for a gospel ministry.
I am convinced there is no other; may the Lord strengthen you in the work.
I have been comforted, I can truly say, though I feel that I am an unprofitable servant.`"
May the praise be given to Him who is our adorable Leader,
for his works alone can praise Him.
Crossed over to Rhode Island, in order to attend the Quarterly Meeting at Portsmouth;
lodged at John Mitchell`'s, and attended the Select Meeting on Fourth-day,
which was a very exercising time.

Fifth-day, 1st of Eighth Month.--Attended the Quarterly Meeting.
My mind was clothed with mourning, because of the low state of the Church;
but was favored to find relief.
Rode to Fall River in the afternoon, and lodged at Thomas Wilbur`'s,
who has been very agreeably with us for several days.

Sixth-day, at Freetown, to satisfaction.
On arriving at Luther Linkin`'s, in the evening,
I learned there were a few members of our Society thereaway;
and feeling my mind drawn towards them, had them together at 8 o`'clock,
and hope it was a profitable season.

First-day, attended Uxbridge and Northbridge Meetings;
and if I was favored with a true sense of the state thereof, religion is at a low ebb,
though there is a seeking remnant; and, I hope, to these they were profitable seasons.
When about to leave our lodging-place in the morning, it seemed to me unsafe to proceed,
as I felt my mind drawn towards a company of persons who had become uneasy
with the forms and creaturely activity of the Methodist society,
and had been in the practice of meeting together in silence to wait upon God.
We had a meeting among them at 10 o`'clock.
Many of them appeared to be in a seeking state,
and I trust it was not an unprofitable season to them.
Third-day, at Leicester and Worcester Meetings; the former a laborious time;
in the latter, the state of religion appeared very low.

Fourth-day, rode to Bolton, in order to attend Smithfield Quarterly Meeting there,
having our kind Friend, Josiah Shove, of Uxbridge, for pilot, in his eighty-fourth year.
At the Select Quarterly Meeting, in the evening,
was a time of "`searching the camp;`" but the reward of peace was mercifully extended.

Fifth-day, the Quarterly Meeting for Discipline, which was an exercising time;
the blessed Master was pleased to be; near, and to strengthen for allotted duty.
I find it cheering to meet with Friends by the way, who love the Truth; and feel,
under a renewed evidence of the presence of the "`Son
of Peace,`" that the language may be adopted,
"`Peace be to this house.`"

Seventh-day, at meeting at Richmond; a very low time.
My mind was clothed with mourning,
under a belief that the cause of Truth was suffering in this place;
though in some honest labor among them, I felt peace.
On setting forward early the next morning, it was, as to the outward,
a morning without clouds.
The whole creation wore a beautiful appearance; and through Divine mercy,
the inward bore a near resemblance thereto.
An awful silence covered my mind;
and the sweet distillations of the heavenly dew refreshed my spirit.
My dear wife and children were brought near, and through immediate help,
ability was received to again intercede on her
behalf in the various trials which attend her,
that He who has been pleased to cause this separation,
might be near to support and comfort her by his good spirit.
Oh, the breathings of my soul on her behalf, as also that of our dear children,
that He would preserve them from evil,
and cause the seed of the Kingdom to grow in their hearts.
This centered in again committing them to his protecting care,
whose mercies are indeed over all his works.
Many of my dear friends at, and about home, came separately and collectively,
fresh in my remembrance, with living aspirations on their behalf.
Tears flowed for miles, while Divine and heavenly harmony pervaded my mind.
May my soul bow before Him, and offer the tribute of thanksgiving and praise.

Reached Weare in good season, and experienced a time of favor.
In the afternoon, at North Weare, which was not so satisfactory as the former; though,
I trust, it was a season of instruction to some.

Second-day, had a meeting at Henniker, to satisfaction,
and set out in the afternoon for Lynn, in order to attend Salem Quarterly Meeting,
to be held there, where we arrived on Third-day evening, and were kindly received.

Here he wrote to his wife, as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Eighth Month 14th, 1839.

[.salutation]
My dear and precious Wife:

I again salute you in near and tender affection,
which is unabated, though a vast distance separates us,
and at this time runs through my heart to you and our dear children.
I received your very acceptable letter, which was like a brook by the way,
a great comfort to me that you are favored to bear up so well;
and yet I know you have a great charge resting upon you.
I feel it to be a great mercy, in the midst of many trials, that, as you observed,
such an evidence of peace is granted to us,
that the present engagement is of Divine requisition; it bears up the mind,
and makes hard things more easy: indeed,
such an evidence of the presence of my Divine Master is in mercy given me,
that I cannot wish it any other way than it is,
although I very sensibly feel this long separation.
But my blessed Master knows that I love Him above all, and in his own time, I trust,
He will restore us to each other.
I was also pleased to hear from our farm, and things relative thereto,
and feel thankful to Him "`who daily loads us with his benefits.`"
This brings to mind very freshly a circumstance that occurred some years ago.

While on my way to Short Creek Quarterly Meeting,
my mind was solemnly impressed with the prospect of its
being required of me to leave my dear wife and children;
and for a time, I thought: how could that be?
being in limited circumstances, and having a large family who were dependent upon me,
together with the separation from my dear companion.
And while musing thereupon, the language ran through my mind:
"`If you will give up to follow me wheresoever I shall lead you,
I will be a husband to your wife, and a father to your children,
and they shall not lack in your absence.`"
I mention this for your encouragement, without making more of it than I ought,
for I feel myself one of the least of the family,
yet thankful to Him for his watchful care, both at home and over as.
My mind is often clothed with mourning on account of
the many deviations from primitive purity;
the young people are soaring above the Divine witness in their own minds.
I have felt it my duty to deal plainly with them,
delivering what appeared to be the "`whole counsel.`"

[.signed-section-closing]
In dear love, etc,

[.signed-section-signature]
Joseph Edgerton.

--

Fourth-day, attended the select Quarterly Meeting at Salem,
which was a time of close searching of heart.
Our dear friends T. and E. Robson, were again with us.
My gracious Master was pleased to be near to strengthen for His service.
In the Meeting for Discipline on Fifth-day,
my mind was clothed with mourning on account of a spirit of
insubordination that is lurking in secret places,
on the subject of the abolition of slavery.
I have marvelled to see the working of the mystery of iniquity,
in drawing off the members of our Society into the maxims and policy of the world;
and that too, under the specious pretence of the good work of relieving the oppressed,
in a way that they will be in great danger of swerving from the peaceable,
non-resistant principles of the gospel.

I am more and more convinced that our safety depends upon our keeping near our holy Head;
in a religious body together;
supporting our various testimonies in the good old way
not joining with those who are always ready.
The language of our blessed Lord applies: "`My time has not yet come;
your time is always ready.`"
But to the praise of our holy Head, be it spoken,
there is a power above every other power, that chained down all opposing spirits,
and the meeting ended well.
Took leave of our dear friends in much feeling,
and rode to a meeting appointed for our friend E. Robson,
which I trust was a time of instruction to many.
She feeling a concern towards the ministers and elders of this place,
I united with her therein, which opportunity, I hope will not soon be forgotten.
Taking leave of many dear friends, in near affection, we rode to West Newbury, and lodged.

Seventh-day, at meeting there in the forenoon, to satisfaction,
and at Amesbury in the afternoon,
and although my mind underwent much exercise on account
of a mistake in the notice of the hour of meeting,
I felt the life to arise towards the close, and the meeting ended well.

At Seabrook the life of religion was at a low ebb,
yet strength was afforded to leave the burden where it belonged.
I left in peace, and rode to Epping, and lodged.

Second-day, had a meeting there, a time of favor, I trust, to some.
Third-day, attended Monthly Meeting at Dover, which was a low, trying time;
and feeling my mind drawn to have a public meeting,
notice was given for one in the evening, which was also trying and laborious;
my faith seemed almost to fail for a time,
but through divine mercy ability was experienced to leave the exercise with them.

Fourth-day, rode to North Berwick to attend Dover Quarterly Meeting.
The Select Meeting convened at two o`'clock, which was an exercising season.
The Meeting for Discipline occurred on Fifth-day, which was a time of renewed favor.
E+++.+++ Robson and D. Wheeler had good service.
My mind, however,
was much affected with the unsettlement which occurred at the closing of the shutters,
occasioned by the greater part of the meeting going out;
which I have noticed to be much the case in many places.
I found it my duty to tell them of it,
and to show them the disadvantage it was to such meetings.
Meetings for Discipline are not viewed by many with
that dignity that is consistent with the subject.
O, that Zion might arise and shake herself from the dust of the earth!
I think I never was so filled with mourning over her,
on account of the spirit of the world which has blinded the minds of many,
as since being in this land;
and yet renewed evidences are granted of the continued care of the Shepherd of Israel,
in visiting again and again for our restoration.

Sixth-day, at Oakwoods and Elliot.
In the first my blessed Master enabled me to throw off the exercise,
though I had to mourn over the lifeless state of some present.
I trust it was a season that will be remembered by some.
The latter was owned by the Shepherd of Israel, under whose preparing power, I trust,
the doctrines of the gospel were a little opened.
After meeting, a Presbyterian who was there, acknowledged to the truth of what was said,
saying, "`I fully believe the doctrine of the striving of the Holy Spirit in man,
that it is freely offered to all.`"
He observed that Friends felt very near to him, that they had never felt so near before;
and manifested great tenderness in parting with us, saying, "`Brethren, pray for us.`"

Seventh-day, at Lower Rochester; a relieving time.
In the afternoon, at Chestnut Hill; a very poor meeting.
I was led to compare their situation with that
of Israel when in such a deplorable condition;
the prophets of Baal being four hundred, and the Lord`'s prophet himself alone;
but the Lord was pleased to be with him, and to open a way to try their idol worship.
Through holy help I was favored to relieve my mind, though clothed with mourning.

He again writes to his wife, as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Eighth Month 24th, 1839.

[.salutation]
My dearly beloved Wife:

I received your very welcome messenger,
the value of which can only be estimated by
those who have been placed in like circumstances.
I may inform you that my dear companion received
intelligence of the illness of his daughter Sarah,
about ten days ago;
and in a few days after additional intelligence of her continued illness,
and possibly not long survival; which was a close trial; and on deliberating thereon,
with the unity and sympathy of many dear friends, he concluded to leave me and go home.
He took leave of me yesterday morning and went
in company with our dear friend Daniel Wheeler,
who is going to attend Ohio Yearly Meeting.
It was a close trial to give him up,
but the feeling I had for his family was such
that I could not hold him from going to see them,
with a prospect of his returning should it appear to be right.
I feel the loss, but the blessed Master has been pleased to be near.
Do not be too much concerned about it, for I am among very kind friends.
I have the company of John Buffum, of North Berwick,
and I trust I shall be favored to get along.
If my gracious Master will be pleased to continue to preserve and support me,
and enable me to get through to the peace of my mind,
my tongue will be too short to set forth his praise.

I was pleased with the good account of the children.
I want you, dear children,
to remember that "`the fear of the Lord is the beginning of wisdom,
and to depart from evil is a good understanding.`"
Be willing to submit to the restraints of the Spirit of Truth,
and you will be preserved out of evil.
I can say to you that plainness, as becomes the followers of a meek and crucified Savior,
never appeared to me more beautiful than of latter time.
I want you in my absence, to pay due regard to the judgment of your dear mother.

When in Salem, Massachusetts,
I went to see a woman who had nervous spasms in such
quick succession as to raise her in a sitting posture,
and then throw her back on her bed with great violence;
She has not been known to be asleep in eight years so as not to hear the clock strike.

She has been convinced of the Truth, as professed by Friends,
since she has been in this condition, and uses the plain language.
She seemed much pleased to see us, and would converse sensibly between spasms.
She said the Lord had been good to her.
I thought her case a remarkable one.
Her name is Sarah Purbeck.

[.signed-section-signature]
Joseph Edgerton.

--

First-day, at Meadsborough, which was an open time.
At New Durham in the evening, to satisfaction.

Second-day, at Pittsfield, which, I trust, was a season of instruction,
though the seed of Life is under suffering.

Third-day, at Gilmanton Meeting, which was a season of favor.
Rode to Wolfsborough in the evening, and lodged at Lindley M. Hoag`'s,
and attended their meeting on Fourth-day; which was a low time.
Silence was my lot among them.
Rode from there to South Sandwich; passed in view of Winnepisiogee Lake,
a very magnificent scene, surrounded by rough highlands,
and dotted with numerous islands.
The lake is said to be thirty miles in length, and contains 365 islands.
The beauty and excellency, as well as the greatness and power of the eternal Jehovah,
are displayed in his works.

Fifth-day, at South Sandwich and North Sandwich Meetings, which were well attended; and,
I trust, through Divine mercy, the good cause did not suffer.
Set out early in the morning of Sixth-day to Parsonsfield,
and arrived in time to attend a meeting there, appointed for our dear friend, E. Robson,
wherein she had good service.

Rode in the evening to Cornish, and had a meeting in a school-house on Seventh day.
My mind was turned in a lively manner towards my dear friends at home,
this being the day of our Select Yearly Meeting.
May our Holy Head he near to strengthen and refresh them by his life-giving presence,
enabling them again and again to rejoice therein, that the whole heritage may be watered,
and Zion arise in her ancient beauty.
Oh! may you be pleased to arise in power,
and scatter the clouds that hang over your heritage, for "`strong is your hand,
and high is your right hand;`" that your people may, through your power,
go forth in your great and glorious work, that your poor, who depend on you,
may be sustained in every trial that may he permitted.
Oh! be a spirit of judgment to those who sit in judgment;
and "`strength to them that turn the battle to the gate;`" that every
spirit that would lead off from the doctrines of the Gospel,
as you have opened them to us, may be kept down, that your people may rejoice in you,
for you are worthy of all praise and glory, forever.
Amen.

First-day, 1st of Ninth Month.--We attended meeting at Parsonsfield, to satisfaction:
and in the afternoon were at Limington Meeting, which was large,
many of the inhabitants of the town coming in.
For a time there seemed to be very little settlement of mind,
so that my faith almost failed me;
but as I endeavored to centre my mind on my gracious Master, a little light sprang up,
and strength was given to arise with these words: "`Be still,
and know that I am God;`" and matter arose in my mind as fast as I was able to utter it.
A very solemn feeling was spread over us, and the meeting ended well.
May the praise be given unto Him from whom all strength comes.

Third-day, were at Falmouth in the forenoon, and at Portland in the evening; where,
if I am not deceived, the life of religion was very low.
After the public service was over, I requested the members to stop;
when I felt it my duty to address them plainly.
Oh, the lukewarmness of many under our name, whereby they are an easy prey to the enemy,
who "`divides in Jacob, and scatters in Israel.`"

Fourth-day, attended the Select Quarterly Meeting, which was an exercising time.
In the evening had a meeting at Gosham, to satisfaction.

Fifth-day, attended the Quarterly Meeting at Falmouth, which,
though a time of deep exercise, was a season of renewed favor.
The doctrines of the Gospel, I trust, were opened in some degree of authority.

First-day, at Leeds; a poor little meeting.
The blessed Master enabled me to leave the burden with them;
though my mind was clothed--as it often is--with mourning,
on account of the lukewarm state of many of our members.

In the afternoon, at Winthrop, to satisfaction.
Went from meeting to the house of Ezra Briggs, where a number of Friends came;
and among them a person who appeared to be under convincement.
A time of free conversation ensued, which, I hope, may prove useful.
I found he was dissatisfied with the forms and
ceremonies of the Calvinistic Baptist society,
of which he was a member.
I desired him to attend to the light of Christ in his own heart,
which had raised in him a desire for something more substantial,
and it would lead him in the way of life and peace.

Third-day, at meeting at Hallowell; a time of renewal of strength.

Fourth-day, attended Select Meeting at Vassalborough.
The good Master was near to strengthen for service required.

My mind has for some time been under exercise from an apprehension
that it was required of me to go to New Brunswick and Nova Scotia;
which has been a very close trial, having been so long from my dear family already.
After having passed several, mostly sleepless nights,
I fully believe it my duty to stand resigned thereto.
I have already ventured to counsel with some of my friends respecting it,
and have received their cordial unity and sympathy, through which I feel encouraged,
and think of laying it before the select member tomorrow.

Here follows an extract of a letter, written to his wife at this time.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Vassalborough, State of Maine, Ninth Month 12th, 1839.

[.salutation]
My dearly beloved Wife:

I again resume the only method in my power
of paying the tribute that tender love prompts me very strongly to,
and may inform you that my health is good;
and having taken it a little more leisurely for some days past, feel rested.
Your acceptable letter, together with one from brother John,
were very reviving to my drooping spirits.
I thought the day before I received yours, if I could get good accounts from home,
I could go on pretty cheerfully, and my desire was remarkably answered.
It was humbling to me to see the kindness of Friends to you and our dear children;
my pen cannot describe the feelings of my heart.
I was glad to hear of your being at Yearly Meeting, though rather unexpected.

It was a great satisfaction to learn that your health has been good.
I do not want you to expose yourself by attending to things too hard for you,
but rather leave it till you can get some one to attend to it.
Your expression of a desire that we may be preserved in the patience,
was strengthening to me; and I desire your prayers,
together with those of the living in Israel, that faith and patience may hold out.
And now I may inform you, that of latter time the way towards Canada,
as expressed in a former letter, seems hedged up, and Nova Scotia set open before me.
I may acknowledge that my Master pointed out to me before leaving home,
that part of his footstool; but as I progressed in the service in this land,
I flattered myself that I should be excused, particularly as our dear friends,
Daniel Wheeler and John D. Lang, were there only a few months ago;
but on coming to Vassalborough, I could see no way but to stand resigned to the service.

Dear John Warren, who is a father in the Church, said to me:
"`My spirit will go with you.`"
My dear, you can understand the depth of this exercise better than I can describe it;
but my gracious Master has been with me in many trials,
and has supported me in this journey beyond anything I could expect;
and shall I not follow Him?
I have visited nearly all the meetings of New England Yearly Meeting,
except some in this quarter which are before me, previous to going east.

Sixth-day morning, 13th.--I attended the Quarterly Meeting at this place yesterday,
which was a favored one; and after its close, the select members met,
before whom I laid the concern above noticed,
and entire unity and sympathy was expressed with me therein,
and encouragement given me to attend thereto, which I felt to increase my strength.
James Jones informed the meeting, that he had for some time felt his mind drawn that way,
but had not seen any way to proceed,
till now he felt willing to offer to bear me company; which is very agreeable to me,
and satisfactory to Friends.
And now I can say, I feel comfortable, and expect to set out in about a week.
I noticed your remarks respecting our meeting.
My desires for my dear friends at, and about home,
are that there may be a settling down in the quiet,
for "`in quietness and confidence`" Divine strength is known,
which will enable us to "`leave the things that are behind,
and press forward,`" where the blessed experience is given of
the "`times of refreshing from the presence of the Lord.`"

I must draw to a close, in near and dear love to you,
feeling nearly united in the covenant of life, wherein I rest your loving husband,
and companion in tribulations, and in some degree, I trust,
of the "`faith and patience of Jesus Christ.`"

[.signed-section-signature]
Joseph Edgerton.

--

Left my dear friend, Daniel Taber`'s, and rode to China to a meeting,
in the forenoon of Sixth-day; and in the afternoon, to South China;
both favored meetings, especially the latter.
Lodged at the house of Ephraim Jones, where we had the company of many dear Friends,
to our mutual comfort.

Seventh-day, rode to Hope, and attended a meeting at 3 o`'clock,
where the life of religion was very low;
though for the sake of a few present (as it appeared to me),
a little opening seemed to arise, and, I trust,
the opportunity will be of advantage to them.
Lodged at the house of D. Lincoln, on the way to Brooks,
and arrived there in time for meeting on First-day, which was large,
and mercifully owned by the Master of assemblies;
and ability was given to declare the "`unsearchable riches of
Christ,`" in some degree of the "`demonstration of the Spirit,
and of power.`"
May the Lord`'s name be praised, for it is his own works alone that can praise Him.

Second-day, attended Monthly Meeting at Brooks; a time of favor.
Dear T. and E. Robson were present.
Attended a meeting of E. Robson`'s, in the evening, which was large, and, I trust,
a profitable season to some.

Third-day, at China Monthly Meeting, which was an exercising time;
but through the Lord`'s mercy, relief was obtained.

Fourth-day, at Vassalborough Monthly Meeting, held at East Pond,
which was a time of renewed exercise; yet, through the Lord`'s mercy,
peace was the reward for allotted service.

Fifth-day, at Monthly Meeting at Fairfield, to satisfaction.
Sixth-day, set out towards the Province of New Brunswick,
in company with my dear friend, James Jones,
in accordance with our afore-mentioned prospect,
with Stephen Jones as assistant companion.
Rode to D. Lincoln`'s and lodged; crossed the Penobscot River at Bucksport,
and reached Ailsworth late in the evening and lodged.

First-day morning, feeling our minds drawn towards the inhabitants of the town,
a meeting was appointed for this afternoon, which was well attended,
and resulted to pretty good satisfaction.

Second-day, 23rd, proceeded to Columbiana,
and feeling our minds drawn towards the inhabitants of that place,
a meeting was appointed, to be held in the evening; and, I trust, through Divine mercy,
ability was given to declare the "`unsearchable riches of Christ.`"

24th.--At Sheldon Gray`'s. He and his wife being
measurably convinced of the principles of Friends;
and they, together with several others who are in a seeking state,
having been in the practice of meeting and sitting down in silence as Friends do,
and we feeling our minds drawn towards them, had a meeting appointed in the evening,
wherein I was led to direct their attention to that Divine Teacher in the heart,
where they might find the "`minister of the sanctuary, and of the true tabernacle,
which the Lord has pitched,
and not man,`" able to open unto them the mysteries of the Kingdom.
The meeting ended well.
May the Lord be pleased to be near and strengthen them to walk in his ways.
I felt glad in believing that the Lord is
visiting even in the remote corners of the earth.

25th.--Had a meeting in the evening in a neighborhood
eight miles distant from the last-named place,
whereto a number of serious people came;
and although no meeting of Friends had ever before been held there,
they sat very orderly, and the meeting was satisfactory.

26th--Lodged again at S. Gray`'s, and may truly say, as it has been in the outward today,
so has it been in the inward; a cloudy and stormy time.
I have had to recur to the time when I was strengthened
to open this prospect to Friends of Vassalborough,
and the feeling unity I received, as well as sympathy in the concern,
which was a strength to me; and the craving desire of my heart is,
that the good Shepherd may be pleased to lead and preserve me on every hand,
so that I may be enabled to move on in his service in all humility of mind,
keeping a single eye to his directions.
My soul feels it to be a very awful service to be
engaged in--going from place to place--and I can say,
"`hitherto the Lord has helped me.`"
May his great name be exalted, now and forever.

27th.--Had a meeting at Coopers, which was small,
on account of notice not having been properly given; but, I trust,
it was a season of profit to some.
In the evening we were at Crawford,
where the people gave but little evidence of being
acquainted with the nature of Divine worship.
I felt it my duty to open to them the true substance of it,
and point out the necessity of coming to the experimental work of religion in the heart,
short of which, all our pretensions thereto would prove in vain.

First-day, 29th.--At a meeting at Milltown, in the forenoon,
in which the people appeared unsettled, and unacquainted with true spiritual worship.
In the afternoon, at Calais, which was, through holy Help, a profitable sea son;
strength being given to declare the "`unsearchable riches of Christ.`"
May the praise be given to Him "`who is glorious in holiness, fearful in praises,
doing wonders.`"

30th.--Rode to St. George, and lodged, and had a meeting there the next day, which,
though small, was a comfortable time; and in the evening, had an open,
good meeting at Pennsfield.

Fourth-day, 2nd of Tenth Month.--Rode to St,. John`'s,
and lodged in a vessel that had for twenty years traversed the mighty deep,
and was then taken up with high tide as far as it could be, and there stationed,
chimneys built, plastered, etc, making a comfortable house.

Here he wrote to his wife, from which the following extract is taken:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
St. Johns, Province of New Brunswick, Tenth Month 3rd, 1839.

[.salutation]
My dearly beloved Wife:

I again resort to the only means in
my power of communicating to you the tenderest feelings that
flow from the heart of an absent bosom friend;
and may inform you, my health is good, for which I desire ever to be thankful;
as to poor travellers, it is an inestimable blessing.
But to feel the sustaining arm of Israel`'s shepherd to be underneath,
while submitting to the various baptisms and trials that are the
portion of those who go forth in an embassy like the present,
is above all things else to be desired; which, through adorable mercy,
has been my experience; though unworthy of the least of his favors.
I have, in company with my companions,
felt drawn towards the inhabitants of several
towns and villages through which we have passed,
and have had meetings with them, which was very exercising to me; but may acknowledge,
that "`hitherto the Lord has helped.`"
May praise be ascribed unto Him "`who is strength in weakness, riches in poverty,
and a present help in every time of need.`"
I have found in many places in this remote corner of the earth, a tender-hearted people,
and a great openness towards Friends, which is very comfortable and encouraging.
John Warren and James Jones, having travelled through here before,
Friends have thereby become better known,
and the way more easy than it otherwise might have been.

I cannot describe the feelings of my heart towards you, in remembrance of the many cares,
exercises and trials, which are your lot.
But it has been a comfort to me to believe that the sustaining
arm of Israel`'s Shepherd has been your support.
O, may He continue to be near, and preserve us in the covenant of life! that when,
in the ordering of his good providence we may be permitted to meet again,
it may be under a feeling thereof, to the praise of his great and holy name.

Dear children! may you be careful to live in his fear from day to day,
trying to do nothing but that which brings peace to your minds;
and thus you will experience the "`work of righteousness to be peace,
and the effect thereof quietness and assurance forever;`" watching over your own spirits,
desiring that you may be enabled to live as becomes the meek and lowly Lamb of God.
But when you feel a disposition to have things a little different from what
your parents wish--a little like some other young people have--remember that
our dear Redeemer has set us an example of simplicity.
He wore a garment without a seam;
and He leads his followers into plainness--into the "`straight and narrow way.`"
I am comforted in believing that the Lord has visited some of you,
and given you at times to feel the emptiness of all things here below,
and raised desires that you might live in his fear.
Attend to these impressions, dear children,
and you will be a comfort to your dear mother; and the Lord will bless you,
and bring you forward in the way in which He would have you to walk, to your own peace.
I must conclude, having a meeting appointed at this place this evening.

[.signed-section-closing]
I remain, your loving husband,

[.signed-section-signature]
Joseph Edgerton.

--

4th.--Attended an appointed meeting at St. Johns last evening, which was large,
and I trust, through holy help, the blessed cause of Truth did not suffer by it.
We crossed the Bay of Fundy today, which proved to be a boisterous time,
yet through the superintending care of a gracious Providence, we got safely over,
landing at Annapolis.

5th.--Rode to Bridgetown, Annapolis, to Joseph Fitz Randolph,
and in the evening had a meeting in a school house,
which was small in consequence of the notice not having been properly spread.

First-day, the 6th.--Had a meeting on the north side of Granville Mountain,
at a place called The Cove;
where there are a few professing with Friends who sometimes meet together to worship.
Public notice was given,
and the blessed Master was pleased to be near and favor us with a tendering opportunity.
In the evening we had a meeting at Bridgetown, which was much crowded, and, I trust,
a little strength was given to declare the "`unsearchable
riches of Christ`" to the people.
May my soul ever bow at the feet of Him who does the works.

7th.--Had a meeting about six miles down the Bay at a Methodist Meeting-house;
and another in the evening at the Ferry, to good satisfaction.

8th.--Were at a meeting at Parker`'s Cove, wherein I was silent;
but dear James had acceptable service.
In the evening, at Young`'s Cove, which was a favored meeting.
Next day called to see the widow Willet and her daughter;
the former appeared in a seeking state; the latter under much discouragement.
I trust it was a season to be remembered.
Rode to our kind friend, J. K.`'s, and had a meeting about four miles up the Bay,
and lodged with Joseph Fitz Randolph.

10th.--Set out toward Wilmot, where we arrived about noon;
and feeling our minds drawn towards the inhabitants of the town,
we had a meeting in the evening to satisfaction.

Had a meeting on Sixth-day evening at Elijah Kinney`'s, which was a fresh trial to me,
as it always appears to be a very solemn thing to appoint a meeting; yet,
through holy help, truth reigned.
May the praise be ascribed unto Him who is the blessed helper of his people.

Seventh-day, 12th.--Started on our way towards Pictou; and after near five days`' travel,
arrived on Fourth-day, the 16th, and were very kindly received,
which we felt to be a comfort Here he again wrote to his wife,
the following being an extract thereof:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Pictou, Province of Nova Scotia, Tenth Month 18th, 1839.

[.salutation]
My dearly beloved Wife:

In the feeling of dear love I again salute you;
being at the house of very kind friends, and in good health; which has been,
through divine mercy, mostly permitted.
I took some cold while crossing the Bay of Fundy,
the wind blowing so cold that I became quite chilly,
but the vessel was so tossed that for some time I thought it
unsafe to leave my seat to go and get my overcoat.
It was a very awful view of the great deep,
but my mind was preserved mostly in the calmness,
not at all doubting that we should get safe to land.
May my soul bow in prostration before Him for his many mercies,
and deliverances in various ways.
I can truly acknowledge that "`hitherto the Lord has
helped,`" and though trials variously do attend,
yet the "`times of refreshing`" are still permitted in
due season to come from his holy "`presence;`" so that,
at times, I could have said: "`It is enough!`"

We found a few individuals near Annapolis who hold a meeting for worship on First-days,
and seem very glad to see Friends.
I hope they are willing to be helped, which I thought they had need of.
There is great openness towards Friends in many places; they see the beauty of it,
but the cross is in the way.
They cannot be Friends in reality without giving up the friendships,
the flatteries and profits of the world; and, therefore,
many remain halting between two opinions;
their better judgment being convinced of the way of Truth,
but yet not willing to submit to its power.
There are a few honest-hearted Friends in this place, but they seem rather unsettled,
some having gone away, and others expecting to go in the spring.

[.signed-section-closing]
Your loving husband,

[.signed-section-signature]
Joseph Edgerton.

--

Seventh-day, the 19th.--Had a meeting in the town of Pictou, which was small;
and the next day attended the meeting of Friends there, which was a good one,
the Lord`'s power being present.
In the evening we had one a few miles distant, in a Presbyterian meeting-house,
which was a time of favor.

Set out on the morning of the 22nd towards St. Johns,
and arrived at Pedigo-Jack on the 25th,
and feeling our minds drawn towards the inhabitants, we had a meeting appointed,
to be held in the evening, which was a trying one for a considerable part of the time.
The people appeared to be very little acquainted with true worship.
After James Jones sat down,
I felt called upon to open to them the nature of Divine worship,
and the way of life and salvation; and the close was more comfortable.

We pursued our journey,
and arrived at the city of St. Johns the 28th. and crossed the river St. Johns.
My mind having been for some time much tried,
soon after getting again seated in the carriage, I read a chapter in the New Testament,
and turning inward unto Him who is the Helper of his people,
I soon felt a holy canopy to cover my spirit,
wherein strength was given to prostrate myself before Him on
behalf of his Church and people in every part of his heritage;
that He would be their stay and their staff in every time of trial;
particularly that He might be near,
and preserve our Society on that foundation upon which
He was pleased to gather and settle it in the beginning.
The different classes were brought fresh and lively to my remembrance,
with fervent breathings of soul for the advancement of the dear Redeemer`'s kingdom.
Many dear Friends were brought individually before me, and in a particular manner,
my dear wife and children,
with desires that He would keep them in the "`hollow of his holy hand,`" and enable her,
the beloved companion of my life, to bear up in my absence,
comfort her in her many trials,
be near unto and preserve those tender lambs committed to our care,
that they might live in his fear; that his holy hand might be turned upon them;
and that we might all be washed in the "`laver of regeneration.`"
During this interval tears flowed freely,
and my heart was made to rejoice in the fresh extensions of Divine mercy.
May eternal praise be returned unto Him, who is worthy, forevermore.

Sixth-day, 1st of Eleventh Month.--Set off in the morning,
but had not travelled far when the hind axletree of our carriage broke, and I,
with the assistance of my friends, made a rough one,
having little to work with be sides an axe.
We then continued our journey, and travelled thirty-four miles that day.
I felt renewedly thankful to the Preserver of men for his watchful care over us,
for had our axle been permitted to break in the night,
while going down some of the hills, the danger would have been imminent.
May my soul praise Him for his mercies and many deliverances.
We arrived on First-day evening at Brooks, and had a meeting at Thomdyke the next day,
wherein I was drawn to lay before the members of our Society present,
the necessity of faithfulness in the various branches of our testimonies.
The reward of peace was granted.
In the evening, sat with the few Friends at Unity,
and such of the neighbors as were willing to attend; to the relief and peace of my mind.
Attended a meeting at Albion on Third-day, which was a time of renewed favor.

Fourth-day, the 6th.--Had a meeting in the morning at the Neck, to satisfaction;
and from there went to Vassal borough to attend the Select Quarterly Meeting,
in which my mind was introduced into deep exercise on behalf of ministers and elders,
desiring that they might be enabled to dwell where ability is
received to labor successfully in the church of Christ.
Ministers thus abiding would be strengthened to
go forth in his service to the honor of his name,
experiencing the "`Lord`'s vestments`" cover the whole man,
whereon is the "`bell and the pomegranate,`" and
the former not to be heard without the latter.
My mind was clothed with sadness,
under a sense of the low state of the ministry in this part of the heritage.

Here he again writes, an extract of which follows:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Vassalborough, Eleventh Monthth, 1839.

[.salutation]
My dearly beloved Wife:

I may inform you that I am now at Daniel Taber`'s,
in good health; arrived safely here yesterday, after an absence of about six weeks.
We travelled 1,250 miles, and had twenty-five meetings.
I can acknowledge that on returning I felt so much relieved, and so comfortable,
that the travel did not seem hard.

When I got here I met William Dewees, and a very pleasant meeting it was.
He seems to have had rather a lonesome time, though Friends were very kind to him.
I may inform you, my dear,
that it is still my impression that my services are drawing towards a close at this time,
which I esteem a great favor from Him who is a good Master; unto whom you, as well as I,
can appeal in the language: "`Lord, you know all things; you know that I love you.`"
A mercy, indeed, that I may be permitted to return to my dear family,
and take a part of your heavy burden.
Hoping before long to have a more comfortable way of conversing with you, I conclude,
and remain, Your affectionate husband,

[.signed-section-signature]
Joseph Edgerton.

--

Fifth-day, the 7th.--Attended the Quarterly Meeting,
the forepart of which was rather trying; but in the latter part life arose,
and strength was furnished me to throw off the burden that rested upon me;
closing with tender counsel to some of the young
who were under the forming Hand for service,
that they might not come forth too soon,
believing that some have thereby injured themselves, as well as the cause; whereas,
had they been willing to "`sit alone,
and keep silence,`" they would have grown in the root of life,
and came forth as valiants in their day, to the honor of our holy Head,
and to the peace of their own minds.
9th.--At a meeting at St. Albans; an open time.

First-day, 10th.--Were at Athens.
The meeting was rather a trying one, and was rendered, as I thought,
more so by some unsavory offerings;
but the reward of peace was given for the allotted portion of service.
On arriving at New Sharon, where a few members reside,
and feeling my mind drawn towards them,
we had notice given for a meeting at 6 o`'clock in the evening.
After which, we rode to Wilton,
and had a meeting with the few Friends there the next day,
which was a season of renewed favor.

In the evening had another meeting at New Sharon, to good satisfaction.
Lodged, and set out the next morning for Belgrade,
where we arrived in time for a meeting in the evening, which,
through the mercy of Israel`'s Shepherd, was a favored time.
May my soul bow before the Lord in awful reverence,
and praise Him for his manifold mercies and blessings.
My mind, in the prospect of before long being released from further service at this time,
feels peaceful and thankful for the favor.
Oh, that all within me may bless and praise his holy name!

14th.--At Sidney, which was a good meeting.
Lodged at John Pope`'s, and in the morning had an opportunity in the family,
which I hope will be remembered.

Sixth-day, 15th, at Litchfield,
wherein the Lord was pleased to manifest his love afresh unto his people.

First-day, 17th, attended Durham Meeting, which was large,
and graciously owned by the blessed Head of the Church, to the refreshing of our hearts;
and Truth signed over all.
May eternal praises be ascribed unto Him, who, in a manner humbling to myself,
has been pleased to be "`strength in weakness, riches in poverty,
and a present help in`" the various exercises and trials that have
been permitted in the course of this long and oft-burdened travel.
My spirit bows before Him in thanksgiving and praise;
feeling now peaceful and at liberty to turn towards home.
Having sold our team and carriage, we intend going by public conveyance.

Nothing appears on record from this time to the date of the following letter:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Barnesville, Ohio, Third Month 20th, 1840.

[.salutation]
Dear friend Joseph Fitz-Randolph:

I have for some time felt my mind drawn towards you,
and the few others professing with Friends in those parts;
unto whom the visitations of my heavenly Father`'s love have been extended
for your gathering into the true "`sheep-fold,`" where the "`Good Shepherd`"
might lead you forth in the "`green pastures`" of life,
where the "`streams`" of that "`river`" that "`makes glad the
heritage,`" are the portion of the "`sheep`" and of the "`lambs.`"
I trust it is in a measure of that love that desires the gathering of
the whole human family into this heavenly enclosure,
that these lines are written; desiring that "`grace, mercy and peace,
from God the Father,
and from our Lord Jesus Christ,`" "`may increase and abound amongst you.`"
And my dear friends, are we not called to great faithfulness to our God,
who has visited us by his day-spring from on high;
and has shown unto us that we must take up the
cross and follow Him in the way of self-denial?

It was in this way that our worthy forefathers grew in the ever-blessed Truth;
counting nothing too near or dear to part with for his great name`'s sake;
and there is the same necessity for us at the present day,
to be faithful to that witness for Him in our own hearts, with which we are favored.
Permit me then to express the earnest desire of my heart for you, that you may,
through the power of an endless life,
stand fast in the liberty where with the Lord`'s people are made free;
counting it but a reasonable duty to give Him the whole heart.
Here you will be led into great watchfulness over your
spirits--over your daily conduct and conversation,
that all may be as "`becomes the gospel of Christ;`" that "`others
beholding your good works`"--the practical,
unaffected piety of your lives,--may have cause
to "`glorify God in the day of visitation.`"
O! I feel much for you in that part of the heritage;
but am comforted in believing that the compassionate
regard of Him who gathers the lambs with his arms,
and carries them in his bosom, and gently leads those who are under religious exercise,
is extended towards you.

May you keep inward and patient,
seeking from day to day to be clothed with the Lord`'s holy fear;
and He will be near to you, even your wisdom and righteousness,
sanctification and redemption--will open to you more and more,
those things which have been hid from the "`wise and prudent, and revealed unto babes.`"
He will unfold to you the doctrines of the gospel of "`our
Lord and Savior Jesus Christ`"--a wonderful display of the
love of our heavenly Father to his creature man.
It was as our worthy predecessors were faithful, that they became more and more settled;
and they had great openings of the scriptures;
and were favored to see the spiritual nature of Christian worship;
for there was raised in them a desire for something more
substantial than that which was in the wisdom and will of man;
even the living eternal Truth.
And being thus gathered together after the manner of the primitive Christians,
waiting for the promise of the Father;
there was opened to them a spring of living gospel ministry, on apostolic ground:
"`If any man speak, let him speak as the oracles of God; if any man minister,
let him do it as of the ability which God gives.`"
And many able ministers were raised up who went forth under his eternal power,
with great boldness and perseverance in the cause of
our holy Redeemer--the "`Prince of Peace,
of the increase of whose government and peace there shall be no end.`"

O,
that the glorious gospel day may more and more come! when "`strong
nations afar off`" may feel the "`rebuke`" of his power;
and that every weapon for the destruction or injury of his creature man,
may be destroyed; or converted to promote his comfort and happiness;
that the "`knowledge of the Lord may cover the earth as the waters cover the sea.`"
That the word of the Lord, through his ancient servant, may be fulfilled,
"`For from the rising of the sun even unto the going down of the same,
my name shall be great among the gentiles;
and in every place incense shall be offered unto my name, and a pure offering.`"

[.signed-section-signature]
Joseph Edgerton.

--
