== Chapter V.

[.chapter-synopsis]
Account of a Religious Visit to Indiana Yearly Meeting and Some of its Branches.

Having for some time felt my mind drawn to attend Indiana Yearly Meeting,
also a few meetings within its limits, I left home the 19th of Ninth Month, 1840;
my dear friend Ralph Cowgill bearing me company.
We reached Alum Creek Monthly Meeting on Second-day, the 21st, by hard driving,
having thirty miles to travel in the morning before meeting.

It being late when we got in, we had no refreshment except what we had with us,
until the meeting concluded, which was near five in the evening.
But the satisfaction of being owned, as I humbly trust, by our gracious Master,
bore up our minds in a good degree, above the sense of fatigue.
The language of encouragement went forth to a tried remnant,
who had been tossed and not comforted; while, on the other hand,
close dealing with some lifeless professors was
included in the mission given me to deliver.
Here we fell in with dear Ann Branson,
whose company and services were strengthening and helpful to us.

Fourth-day, 23rd, attended the select quarter at Goshen,
wherein our good Master was pleased to manifest himself,
to the comfort of the exercised travellers,
as well as to the admonition of those who are
not sufficiently sensible of the obligations,
we, of this part of Society are under, to "`take heed unto ourselves,
and to the flock over which the Holy Spirit has made us overseers.`"
Were at the Quarterly Meeting for Discipline on Fifth-day, which,
though an exercising time, the reward of peace was vouchsafed to us,
poor and unworthy as we are.

First-day, 27th, attended meeting at Richmond.
I was silent, but John Wood was extensively engaged; yet rather a laborious meeting.
Had a meeting appointed at New Garden in the afternoon, which was a time of renewed favor.
Returned to Richmond next morning to attend the Meeting for Sufferings.

Third-day, 29th, the Select Yearly Meeting opened,
and notwithstanding many were clothed with mourning on account
of the inroads which the enemy has made within the camp,
in the midst thereof encouragement was received from the
immediate extension of the presence of our holy Head.

At the public meeting on Fourth-day, dear E. Robson was livingly engaged in testimony,
which was suitably followed in supplication by J. Wood.
The Meeting for Discipline commenced on Fifth-day and continued till Third-day following.
On First-day, previous to the close,
I attended the public meeting at Richmond in the forenoon, which, I trust,
was a season of instruction to many; in the afternoon, at New Garden;
a part of the Yearly Meeting for worship being held there;
both of which were crowded meetings, and in the latter, I trust,
renewed ability was received to declare the "`unsearchable
riches of Christ;`" and the meeting ended in prayer,
thanksgiving and praise.

After the conclusion of the Yearly Meeting on Third-day,
we took a solemn leave of many Friends, unto whom I felt nearly united.
It has been a very exercising time on account of various things,
and prominent amongst them is the abolition subject;
a spirit that does not want to be circumscribed to the limitations of our holy Head,
and keep together as a body: but are saying, "`I pray you, let me run.`"
The judgment of Truth was placed upon it;
but I still fear that difficulty and distress will attend.
The testimony which our holy Head has laid upon us to bear against slavery,
is a righteous testimony;
and it rests upon us with undiminished obligation to be faithful therein.
But I am renewedly confirmed that the only safe way for us to move therein, is unitedly;
and as shall be pointed out by our divine Master.
Then may we look forward with hope and confidence,
that in the Lord`'s time our feeble efforts may be crowned with success.

Took leave of our dear friends T. and E. Robson and J. Wood,
and left Richmond on Fourth-day morning;
and on Fifth-day attended a meeting at Harveysburg, to satisfaction.
Rode to Clarksville in the afternoon,
and attended a meeting appointed for us at early candle light; which, I hope,
was a season of instruction to some.

Sixth-day, 9th of Tenth Month.--We attended Springfield Meeting in the morning,
which was small, owing to the notice not having been sufficiently circulated.
In the afternoon, at Littres Creek, to good satisfaction;
though there was also some deficiency in the notice there;
which concerned Friends regretted.
I have often thought that great care should be taken that notice for such meetings
should be given into the hands of trusty Friends that would attend promptly to it,
as a failure therein very much frustrates the design.

Seventh-day, 10th, at Centre in the forenoon.
Our gracious Master was near and gave ability to
open the doctrines of the gospel unto the people,
many of whom sat solidly.
May the praise be ascribed unto Him who is "`Head over all things unto his church.`"
At Chester in the afternoon; soon after sitting down,
the canopy of heavenly love was spread over us,
and an open door was set before me to declare
the "`unsearchable riches of Christ;`" showing,
that in this gospel day, is fulfilled the ancient prophecy:
"`I will bring the blind by a way they know not;
I will lead them in paths they have not known; I will make darkness light before them,
and crooked things straight; these things will I do unto them, and not forsake them.`"

First day, at Dover in the forenoon--an open, good meeting.
In the afternoon, at Wilmington, to a good degree of satisfaction,
though not so favored as that in the morning.

Set out for home the next day, where we arrived on Fifth-day the 15th,
and found my dear family well,
to our mutual comfort and thankfulness to Him who does all things well.

The following letter was written soon after his return home:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Tenth Month 26th, 1840.

[.salutation]
Dear Daughters:

I thought I could not well omit availing myself of the present
opportunity of sending you a token of paternal remembrance and regard.
You are often fresh in my mind;
attended with desires for your preservation and progress in your studies; so,
not withstanding we are not permitted to mingle together in the social circle,
I doubt not we are often remembered by each other;
and at times in that feeling which would inspire the language,
"`The Lord hear you in the day of trouble, the name of the God of Jacob defend you,
send you help from the sanctuary, and strengthen you out of Zion.`"

I may inform that I stood the fatigue of travelling quite as well as I could expect,
and was favored to return with the reward of peace.
Dear daughters! you know that the anxious desire of your dear father and mother,
is that you may in your present situation be strengthened to walk circumspectly,
not yielding to the suggestions of any to deviate from
the plain way which Truth leads into;
and you will, as you keep to it, realize that peace which the world,
with all its fascinating amusements and pleasant pictures, cannot give,
neither can it take it away from you;
as you are faithful to the good Shepherd who will lead,
feed and refresh in his heavenly fold; where there is joy unspeakable and full of glory.

[.signed-section-signature]
Joseph Edgerton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Letter to E. M.:

[.signed-section-context-open]
Seventh Month 19th, 1842.

[.salutation]
Dear friend E. M.:

I trust it is under feelings of
deep interest in the welfare of our religious Society,
that I have felt my mind drawn to communicate to you, on the present occasion,
what rests with me.
And although the subject is a delicate one that
I wish to bring into view for your consideration,
yet I believe it is intimately connected with the prosperity of this people.
I allude to the case of John Wilbur, which, I understand,
has been under the care of the Yearly Meeting`'s committee,
and referred by them to South Kingston Monthly Meeting.
It appears evident to me that the moving cause
of complaint exhibited against John Wilbur,
was his opposition to the doctrines, or sentiments, of J. J. Gurney.
How far he may have acted imprudently, I know not;
but I have myself been grieved to see so much countenance given to
sentiments at variance with the doctrines of the Gospel,
as received and upheld by us ever since the Lord first gathered us to be a people.
And I hesitate not to say, that so far as that spirit is yielded to,
which would have Quakerism changed,
so as to a little better suit what is called the religious world,
we shall grow weaker and weaker, and finally, the glory will depart from our Israel.

It has indeed touched me in a very tender spot,
to see in the writings of this individual (under the
character of a minister of our religious Society),
views differing very materially from those of George Fox, William Penn, Robert Barclay,
and others; and even to call in question their Christian soundness.
I believe the time will come when all this unsoundness will by judged down;
though it will cause much deep suffering to the living, who dare not touch, taste,
nor handle it, but are engaged to walk in the good old way,
"`earnestly contending for the faith once delivered to the saints.`"
I afresh remember the language of the prophet:
"`And I will bring the third part through the fire,
and will refine them as silver is refined; and will try them as gold is tried;
they shall call on my name, and I will hear them; I will say: It is my people;
and they shall say: The Lord is my God.`"

My faith is unshaken in that Power that gathered us to be a people; and although trials,
one after another, may be permitted to come upon the Church, yet a third part,
after having been sufficiently brought through the fire, will be faithful to their God;
not bowing to any image whatever, that may be set up; and thus,
by his secret sustaining power, demonstrate the truth of the language:
"`It is my people;`" and by our faithfulness in the maintenance of
the testimonies which He has made it our duty to bear,
say, "`The Lord is my God.`"
As I have understood the case of John Wilbur is postponed,
permit me to speak the sincere desire of my heart to you,
as one for whom I have long entertained a high esteem, and say,
be very careful how you proceed in that matter,
lest you take a step that will throw your weight into the wrong scale,
and thus greatly increase the difficulty in Society, and be a step, too,
which the faithful members in other Yearly Meetings cannot recognize.
The minds of many Friends in Ohio have been made sad on account of it.

Oh, I desire the prosperity of your Yearly Meeting,
as well as the prosperity of this people everywhere; and if we keep to the Truth,
it will keep us in every part of the heritage, and we shall be of one heart,
and of one soul, knowing our unity to be in Christ, the Seed;
eating the same spiritual meat, and drinking the same spiritual drink,
we shall become stronger and stronger in the Lord and in the power of his might.
Ah, if Friends everywhere were such a lively and exercised people,
defection in principle, as in practice, could never enter;
all being sensible from which we have been taken--even from the "`hole of
the pit`"--would feel great responsibility resting upon us,
to be faithful to our holy Head,
showing forth the excellence of the gospel of Christ as we have learned of Him.

I drop these hints for your perusal, with fervent desires that you, as well as myself,
together with Friends everywhere,
may have their attention individually fixed upon our blessed and heavenly Master,
where we shall all be engaged to keep to the ancient landmarks,
the doctrines of the Gospel, as they were opened to our worthy fore fathers,
not conniving at anything to the contrary in others,
and then the Church will be preserved in the unity, out of the party feeling,
and know the blessedness of that state spoken of by the Psalmist:
"`Behold how good and how pleasant it is for brethren to dwell together in unity;
it is like the precious ointment upon the head, that ran down upon the beard,
that went down to the skirts of his garments; as the dew of Hermon,
and as the dew that descended upon the mountains of Zion;
for there the Lord commanded the blessing, even life forevermore.

[.signed-section-signature]
Joseph Edgerton.

--
