== Chapter VI.

[.chapter-synopsis]
* Account of a religious visit to New York, Canada, and Philadelphia, taking Baltimore Yearly Meeting on the way.

Having felt my mind drawn in the love of the Gospel to
visit the meetings of New York Yearly Meeting,
and some of those of Philadelphia, taking Baltimore Yearly Meeting on the way,
I left my dear wife and children the 13th of Tenth Month, 1842,
under feelings of near affection, after a solemn season,
wherein supplication was put up to our Heavenly Father
for protection in our different allotments;
that through the various proving dispensations that might attend,
we might be preserved in the hollow of his holy Hand.

Lodged at the house of my dear friend, Nathan P. Hall,
who has given up to accompany me in the visit, with whom I set out on the 14th,
and reached Westland the following evening.
Called to see our dear friend, Mildred Ratcliff, who was in a low state of health,
suffering much from a severe cough, but lively in spirit.

First-day, 16th.--Attended Redstone Meeting,
in which the life of religion appeared lamentably low.
I was favored to deliver what I apprehended to be required at my hands; and left in peace.

We set out on Second-day morning, 17th, towards Hopewell, in Virginia,
and arrived on Fifth-day, 20th, and had a meeting at a small village called White Hall,
the next evening; which was rather a low time; though, I trust,
a season of instruction to some.

22nd.--Had a meeting at Winchester, which, through the mercy of our God,
proved a relieving, good meeting.
May his great and eternal name be magnified and adored forever.

First-day, 23rd, attended Hopewell Meeting at one o`'clock,
that being their meeting hour in consequence of the
Hicksites having the use of the house in the forenoon.
My divine Master,
in his abundant mercy was pleased to be near and strengthen me
to discharge the portion of allotted service.
May my soul be kept in awful abasement,
that everything that is of the creature may be kept in the dust,
and his great and eternal name be exalted over all.

24th.--Rode to Jonas Jenney`'s, in the vicinity of Goose Creek;
a house built many years ago by our friend Jonathan Taylor.
Here my mind was led to reflect on the low state of the church in this land; which,
with the distress attending the cruel system of slavery,
clothes the mind with lamentation and mourning.
May the most High, who rules in the kingdoms of men,
arise for his own name and Truth`'s sake; and hasten the coming of that day,
when "`righteousness shall cover the earth as the waters cover the sea.`"

25th.--Had a meeting at South Fork,
wherein strength was given to declare the "`unsearchable
riches of Christ,`" in this last and lasting dispensation.
The meeting was small; but, I trust, it was a season of instruction to those present.

26th.--At Goose Creek, to satisfaction;
and set off on Fifth-day morning towards Baltimore,
where we arrived on Sixth-day evening, 28th, and were kindly received by Friends there.
The Select Yearly Meeting was held on Seventh-day,
which was a time of great suffering under a superficial ministry.

First-day, 30th, the public meeting was held,
which was a time of suffering on account of a lifeless ministry.
In the afternoon, dear Elizabeth Evans, of Philadelphia, was acceptably engaged,
and I thought it a favored time.

31st.--The Meeting for Discipline was opened; and though very small,
a number of honestly concerned Friends were in attendance.

Fifth-day, 3rd of Eleventh Month, another public meeting was held;
which through divine mercy was a season to be remembered.
Truth reigned over all; and the meeting closed that evening.

[.offset]
The following is an extract of a letter to his wife written at this time:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Baltimore, Eleventh Month 3rd, 1842.

[.salutation]
Dearly beloved Wife:

In near affection I tenderly salute you,
desiring your strength and preservation, in and under the many trials,
tribulations and cumbers, which no doubt surround you.
My mind is at times drawn out in a very tender manner towards you and our children;
believing that He who, I trust, has been the moving cause of this separation,
is able to keep and preserve us in the hollow of his holy hand;
so that it may redound to our advancement in the Christian`'s path,
and be of those afflictions that may work for us "`a
far more exceeding and eternal weight of glory.`"

On arriving in this city we met with a number of strangers from other Yearly Meetings.
Elizabeth Evans, Hannah Rhoads, Ebenezer Roberts and Regina Shober,
from Philadelphia Yearly Meeting; Moses H. Beede, from New England; and Edith Griffith,
from Redstone quarter.
It has been a time of much suffering on account of, what appears to me,
a superficial ministry.
The Select Yearly Meeting closed yesterday,
in which relief was obtained in some close remarks respecting the ministry.
Our dear friends Elizabeth Evans and Hannah Rhoads were acceptably engaged.

My feelings are often drawn towards you, my dear children, in the most tender manner,
desiring that you may be so attentive to the voice of the good Shepherd,
as to experience preservation from everything that might hurt or harm you.
I want you all to be very tender of your dear mother;
she is worthy of your highest esteem, as well as filial regard;
because of her pious care over you,
and her unwearied diligence in providing for your needs.

[.signed-section-signature]
Joseph Edgerton.

--

Sixth-day morning, took the cars for Philadelphia,
leaving my companion to come with the carriage;
arrived that evening and was kindly received by my dear friend Thomas Kite.
Attended the Select Quarterly Meeting on Seventh-day, to satisfaction.

First-day, the 6th, at the North Meeting, which was an open time.
In the afternoon, at Western, which was a dragging, laborious time.

7th.--Attended the Quarterly Meeting, in which the blessed Head of the church was near;
and gave ability for that portion of service required;
for which my soul was bowed in thankfulness for the favor.

8th.--Set off towards New York,
and lodged at the house of our dear friend Christopher Healy.
He had just returned from a tour among the Indians of Wisconsin Territory,
and the meetings of Indiana Yearly Meeting;
and appeared to be enjoying the reward therefor.

10th.--Reached New York, and were kindly received by dear John Wood and family.

[.offset]
Here he again writes to his wife, of which the following is an extract:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
New York, Eleventh Month 11th, 1842.

[.salutation]
My dear Wife:

From Baltimore, where I last wrote,
I took passage in the cars for Philadelphia, and arrived the same evening.
Attended the Quarterly Meeting there on the 7th,
which was the largest meeting of the kind I ever attended.
Our blessed and holy Head was pleased to give us a fresh token for good,
that might be seen even by those who are seeking an
easier way to the Kingdom than by the way of the cross.
I visited several Friends in the city--William Evans, Joseph Snowden, Elizabeth Pitfield,
Samuel Bettle, and some others.
I lodged with Christopher Healy on my way to this place,
which was mutually comforting to us.
I could in measure rejoice with him who had been
favored to perform the allotted portion of service,
and was then enjoying the sweet reward of peace,
while I was still under the weight and awfulness of
extended labor in a foreign and northern clime.
May the everlasting arm be my guard and guide
through all the steps that are yet to be taken,
for truly my soul knows that it is only through the all-sustaining help of Him, who,
when He "`puts forth his own sheep and goes before them,`"
that any can be kept in the newness of the spirit,
and enabled to labor as ambassadors for the King of Peace in
such a way as may redound to the honor of the great Name,
to the peace and quiet settlement of the church, and to the welfare of their own souls.
I have felt so well satisfied that I am in my proper place in the present engagement,
that I cannot wish myself in any other situation.
We have had the company of Prince Gardner, from Nantucket, which was acceptable.
It is said that Rhode Island Quarterly Meeting has laid down South
Kingston Monthly Meeting--a very serious state of affairs.

I often feel the awfulness of the embassy in which I am engaged,
and that it is only under the all-sustaining hand of Israel`'s
God that I can move forward from day to day in the great work,
at a time when that spirit which would lead into the mixture,
and out of that straight and narrow way which the feet of our forefathers,
and the faithful from that day to this, have happily been turned into,
is so busily at work, to sap, if it were possible, the very foundation of Quakerism;
and has, indeed, been too successful in many instances.
Oh, may the Lord continue to lead his poor dependent children;
and show himself to be a hiding-place unto them in all their trials and deep baptisms,
which in his own pure and perfect wisdom is seen to be
necessary for the work whereunto they are called.

[.signed-section-closing]
I remain your affectionate husband,

[.signed-section-signature]
Joseph Edgerton.

--

Attended meetings in the city on First-day, the 13th, to satisfaction,
particularly the latter;
wherein Divine strength was afforded to lay judgment to
the line upon a spirit that is deceptively delusive,
that is weary of the plainness and simplicity of our high and holy profession,
and would eagerly lead into the mixture, to sap the very foundation of Quakerism.
I was led to show them that Truth is the same now that it was in the primitive days;
hence,
the way of the daily cross is the path for us to walk
in,--the very same path that our dear forefathers trod.

My mind has experienced deep exercise on account thereof for many months;
and I have had to mourn because of its baneful effects,
as it alienates the minds of Friends from each other,
and is calculated to lead back again into the world`'s ways, worship and ministry.
May our eternal and holy Head, by his everlasting power,
keep and preserve his heritage from this deception, and establish,
strengthen and settle his poor, tribulated Church, upon "`that Rock,
against which the gates of hell shall never prevail.`"

Left New York on Second-day, the 14th, in a steam boat,
and arrived at Cornwall on the 15th, and had a meeting there, to satisfaction.

16th.--At Clove; which was an open, good meeting.
Also had a meeting at Blooming-Grove, where religion appeared to be at a very low ebb.

18th.--Had a meeting at the Valley, to satisfaction; and one at Marlborough the next day.

First-day, 20th.--At Plattekill, where my gracious Master was near by his Divine power;
giving ability to show the importance of an acquaintance with God;
which is to be realized only by attending to the Divine gift in the heart.
The meeting ended in thanksgiving and praise unto Him whose is the power,
as well as the work.
Truth reigned over all.

21st.--At Platz; which was a very suffering time.

22nd.--At Plains Monthly Meeting;
Divine strength was afforded to labor honestly for the welfare of the Church.
The language of encouragement ran freely to some who were
concerned to build upon that immovable "`Rock of Ages,`" as
well as close labor bestowed on the careless professors.
Our religious Society appears to be in a very low state.
Attended Marlborough Monthly Meeting, held at Plattekill.
A season of Divine favor.
May the Lord be praised, for his works alone can praise Him.

24th.--Had a meeting at Poughkeepsie, to good satisfaction.

25th.--At Beakman; which, through Divine mercy, was a season to be remembered.
An open door was set before me,
and the "`unsearchable riches of Christ`" was freely declared, I trust,
in the "`demonstration of the Spirit, and of power.`"
Lodged at James Congden`'s, and had a meeting at his house,
to a good degree of satisfaction.

First-day, 27th.--At Nine Partners; had a meeting with the pupils in the school.
My Divine Master gave strength to discharge the portion of service required;
though sadness covered my mind in viewing the
great departures from our peculiar testimonies.
I am renewedly confirmed in the belief,
that it is only as Yearly Meeting Boarding Schools are
conducted under religious feeling and weight,
that the object can be reached; for indeed, it appears to me,
that if those who have the immediate oversight thereof,
are not consistent members and testimony bearers; such schools,
instead of being as our holy Head would have them to be,
prove merely a nursery of pride and vanity,
and our dear youth will soar above the Divine gift, take wings, and leave the Society.
May the Lord in his mercy enable the Church to keep to his own divine power,
that its efforts in this important matter may be rendered subservient
to the advancement of the cause which is dignified with immortality,
and crowned with eternal life.

28th,--At Creek Meeting, which was an open time; and at Stanford in the afternoon,
to satisfaction.
Lodged at the house of Sarah C. Hull,
widow of our late friend and fellow-laborer in the Gospel, Henry Hull.
We proceeded forward, and attended meetings at North-East, Little Nine Partners,
and Hudson; then passed on to Saratoga.

[.offset]
The following is an extract of a letter to his wife, written at this time.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Near the city of Hudson, Eleventh Month 30th, 1842.

[.salutation]
My dear Wife:

We have been favored to get along as well as we could expect,
and can "`set up our Ebenezer`" and say, "`hitherto the Lord has helped us.`"
He has afforded such clear evidences of his gracious regard,
that there is not a doubt left of our being in our right places;
though many baptisms and trials are our portion.
The precious seed of life is oppressed and borne down in many places; and sometimes,
where they show us all the kindness that is necessary,
our Divine Master is very unkindly treated, and even kept out,
until his "`head is filled with dew,
and his locks with the drops of the night;`" which makes us feel very sad.
Oh, I have desired that I might be willing to suffer with Him!
Suffering is in large measure dealt out to the faithful members of our religious Society.
I have never had my mind so clothed with mourning on account thereof, as of recent time.
A spirit is in the camp which leads into the mixture,
compromising our peculiar testimonies,
and thus carrying back into that which our dear forefathers were gathered out of.
Yet it is a comfort to find a remnant in most places, who, I trust,
will not be driven from the good old way,
and who are "`grieved for the afflictions of Joseph,`" spiritually.
My spirit is in deep sympathy with these,
not doubting that the Lord`'s faithful children will be kept in the "`hollow of his
hand,`" and enabled to support the various testimonies of Truth to their own peace,
and to the praise of his great name.

I keep the run of all our meetings at home, and my spirit often visits you in them.
I believe that all the Divine promises are "`yes, and amen, forever;`" and, therefore,
our holy Head will be in the midst of those who are gathered in his name,
though but few in number.
It is snowing very fast, and the weather having been winter-like for some days,
I expect we will leave our carriage here and take a sleigh.

[.signed-section-closing]
As ever, your affectionate husband,

[.signed-section-signature]
Joseph Edgerton.

--

First-day, 4th of Twelfth Month.--Attended a meeting at Half-Moon, to satisfaction;
and rode that evening to Shaticoke; a little meeting, held in David Devol`'s house.

My gracious Master gave strength to open to the
people the "`unsearchable riches of Christ.`"
The power of the Lord was present to heal the diseases of all
who in faith were concerned to submit themselves thereto;
and the meeting would have ended well had it not been for some
"`dead flies`" cast in by a member of the meeting,
which caused the ointment of the apothecary to
send forth a savor, not so pleasant as before.

Fourth-day, 7th, we proceeded to East Hoosack, in the State of Massachusetts,
and attended meeting there; found the state of religion lamentably low.
O, how the poor traveller has to mourn when his divine Master is in suffering!
I was favored, however, to perform the allotted portion of service.
Proceeded that evening towards Granville, where we arrived on Fifth-day evening,
and had a meeting there on Sixth-day, in which Truth reigned over all.
May the praise be ascribed unto Him from whom all strength comes,
and who is worthy of all praise forever.

First-day, 11th, attended a meeting at Lincoln; a time of close labor,
but felt sweet peace.
Dined at Benjamin Tabar`'s, and had a meeting at the Creek in the evening;
which was an open time in close labor to some lukewarm professors.
The way of life was spoken of, I trust,
in the "`demonstration of the spirit and of power;`" and the day closed peacefully.

12th.--At Starksborough; a time of suffering; very little relief was obtained.

13th.--At Monkton and Ferrisburgh, to satisfaction; particularly the latter.

14th.--Rode through a very severe snow storm to Moutpelier, and had a meeting there;
and the next morning set out for Farnham, Lower Canada.
We reached Barton in the evening, and lodged at the house of James May;
a member of our Society, who, together with his family,
sit down in their house on First-days; and sometimes others come and sit with them.
We had a meeting in the town to satisfaction, and set out again in the afternoon,
expecting to reach Farnham Monthly Meeting; but a heavy snow storm coming on,
rendered it very difficult travelling,
the snow being so much drifted that it was almost impossible to get through;
and very cold.
It caused me to reflect upon the many sufferings and hardships which
our dear forefathers endured in the early settlement of America.
The accommodations, however, are very different now;
though far inferior in this country to that of our own.
We travelled very hard all day and only made about fifteen miles;
were favored to reach a poor inn in the evening, for which I felt thankful.

On Third-day, the 20th, we proceeded on through the deep snow;
it being from four to five feet deep in many of the lanes.
Travelled about twenty miles and reached the settlement of Friends in Lower Canada,
where we were very cordially received by them.

21st.--Had a meeting at Farnham, which was largely attended by Friends and others,
and it was a season to be remembered.
Truth reigned over all,
under the authority of which strength was given
to declare the "`unsearchable riches of Christ.`"
The meeting closed with humble supplication and
thanksgiving unto God for his many mercies.
Left in sweet peace and great tenderness towards
Friends in this remote part of the heritage.
Set out in the afternoon for Peru, and arrived on Sixth-day evening, the 23rd,
and stopped at William Kee`'s.

First-day, 25th.--At Peru in the forenoon (in Friends`' meetinghouse),
wherein Divine strength was given to declare the way of life and salvation.
In the evening, had a meeting in the village of Peru,
and humbly hope the cause was not injured thereby.

Third-day morning, 27th.--Set out for Queensbury, and arrived on Fourth day evening,
and attended Monthly Meeting there on Fifth-day.
The reward of peace was vouchsafed for honest labor to some lukewarm professors.

Had an evening meeting on the banks of North River,
where a few families of Friends reside; to which many not of our Society came.
The "`unsearchable riches of Christ,`" I trust, was declared,
in some degree of the "`demonstration of the Spirit.`"

30th--At Greenfield, which was a good meeting; and at Galloway in the evening;
a time of instruction to many.
Lodged at Caleb Parmer`'s, expecting to go directly on to Le Ray Quarterly Meeting;
but owing to a heavy fall of snow during the night, we were detained several days,
which was a renewed call on my little stock of patience,
having felt great anxiety on account of my dear family for some weeks,
and expecting to get letters from them, either at Le Ray or Lowville.

[.offset]
Here he wrote to his wife, the following being an extract:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Twelfth Month 31st, 1842.

[.salutation]
My dearly beloved Wife:

Being detained from pursuing our journey,
in consequence of a heavy snowstorm, I think it will be best for me to write,
though I have deferred it for sometime, hoping soon to reach Lowville,
where I might receive a letter from you;
as I have had no account since leaving John Wood`'s, nearly eight weeks ago.
It has been a great trial of my faith and patience, and the more so,
because some of our dear children were complaining at that time.

We have been favored to get along without any accident thus far,
for which I feel thankful to the great Preserver of men.
We have been very industriously engaged in the work before us,
having visited the meetings of Saratoga and Ferrisburgh since I last wrote you;
the meetings of the latter are very widely scattered, which occasioned much travelling;
but we were favored to get along safely,
and we felt glad in having visited this remote settlement; indeed,
I was richly paid for all the fatigue and exercise I had to undergo.
May the great name of our God be worshipped and adored forever.
My soul, though unworthy of the least of his mercies, can say,
"`Hitherto He has helped us;`" though the trials which have been meted out, perhaps,
have never been more severe than during the present journey.
It does me good to remember that I have your prayers,
as well as the prayers of many other dear friends and connections.

Oh, I sometimes look over the meetings in our quarter,
and although I know that weakness too much prevails there,
yet if I have been favored to be dipped into a
sense of the state of Society in this land,
it is far below it.
A spirit which is weary of the plainness and
simplicity of the Truth as it is in Christ Jesus,
is leading into the world, its riches, its fashions and customs,
together with its flatteries, which eats up every green thing where it goes, and does,
indeed, seem like spreading devastation in this land; and yet, there is a remnant,
as the "`two or three berries in the top of the uppermost
bough,`" up and down in the different meetings,
unto whom we have felt nearly united in the covenant of life, and who are, I trust,
as "`the dew in the midst of many people.`"
But, oh, how sad we many times feel, in passing along from place to place;
so little of that living, upright zeal,
which so remarkably characterized our dear forefathers,
and which is to be found (blessed be the name of Israel`'s
Shepherd,) in many parts of his heritage.
In tender love, I remain,

[.signed-section-closing]
Your affectionate husband,

[.signed-section-signature]
Joseph Edgerton.

--

First-day, First Month 1st, 1843.--Had a meeting at Providence,
and found relief in some close service.
My mind has often been clothed with mourning on account of the low state of the Church,
which induces the mournful language: "`Oh, that my head were waters,
and my eyes a fountain of tears,
that I might weep day and night for the slain of the daughter of my people!`"

Set out on the morning of the 2nd towards Lowville, a distance of one hundred miles;
and reached the neighborhood of Western the next evening.
Had meetings at Western, and Lee, on the 5th to good satisfaction.
Lodged at the house of John Powel in company with Lachens Hill
of whom it could be said as of Nathaniel of old,
"`Behold an Israelite indeed, in whom there is no guile.`"
Had a refreshing opportunity in the morning which I believe, will long be remembered.
May the Lord`'s great name be praised, who is worthy forever,
and the poor creature be kept where it ought to be--in the very dust.

6th.--We reached Lowville, where I received a letter from my dear wife,
giving the sorrowful intelligence of the decease of our beloved daughter, Lydia;
which was indeed a proving dispensation, and deeply affected me: though, I trust,
I was preserved from giving way too much; yet it was hard to suppress the falling tear.
And I am inclined to think it may be admissible to give vent
to affectionate feelings in this way to a limited extent;
for "`Jesus wept`" at the grave of Lazarus.
And, to the praise of the good Shepherd be it spoken,
His sustaining arm bore up my head above the waves, and enabled me,
in humble acquiescence with His divine will to say with Job; "`The Lord gave,
and the Lord has taken away, blessed be the name of the Lord.`"
We attended meetings at Le Ray and Indian River, to satisfaction.

[.offset]
Relative to the close trial above alluded to he thus writes to his family:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Lowville, First Month 7th, 1843.

[.salutation]
My dear Wife and Children:

We are now at Thomas Townsend`'s; arrived here last evening,
where I soon became acquainted with the mournful tidings of the 12th of last month,
the removal of our dear Lydia from time to eternity.
The keenness of the stroke you can better understand than I can describe; and yet,
I trust, that eternal arm which has been my help in many times of trial, has been,
and will continue to be near, and hold up my head above the waves.

We left Le Ray yesterday morning, and while riding to this place, it ran through my mind;
"`One of our daughters is gone.`"
My mind was directly turned to our parting opportunity; in which,
as well as at other times, I committed you all,
as also my own soul into the hands of that God who does
all things after the counsels of his own will;
which had a tendency to quiet my mind, still hoping it might not be so,
until I got hold of the letter.

And now my dear,
notwithstanding this very severe dispensation which has been meted out to us,
I am fully satisfied that this separation from you has
been in the ordering of the Head of the church:
and as respects the dear sufferer, who has passed away,
I have no doubt all was done that could have been done had I been present with you.
I therefore desire your encouragement and strength, as you,
with myself have many times known the everlasting arms to be
underneath to bear up and carry us through that which would
have appeared impossible to human understanding.
Oh, He is worthy of all praise forever, and ever, as well as our entire obedience!

I feel for our dear children, knowing the severe stroke is very keenly felt by them.
Oh, I want you to love Him who has dealt thus with us in his wisdom! -though it
is in causing us to drink the waters of "`Marah`" and affliction;
for He is very gracious unto His children in every part of his heritage,
and will keep them, and as they love Him more and more,
they will become stronger and stronger, living to his praise,
who is worthy of all that can be ascribed unto Him.

And now, my dear, I must soon close this little paper messenger;
and as respects this way of communication,
stop the current of affectionate regard which runs as a
lively stream through my heart unto you,
and our dear children; and remain your affectionate husband and companion in tribulation,
and, I trust, in the faith and patience of the Gospel,

[.signed-section-signature]
Joseph Edgerton.

--

Sixth-day morning, the 18th, set out for Upper-Canada,
and crossed over the great river St. Lawrence to the house of Isaac Booth.
I felt thankful to the great Preserver of men for his many favors and deliverances.
Had a meeting in a school-house in the vicinity on Seventh-day;
and then rode to Harvey Derbyshire`'s.

First-day, 15th, at Leeds meeting,
which was an open good time in declaring the "`unsearchable riches of Christ.`"

16th.--Set out for Leonark, a distance of near sixty miles,
a small number of members being there,
but found to my sorrow that they were far short of being thorough Friends.
Had a meeting with them to satisfaction,
in which I felt it my duty to lay the matter close home to them.
Returned to Leeds meeting on Fifth-day, wherein I felt it my duty to deal plainly.
Had a meeting south of Leeds, and one northeast;
the latter was a very open good meeting among a company of serious,
and some seeking people.

Sixth-day morning set out for Kingston;
and after traveling ten or twelve miles on the mud in the sleigh,
arrived late in the evening.

First-day, 22nd. At Kingston meeting:
close service went forth to some lukewarm professors, and felt peace.
From there went to Camden, a small meeting held on First-days.
Had a meeting on Fourth-day morning; and one in the evening in a school-house,
about fifteen miles towards Adolphustown.
The former, particularly, was an open time.
From there, to Adolphustown meeting, to satisfaction.

Crossed the Bay of Quinte on the ice, and were favored to get safely over,
for which I felt thankful.
May I never forget all, nor any of His benefits.
Went to William Roerk`'s, where I received several letters,
one of which was from my dear wife and children, which was a great satisfaction to me.
May the Lord be pleased to keep and sustain them by his eternal power,
and enable them to bear the sore bereavement that has been permitted to attend,
with resignation and fortitude.

Sixth-day, at the Boarding School; had a religious opportunity with the pupils;
felt very sorrowful on account of the situation of the school,
it having been opened for those who are not members of our religious society,
and thereby is a very crippled concern.

First-day, 29th, at West Lake in the forenoon,
and in the evening had a meeting in the town of Pictou.
The former was a solid good meeting, and the power of Truth was felt to prevail.
The latter was very large; supposed to be more than a thousand present.
The people appeared attentive, and I was led to open to them the doctrines of the gospel,
I trust, in the "`demonstration of the spirit and of power.`"

30th.--At Helier, to satisfaction; and on Third-day, the 31st,
the Select Half Year`'s meeting was held, which was a time of close searching labor;
and towards the close, Truth reigned over all.
May praise be ascribed unto Him, who is "`Head over all things to his church.`"

[.offset]
From this place he again wrote to his family, the following being an extract thereof:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
West Lake, Upper Canada, First Month 31st, 1843.

[.salutation]
My dear Wife and Children:

I again salute you in the tenderest feelings
that can flow from the heart of an affectionate husband and father.
Very deeply do I feel for,
and sympathize with you in the trials which have been meted
out by Him "`who lays the beams of his chambers in the waters;
who makes the clouds his chariots;
and who walks upon the wings of the wind,`" unseen by mortal eye;
and no doubt in the counsels of that wisdom which is perfect, it becomes us to say,
"`It is the Lord, let Him do what seems Him good.`"
I hope I have not given way improperly to my tender affectionate feelings towards you;
for although I often give vent to the emotions of my heart, particularly when alone,
I do not repine, nor doubt that I am in my proper place.
My gracious Master has been with me, and supported me beyond my expectations:
may his great name be praised and magnified forever.

It has been a strength to me in the many baptisms that
have attended in this arduous engagement,
to believe that I have the prayers of many,
very many dear friends both at home and in other places, that I may be preserved,
and strengthened to fill up the measure of allotted service,
to the honor of the great Head of the church, and to the peace of my own mind.
And to the praise of Israel`'s Shepherd be it spoken,
He has not failed to be near in "`heights and in
depths,`" and has equipped for every service,
however close and trying, or humiliating to the creature.
Indeed, I never saw more clearly the wonder working-power of eternal Jehovah,
in leading his servants again and again into deep baptisms, than of recent time.

May stones of memorial be taken from the bottom of "`Jordan and pitched in
Gilgal,`" to bear testimony to the goodness of the Lord to his people.
I desire to be preserved in patience until the time comes when a
release may be sounded from further service in a foreign land.
It is scarcely worthwhile to say, then gladly shall I return to you, if so permitted,
which I trust, will be the case in the Lord`'s time.
May the Lord bless you, and watch over you by day and by night,
together with my own soul,
and preserve us in his "`secret pavilion,`" where no "`evil can befall,
nor any plague come nigh.`"

[.signed-section-closing]
Your affectionate husband,

[.signed-section-signature]
Joseph Edgerton.

--

Fourth-day, Second Month, 1st.--The meeting for discipline commenced.
Heavenly help was near, and strengthened for the service required.
Fifth-day, a public meeting was held, which was largely attended by Friends and others;
and I trust, to many, it was an instructive opportunity.
In the afternoon the meeting for discipline closed.
My mind felt sad because of the low, mixed state of the church.
Left the meeting with the reward of peace,
in delivering what appeared to be the counsel of my divine Master.

Sixth-day, had a meeting in the evening at the house of P. L., in the town of Sidney;
and were at Cold Creek meeting on Seventh-day;
in which the glad tidings of the gospel were
proclaimed in the demonstration of the Spirit.
May the name of our God be exalted over all.

First-day, 5th, at Haldemand--a poor little meeting:
obtained relief in some close labor to the lukewarm.

Second-day, rode fifty miles to Pickering; a very extremely cold day.

Third-day, at Pickering meeting, which was a favored time.
Set out on Fourth-day for Uxbridge, and travelled about eleven miles,
where we found the snow so drifted that we could not go forward: had to return,
and proceeded to Yonge Street, and were at a meeting there,
where the life of religion appeared to be at a low ebb.

In the evening, at White Church; and the next day at Tecumseh, to satisfaction;
on our way to Pelham, we attended a meeting near Stony Creek on First-day evening,
appointed by our friend Mead Atwater, for the colored people.
Attended the Select meeting at Pelham on Third-day;
the meeting for discipline on Fourth-day; and the public meeting on Fifth-day;
through all of which the Lord helped us to discharge the portion of service required.
May his great name be magnified over all.

Set out on Sixth-day morning, the 17th,
and crossed the Niagara river just below the Falls.
We stopped awhile to view the works of the great Creator, which all praise Him.
And truly,
on landing on the American shore I felt thankful to Him
for his many deliverances and preservations,
both by sea and land.
Oh, may my soul forever praise Him, who is worthy to be worshipped,
and adored by all his workmanship! -and particularly,
to be had in remembrance in the most awful humility and gratitude,
by all those that are "`about Him.`"

First-day, 19th, attended meeting at Lockport.
The spring of gospel ministry was pretty freely opened in a
tender manner to some who had left their first-love;
commencing with the Scripture language; "`I remember you; the kindness of your youth,
the love of your espousals; when you went after me in the wilderness,
in a land that was not sown;`" showing the need
of remembering the days of our tenderness,
wherein a willingness was experienced to follow the Lamb in the way of his holy leading,
even in a wilderness state, or in a land that was not sown;
and the necessity of looking unto, and following that which first awakened us.
Counsel also flowed in a tender manner to some not in profession with us,
diligently to take heed unto the Divine gift in the heart,
whereby any may come to experience the goodness and mercy of the Lord,
and be prepared for another and a better world.

20th.--At Somerset and Hartland.
The life seemed to be low.
Felt a good degree of peace for honest labor,
being very close,--particularly in the former.
My spirit mourned on account of the low state of the Church.
"`Oh, that my head were waters, and my eyes a fountain of tears,
that I might weep day and night for the slain of the daughter of my people.`"

21st.--At Shelby and Elba, to satisfaction.
Rode to Buffalo the next day,
and had a meeting in the evening with the few Friends there,
and some friendly people who came in.
I was led to show them the necessity of an upright walk before the Lord,
whereby they might adorn our high and holy profession.

Rode on Fifth-day morning, the 23rd, about twenty-five miles, to Collins Monthly Meeting,
in which the life was very low.
Obtained peace by being faithful in the allotted portion of service.
In the Meeting for Discipline,
the very exciting subject of abolition of slavery was taken up,
and it appeared evident to me that some of them were too much warmed with a forward zeal,
even in a good cause.
I felt it my duty to give them a hint of it, by remarking to them,
that I had remembered the circumstance of Peter`'s
wife`'s mother being taken with a great fever;
and when our blessed Lord laid his cooling hand upon her, immediately the fever left her,
and she arose and ministered unto them.
Oh, how sorrowful it is that Friends allow themselves to be
carried away from the ancient ground,
which our religious Society has acted upon from generation to generation,
even a waiting for the direction of our holy Head,
and then to move as He may open the way.

Sixth-day, at Clear Creek and Hamburg.
The former was largely attended by Friends, and others, and was a very open time.

First-day, 26th, at Orangeville; a poor little meeting.

28th.--At Wheatland; which was an open, good meeting.
From there to Farmington, and attended that meeting the next day; but was entirely closed.
It seemed to me that an example of silence was my service among them.
My mind was clothed with mourning;
many Friends having become excited on the subject of abolition, temperance, etc.,
and thus running in the activity of the creature, into the mixture with other people,
so that genuine Quakerism seems likely to be eaten up.
I feel these to be very important subjects, which we, as a religious Society,
have always held very dear; but it is highly important that in promoting them,
we should move on in a collective capacity, as we have learned of our Divine Master.
It is lamentably the case, that where there has been a mixing with other people,
the language respecting Ephraim of old is applicable:
"`Ephraim has mixed himself among the people; strangers have devoured his strength,
and he knows it not.`"

Fifth-day, Third Month 2nd.--Attended a meeting in the evening at M+++_______+++,
where Divine life was at a low ebb; and having a cold, we rested the next day,
and went from there to Scipio.

4th.--Were at North-street and Scipio; both favored meetings, particularly the latter,
which was a refreshing season.

[.offset]
The following is an extract of a letter to Ann Branson, written at this time:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Third Month 6th, 1843.

[.salutation]
My dear Friend, Ann Branson:

Having for sometime felt my mind drawn towards you in,
I trust,
a portion of that gospel fellowship which unites the
members of that body of which Christ Jesus is the Head,
I salute you, and may say, through the mercy of the good Shepherd,
we have been favored to get forward as well as we have had reason to expect.
Many, indeed, are the baptisms which have been our portion, of different kinds;
some of which, I have no doubt,
have been administered for the purpose of keeping the
poor vessel in its proper place and condition.
May I learn more and more in the school of Christ,
being found in that situation wherein the heavenly anthem: "`Not my will, but yours,
Oh Lord, be done,`" may be adopted.
To be baptized for the dead seems to be a very
prominent part of the suffering meted out to us.

Oh, my life has been brought very low with the suffering
seed in our poor "`stripped and peeled`" Society;
and, perhaps, never more than within a few weeks past.
There is at work in various places an over-active spirit, in Abolitionism, Temperanceism.
and Gurneyism, which,
like the "`locust,`" the "`cankerworm`" and "`caterpillar,`"
are ready to eat up every green thing.
I trust there are many sound Friends hereaway; and yet, if I do justice to my feelings,
I must say, that the life of religion is very low in many places.
This over-active,
restless spirit that is unwilling to come under the
circumscribing limitations of the cross of Christ,
and which strikes at the very life of Quakerism, is much to be dreaded in these days.
Nevertheless, in the midst of many discouraging things, I trust it may be said,
there is a remnant in most places who are of the salt
of the earth,--who are desiring to be found faithful,
to whom we have felt nearly united in the covenant of life.
May they hold on their way, and become stronger and stronger.
I remain, in the fellowship of the Gospel,

[.signed-section-closing]
Your friend,

[.signed-section-signature]
Joseph Edgerton.

--

5th.--Had a very small meeting at Skeneateles; the life of religion lamentably low.
From there to De Ruyter,
where Truth`'s testimony was held forth in some degree of gospel authority.

[.offset]
Here he again writes to his wife, of which the following is an extract:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
De Ruyter, Third Month 8th, 1843.

[.salutation]
My dearly beloved Wife:

I again salute you, together with our dear children,
and may say,
through Divine mercy we have been favored to get along as well as could be expected.
I have no doubt I have your prayers, as well as the prayers of many other dear friends,
both at home and abroad,
which has been a strength to me under the many trials which I
have had to pass through in going from place to place,
many times, as it were, with my hands upon my loins, and weeping, too,
for the "`slain of the daughter of my people.`"
Not slain in the Lord`'s battles, but on the enemy`'s ground.
Yet, it has often been a comfort to believe that the "`foundation of God stands sure,
having this seal: the Lord knows them that are his;`" and that his own are known by Him,
and sustained by Him,
however they may have to pass through evil
report for their faithfulness to our holy Head.
Oh, how great is his goodness towards them that fear Him!
He will hide them secretly in his presence from the pride of man,
and will keep them in his "`pavilion from the strife of tongues.`"
To the praise and the glory of our eternal Helper be it spoken,
He has not failed to be near, and by his arm underneath, to bear up.
May my soul forever commemorate his goodness,
and the remainder of my life serve Him with a willing mind.

We are still in the old sleigh, and think likely we shall get it back to Hudson,
as there is plenty of snow yet.
We have travelled about twenty-two hundred miles in it.
I have often thought of you during this long, cold winter;
how you are getting along in different respects;
but have to leave you in the hands of our great Creator.
I remain, as ever,

[.signed-section-closing]
Your loving husband,

[.signed-section-signature]
Joseph Edgerton.

--

We next went into the limits of Butternuts Quarter, taking Smyrna, Madison,
Brookfield and Burlington, to satisfaction.

First-day, 12th, at Butternuts, which was a large meeting;
many not of our Society being there.
Next, at Otego and Lawrens; both to the relief of my own mind; but not feeling easy,
we returned to Butternuts, and attended their meeting on Fourth-day.
Found relief by faithfulness in delivering what
seemed to be the allotted portion of service.
My spirit has often been clothed with mourning,
on account of a disposition that seems to prevail,
which would compromise the peculiar testimonies
for which our forefathers so deeply suffered.

On Fifth-day, 16th, rode to Blenheim, and were detained there until First-day,
by deep snow-drifts.
Sat down, at 11 o`'clock, with the few Friends there, and some of the neighbors,
which was a solid, edifying season.
Set out First-day afternoon towards the city of Hudson,
and arrived at the house of our kind friends, Samuel and Ann Marriott,
where we started from in the sleigh, the last of Eleventh Month.
We were rejoiced to get there.
Attended Hudson Monthly Meeting;
counsel flowed freely to the exercised Christian travellers;
while close labor was meted out to some careless, unconcerned professors.
Left in peace.

Fourth-day, 22nd, attended Coeymuns Monthly Meeting; an open time in testimony,
beginning with the words: "`He that has an ear to hear,
let him hear what the Spirit says unto the
churches,`" demanding deep and awful attention,
that we might come up faithfully as individual members of the Church; showing,
that if ever the Church does arise and shake herself from the dust of the earth,
and put on her beautiful garments, individual faithfulness and purity must be witnessed.
Returned to Samuel Marriott`'s through a snowstorm.

[.offset]
Here he again writes to his family, as follows:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Near Hudson, State of New York, Third Month 24th, 1843.

[.salutation]
Dearly beloved Wife and Children:

In dear and tender love do I again salute you,
being prevented from travelling by a heavy snowstorm,
which is a fresh trial of patience.
The snow is perhaps three feet deep where it is not drifted,
and from ten to fifteen where it is blown into lanes and roads.
It has been exceeding difficult travelling; indeed,
it has been impossible in many places, until the roads were opened with shovels.
I feel very tenderly for you, and have been desirous to improve the time.
I much desire to be preserved in the patience until the Lord`'s time,
when a release may be granted, and liberty given to return to you, which, I believe,
will be before long.

Many baptisms have been permitted to attend during the present arduous engagement; yet,
I may say, I have never felt a greater evidence in my feeble stepping along,
that I have been, and am at this time, in my proper place;
although sensible that I am an unprofitable servant, having done,
in this very humiliating service, that only which it was my duty to do.
And as respects the Society for which we so deeply feel,
you know it is not a time of much sending of presents, one to another,
under a sense of the abounding of that life which so eminently marked earlier days;
indeed, the mind is often clothed with mourning,
because of the "`slain of the daughter of my people,`"--slain, not in the Lord`'s battles,
but on the enemy`'s ground--a delusively deceptive, compromising spirit,
which raises itself above the cross of Christ,
and which strikes at the life of Quakerism.
This is so prevalent, that the poor pilgrim is ready to say with one formerly: "`Oh,
that my head were waters, and my eyes a fountain of tears,
that I might weep day and night for the slain of the daughter of my people.`"
There is, however, (blessed be the name of Israel`'s God), a remnant,
unto whom I feel nearly united in the covenant of life,
and with whom we have been refreshed, even as of a brook by the way.

I have received no letter from you since being at Pictou, Upper Canada,
the last of First Month.
Give my kind and affectionate remembrance to all
our relatives and friends in your freedom.
I often remember you in all our meetings at home,
believing that some of you feel deeply for the "`ark`" of the "`testimony,`"
and many times feel the solemn responsibility which rests upon you.
May the "`eternal God be your refuge;
and underneath the everlasting arms,`" to support and
strengthen you in "`every good word and work.`"
+++E+++. and M. B. are of the number alluded to, and are sharers of my lively interest.
My love to them in the fellowship of the gospel.
I must draw to a close, and remain, as ever, in that which time, nor distance,
can in any degree diminish,
your loving husband and companion in the tribulations of the gospel,

[.signed-section-signature]
Joseph Edgerton.

--

We were detained by the deep snow until First-day, the 26th,
when we rode to Little Nine Partners, to a meeting, at 2 o`'clock; a poor little meeting.
An example of silence appeared to be my place.
After attending a meeting on Fourth-day, to satisfaction,
we proceeded on our way towards New York; and on arriving, attended meetings in the city,
on First-day, the 2nd of Fourth Month,
under awful feelings of the prevalence of a spirit that is lurking in secret places.

[.offset]
Thus closes the account of this visit,
except what is contained in the following extract of a letter,
written after arriving at the city of Philadelphia:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Fourth Month 8th, 1843.

[.salutation]
My dearly beloved Wife:

Being now at the house of Thomas Kite,
I take my pen in hand again to address you.
Through Divine mercy we have been favored to get along thus far,
to the relief and peace of our minds.
After arriving at New York, we attended both meetings in the city on First-day,
the 2nd. In the forenoon my Divine Master called for dedication;
and by his all-sustaining hand of power,
enabled me to declare "`the unsearchable riches
of Christ`" to a large meeting of Friends,
and others, to my own satisfaction;
though mourning and lamentation was the clothing as respects
many of the members of our highly professing religious Society;
in which sense it might be said, that "`bonds and afflictions abide.`"

In the afternoon, humble petitions were put up for our poor, stripped and peeled Society,
that like the vine that was brought out of Egypt, spiritually,
had been watered by the heavenly rain and celestial dew, from season to season,
yet the "`boar of the wood is wasting it,
and the wild beast of the field is devouring it.`"
Every opposing spirit was kept under, and the Lord magnified over all.
May my soul forever bless and praise his holy name while I have a being.
Dear John Wood said in the evening: "`We can say, in the language of David,
'`This is a day which the Lord has made; we will be glad,
and rejoice in it.`'`" I feel more and more my weakness and unworthiness,
and that I am an unprofitable servant indeed;
it is through holy help alone that I am enabled to speak well of his name; for truly,
what I am, I am by his grace.
May this covering of humility and nothingness be put on and worn to the end,
is the desire of my heart.

Attended their Meeting for Sufferings on Second-day, which was a very trying time.
An epistle having been received from the Meeting for Sufferings of Indiana,
setting forth the cause of the recent separation
from our religious Society in that country;^
footnote:[On the subject of abolition of slavery.]
which was read, and after a long discussion was not noticed on the minutes of the meeting.
A very low state of things certainly does exist,
if I have been dipped into a sense of the condition of
the church in that part of the heritage.
I felt on leaving the city, a peaceful release from further service there;
and may inform you, that, from my present feeling,
I think we may be at liberty to set out for home
soon after the close of Yearly Meeting here.
On arriving in this city, I went directly to the house of William and Elizabeth Evans;
as he had been at our house,
and was no doubt a comforter of those mourners for whom my tenderest sympathies flow.

Night before last we were at Christopher Healy`'s,
after attending his Monthly Meeting at the Falls;
wherein he opened a prospect of religious service in New Jersey,
principally among those not of our society.

[.signed-section-closing]
I remain as ever, your loving husband,

[.signed-section-signature]
Joseph Edgerton.

--
