== Chapter VII.

[.chapter-synopsis]
* Account of a visit to Salem and Springfield Quarterly Meetings, and their branches.

Having felt my mind drawn in the love of the gospel to visit
the meetings constituting Salem and Springfield Quarters;
and having obtained the necessary certificate for that purpose,
I set out on the 20th of First Month, 1844; my dear friend, Edmund Baily,
bearing me company.

First-day, 21st.--Attended the meeting at the Boarding School at Mount Pleasant,
to satisfaction.
The language of encouragement flowed freely to the dear children,
with desires for their growth and settlement in the Truth;
that they might on their return to their own homes, and neighborhoods,
give evidence of the preparing hand of the great Potter.
Rode to Salineville the next day, and on Third-day, had a meeting there, to satisfaction.

On Fourth-day morning rode to Salem and attended the Monthly Meeting there,
in which I was led to set forth the connection of the different members of the body;
rising with the language, "`If one member suffer, all the members suffer with it;
and if one member be honored, all the members rejoice with it.`"
It was a solid good meeting, and much to the relief and peace of my mind.

Fifth-day, attended Monthly Meeting at New Garden, to satisfaction.

Sixth-day, attended Sandy Spring Monthly Meeting, held at Augusta; a time of close labor.
After meeting rode to Springfield, and attended Monthly Meeting there the next day;
which was crowned by the life-giving presence of Him who is the Head of his own church.
I was led into deep travail for the members of the church of Christ;
standing up with the language, "`The spirit and the bride say come;
and let him that hears say come;
and let him that is athirst come and partake of the water of life freely.`"
Left peacefully.

First-day, 28th.--At Goshen, which was a highly favored meeting;
strength being given to labor for the restoration of
the captive sons and daughters of Zion:
reviving the language, "`By the rivers of Babylon, there we sat down; yes,
we wept when we remembered Zion;
we hung our harps upon the willows in the midst thereof;
for there they that carried us away captive required of us a song;
and they that wasted us required of us mirth, saying: sing us one of the songs of Zion.
How shall we sing the Lord`'s song in a strange land?`"
The baptizing power of Truth prevailed over us.
May the Lord be magnified over all.

Second-day, attended the Select Preparative Meeting at Marlborough--a very low time.
Attended Monthly Meeting there on Third-day, which was a time to be remembered.
My gracious Master enabling in a searching manner, to plead with the carnal professors;
reviving the language, "`A voice is heard in Ramah, lamentation and bitter weeping;
Rachel weeping for her children, refusing to be comforted because they are not.`"
A lively emblem of the condition of the church,
who is weeping because of many of her children who are in a carnally minded state,
and therefore, as to the divine life "`are not;`" for, as says the Apostle,
"`To be carnally minded is death; but, to be spiritually minded, is life and peace.`"
Through faithfulness in extensive and searching labor,
the reward of peace was mercifully vouchsafed.

Fourth-day, rode to Kendal.
Dined at the house of Robert and Hannah Ghoekin, who are colored people;
the latter a member of our Society; for whom I felt deeply,
she having to go eight miles to meeting.
Lodged at Richard Williams`', and had a meeting there the next day, which was a low time;
rode back to Marlborough the same evening, and had a meeting at Lexington on Sixth-day.
The house was crowded, a considerable number having to stand the whole time.
The baptizing power of Truth was felt eminently to spread over us:
and strength was furnished to declare the "`unsearchable riches of Christ`" to them,
many of whom were not members of our Society.
May the praise be ascribed unto Him who "`gives power to the faint,
and to them that have no might he increases strength.`"

First-day, 4th of Second Month.--At meeting at Salem; which was a time of divine favor;
feeling it my duty to stand up with the words, "`Behold the fire and the wood,
but where is the lamb for a burnt-offering`"--the language of
the son to the venerable patriarch--his father;
who replied; "`God will provide himself a lamb.`"
The language of encouragement flowed freely to some, who,
in the faith of Abraham had made covenant with the Lord by some sacrifice;
showing that their safety depended upon their faithfully following
their divine Master in the future leadings of his Holy Spirit;
though the sacrifices required might be such as nature would shrink from,
as in the case of Abraham: believing,
that in their experience they would know that God would provide himself an offering.
A solemn appeal was made to some who had been visited by the "`day-spring
from on high;`" but for lack of faithfully following the heavenly Leader,
they had suffered loss;
the "`little foxes`" had come in and injured the "`vine,`" so that it became unfruitful.
It was a solid good meeting.

At Middleton on Second-day; which was through adorable mercy, a refreshing season;
and the doctrines of the gospel were opened,
and flowed freely to a crowded meeting of Friends and others.

In the afternoon, at Elk-Run.
I sat in great poverty; having invited the people to come together,
most of whom were not members, I was brought very low:
but He who is the "`resurrection and the life,`" in his own time arose and granted
ability to declare the "`unsearchable riches of Christ,`" to the people.

Third-day at Carmel to satisfaction.

Fourth-day, attended the Select Preparative at Middleton, and on Fifth-day,
the Monthly Meeting, in which our blessed and adorable Head was near,
to the refreshing of the hearts of many.
May his holy name be magnified over all.
In the meeting for discipline, I was led to sound an alarm among them,
on account of a spirit of strong delusion which is lurking around,
and calculated to lead the unsettled mind from the Truth,
and create a disrelish for the sublime and important subject of practical piety,
even to the reproach and scandal of the Christian name:
called by some French Philosophy or Mesmerism; in connection with Phrenology;
on account of which I have mourned and been in heaviness.
May the Lord open the eyes of the people to see the delusions of the enemy,
that a standard may be lifted up against him.

Sixth-day, at the Select Quarter at Salem, to satisfaction;
and attended the Quarterly Meeting on Seventh-day, which was a season of renewed favor;
strength being given to divide the word to a very crowded meeting,
in a close and searching manner, to the indifferent and superficial professors;
and to some who had allowed the "`foxes`"--the "`little foxes,`"--to
injure the "`vines,`" whereby they had become unfruitful.
The language of encouragement flowed freely to the poor in spirit;
and the meeting was crowned with the spirit of
prayer and supplication to the throne of grace.
May praise and thanksgiving be ascribed unto Him whose
lovingkindness and tender compassion has been from of old,
from everlasting.

First-day, the 11th.--At Springfield;
in which I believed it my duty to set an example of silence.
In the afternoon had a meeting for the youth, which was largely attended,
and was a very solid and orderly meeting;
and through the tender compassion of the Shepherd of the sheep, it was a good meeting.
Truth reigned over all.
The spring of the ministry ran freely to the different classes:
may the opportunity be blessed to them.

Second day, attended the Select Quarter--a solid edifying season.

Third-day, at the meeting for discipline.
The presence of our ever adorable Head was mercifully
witnessed bringing into a holy solemnity.
I felt the power of Truth gradually to arise in my heart,
which centered me deeper and deeper in awful abasement of soul,
until it appeared to be my duty to stand up with the words,
"`Deep calls unto deep at the noise of your waterspouts;
all your waves and your billows are gone over me.`"
The members of the mystical body of Christ were called
upon to dwell deep in the power of an endless life;
the deep things of God call for deep indwelling--the
state recommended by that faithful servant and elder,
who was the first instrument in gathering us together in the beginning,^
footnote:[George Fox]
where he says, "`Let all your meetings be held in the power of God.`"

As the members of the body are gathered with one accord into one place,
waiting in their measures upon Christ Jesus, the "`Minister of the sanctuary,
and of the true tabernacle, which the Lord has pitched,
and not man;`" the state spoken of by St. John, the divine, comes to be witnessed,
where he saw a "`woman clothed with the sun and the moon under her feet;
and upon her head a crown of twelve stars.`"
Clothed with the Son of righteousness,
in the light of which shining brightness she is enabled
to go forth in her transcendent beauty and glory,
and the moon under her feet--everything changeable kept under her feet;
and upon her head a crown of twelve stars--representatives of
the twelve tribes of the Israel of God,
scattered abroad.
The word of exhortation flowed freely to the careless, superficial members,
to gather to the divine gift in themselves that they might be "`raised into newness
of life;`" being united with those who are travailing for the "`welfare of Zion,
and the enlargement of her borders,`" that the language might be proclaimed: "`Arise,
shine, for your light is come, and the glory of the Lord has risen upon you.`"
"`Her light is come`"--"`clothed with the sun,`" and thus go forth under the
authority of Him whose right it is to be "`Head over all things to his own church.`"

[.offset]
Thus the account of this visit closes.
