== Chapter VIII.

[.chapter-synopsis]
* Account of a Visit within the Limits of Philadelphia Yearly Meeting, In 1844; Which Concern Extended to New England; for Which Service He was Liberated by His Friends at Home; But Owing to the Well-Known Difference in our Society on Points of Doctrine which then Existed There, the Prosecution of His Concern Was Opposed; to Which He Submitted, in Accordance with Disciplinary Order, and Left His Burden with Them.

The first account we find of his engaging in this visit,
is contained in the following extract of a letter, written to his wife,
after his arrival at New York:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
New York, Sixth Month 12th, 1844.

[.salutation]
My dearly beloved Wife:

I am now at the house of our dear friend, John Wood.
I set off from Wheeling as was expected, on Seventh-day morning, the 1st of Sixth Month,
and got to Westland in the afternoon.
Went to see our afflicted friend, Mildred Ratcliff, who is very feeble,
yet appears to be alive in the Truth.
Attended meeting at Westland, on First-day;
and set off on Third-day evening in the stage, and crossed the mountains to Cumberland,
where we took the rail-cars for Baltimore, and arrived in the evening.
Set off next morning for Philadelphia; got in about 3 o`'clock, and was, as heretofore,
kindly received.
I soon went to see Joseph Snowden, the Friend I had looked towards to bear me company;
but he being in poor health, it was not suitable.
Charles Williams being spoken to, gave up to it, and is now, agreeably, with me.

On Sixth-day, made several calls, with my dear Friends, S. Hillman, and others;
and Seventh-day, went to Westtown.
Attended both the morning and evening meetings, to satisfaction.
My visit there was very interesting,
both as respects the conduct and appearance of the pupils,
and the general management of the school;
and I enjoyed myself there as much as I could expect,
considering the weight of exercise in view of the prospect before me.
I try to keep the sack-cloth as much within as possible.
Ah, truly the Spirit bears witness that bonds and afflictions await.
We expect to set off tomorrow for New England.
May the Lord, in his condescending mercy,
be pleased to be near in every time of conflict,
and sustain by his everlasting Arm underneath.
Whether suffering or rejoicing be meted out, may He have the praise of his own works.

[.signed-section-signature]
Joseph Edgerton.

--

Nothing appears between this letter and the following:

Philadelphia, Sixth Month 28th.--Left this city in company with James R. Greeves,
and lodged at the house of our dear ancient Friend, Ezra Comfort.
Went to Pottstown on the 20th,
and had a small meeting in the afternoon with the few members, and others there.
Felt peace of mind in the faithful discharge of allotted duty.

First-day, 30th.--At Exeter Meeting,
wherein strength was afforded to open the doctrines of the
Gospel in the "`demonstration of the Spirit,`" through the
immediate assistance of our blessed and holy Head.
May the praise be ascribed unto Him who is worthy forevermore.

Second-day, Seventh Month 1st.--Attended meeting at Maiden Creek,
which was owned by the presence of the Head of the Church.
The spring of life flowed freely in a line of encouraging communications to
some exercised travailing children to hold on their way,
and devote themselves unreservedly unto Him whose right
it is to be "`Head over all things to his Church.`"
Some were affectionately addressed,
who had allowed the things of time to engross their attention,
so as to obstruct the growth of the good seed.
The meeting ended in fervent supplication to the
Lord for the continuance of his gracious regard,
that his poor,
dependent children might be supported and strengthened to stand in their allotments.
May praise and thanksgiving be ascribed unto Him forevermore.

Third-day, crossed the Blue Mountains to the house of David Masters, at Greenwood;
and the next day attended meeting there, which was a season of mourning,
under a sense of the low state of the Church.
Way at length opened to discharge myself to some careless, nominal professors;
and also a word of encouragement to some of the youth.
Left in peace, and rode to Muncy; and attended meeting there on Fifth-day;
and though the life of religion seemed to be at a low ebb,
strength was given to throw off the weight of the exercise in
close dealing towards the lifeless professors;
while the language of encouragement flowed freely to the honest-hearted.
Set out on Sixth-day morning for Elkland, on the Allegheny Mountains;
the scenery on the way was delightful.
Arrived at Joel McCarty`'s in good time in the evening.
He had recently buried his wife,
who had been a valuable minister and "`Deborah`" in that place.
In the morning had some religious service in the family, which, I hope, may be remembered.
Attended meeting near Anthony Kilmer`'s, on First-day, the 7th,
which was large and laborious, but was favored to find relief by honest labor.

Second-day, rode back to Muncy, to the house of our kind Friend, H. Ecroyd.
After breakfast, had a very solemn parting opportunity, and then rode to Pottsville.
Having felt my mind drawn towards the inhabitants of this place,
I had a meeting appointed at early candle light.
The meeting was small, but solid; and, I trust, the good cause did not suffer thereby.

Sixth-day.--Had a meeting at Robeson, which was an open time.

Seventh-day.--At Nantmeal; the state of Society very low.
A number of other people came in, and it proved an open time.
May the Lord have the praise of all his works.
In the afternoon, at Uwchlan; an open, satisfactory meeting: First-day,
14th.--At Downingtown in the forenoon; an open, good meeting.
Ability was afforded to open, in a good degree,
in the "`demonstration of the Spirit and of power,`" the doctrines of the Gospel;
showing the difference between the worship under the
legal dispensation and that instituted under the Gospel.
In the afternoon at Westchester; a very crowded meeting.
The weather being oppressively warm, rendered it trying;
and though the life did not rise so high as is sometimes the case,
there was a liberty granted to declare the "`unsearchable
riches of Christ,`" and found relief.

Second-day.--At Birmingham; which was a season of favor.
At Bradford in the afternoon; which was an open, heavenly meeting.
May the Lord be praised.
Lodged at the house of our dear Friends, Samuel and Ann Cope,
where we were sweetly refreshed, both in body and mind.

Third-day.--At East Cain and West Cain; both good meetings,
the Lord`'s power being manifested, and the gospel of Christ preached, I trust,
in the "`demonstration of the Spirit and of power;`" which, blessed be his holy name,
reigned over all.
Next, at Sadsbury and Bart; which were seasons of Divine favor.
Oh, my soul! may you forever bow before Him who has dealt marvellously with you,
and yield obedience unto Him in the future steps of your pilgrimage,
for He is worthy to be served forever and forevermore.

Sixth-day.--At East Sadsbury.
Found relief and peace in close labor to some worldly-minded professors,
with a solemn warning to flee from the wrath to come;
that they might lay hold on eternal life, and be found among the living in Jerusalem.
The word of encouragement flowed freely to some, particularly to the youth,
to give up to follow the blessed Captain of salvation in the way of his holy requirings.
In the end it proved a good time.
At Fallowfield in the afternoon, which was also a good meeting.
It is the Lord`'s doing, and marvellous in our eyes.
Indeed, to me it is remarkable, that a door of utterance has been so opened for me.
May the Lord have the praise.

Seventh-day.--At London Grove and West Grove; both open, good meetings,
particularly the latter.

First-day, 21st.--Called to see a dear, aged Friend, who is blind:
the word of encouragement flowed through my heart to her,
and her husband who was also infirm.
Attended London-Britain in the morning; and New Garden in the evening.
The Lord`'s power was present for the help of his people, and the day closed peacefully.
"`Return unto your rest, O, my soul,
for the Lord has dealt bountifully with you!`" and may I stand resigned,
and devoted to the service of my divine Master,
until He may proclaim a release from further service in this land,
that I may be permitted to return to my dear wife and children with the reward of peace.

Second-day.--At Hokessin, and Kennet; both seasons of renewed favor.
In the former I was led to speak closely yet tenderly,
to some who are in the earlier walks of life,
to give up to follow the blessed Shepherd of the sheep who would lead them from the
vanities of the world into an earnest concern for the salvation of their own souls.
And to those in more advanced life; that they might be found faithful,
showing forth his praise who has "`called them to glory and to virtue.`"
The latter was an open, yet rather a laborious time;
and at the close I felt the sentence of death within myself.
O, how we poor finite creatures are dealt with! that no flesh may glory in his presence.

Third-day.--At Concord, where strength was afforded to discharge apprehended duty.
The meeting closed in prayer for the blessing of
preservation of the flock and family scattered abroad,
that strength might be vouchsafed "`earnestly to
contend for the faith once delivered to the saints.`"
But O! I feel a jealousy and fear,
lest I may move improperly in the solemn embassy in which I am engaged.

You, O Lord, know my heart;
that it would be grievous indeed to leave you--the living fountain!
Be pleased to keep me as a little child, that I may adopt the language, "`Not my will,
but yours, O Lord, be done.`"
Dined at N. and P. M.`'s, very pleasantly.
It is cheering to call upon those whom we can feel in the covenant of life.
Rode to Wilmington, and attended meeting there on Fourth-day, to satisfaction.

Fifth-day.--At Chichester and Chester, which were relieving opportunities.
May the Lord`'s name be praised who is worthy forevermore.
Lodged at the house of Jesse J. Maris.

Here he writes to Ann Branson, as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Chichester, Pa., Seventh Month 25th, 1844.

[.salutation]
Dearly beloved friend, Ann Branson:

I have felt my mind sweetly turned
towards you this morning in the covenant of life,
even that in which the Lord`'s humble and dependent ones know, and feel one another,
though far separated;
and wherein they are permitted to drink together of the cup of suffering;
even the sufferings of Christ which are behind, for his body`'s sake, which is the church.
These being brought into the same school--the
school of Christ--they can understand each other,
speaking the same language, and minding the same thing;
and it is a blessed privilege they have, in the Master`'s time, to rejoice together,
and to bless and praise Him for his loving kindness to them;
also that they have been accounted worthy to suffer for his sake; and as they thus abide,
he will enable them to arise and "`anoint the shield,`"
and go forth against his and their enemies.
Ah! the work is the Lord`'s; and in every step taken the solemn language is applicable,
"`Who is sufficient for these things.`"
Nothing short of divine power daily communicated,
can renew the "`cruse,`" and qualify for the allotted portion of service.

It is a day in which the ambassadors of peace have, in many places,
to "`weep bitterly,`" under a sense of the deceivableness of unrighteousness.
Ah! in many ways the enemy of the church is at work;
and perhaps in no one particular has he proved more sorrowfully successful,
than in a worldly, deceptively delusive spirit, which is at work in the "`camp.`"
Unwilling to bear the cross, though, at the same time,
insinuating a love for the Society, and is secretly working, like a mole under-ground,
to destroy the root,
and would gladly modify Quakerism so as to suit the views of
other people better--more congenial to the world`'s ways,
worship and ministry;
and thus lead back into that which our dear forefathers were gathered out of.

As respects my visit to New England; I thought I felt an evidence of being in my place;
though, of all the sea sons of suffering I ever had to endure, I think that exceeded.
The language respecting our divine Master was very forcibly brought, to view;
"`He was despised and rejected of men, a man of sorrows and acquainted with grief.`"
Also; "`It is enough for the disciple that he be as his Master,
and the servant as his Lord.
If they have called the Master of the house, Beelzebub,
how much more them of his household.`"
You have, no doubt, had particulars of my visit.
There is a remnant of faithful, honest-hearted Friends there,
for whom I deeply felt and sympathized, having frequent opportunities with them,
which were heart-tendering seasons.
O! may the Lord, who knows the hearts of his people,
take his cause more immediately into his own hands,
and make it more and more manifest who are his,
that the oppressors of the seed might be brought to see
the awfully dangerous ground they are standing upon,
that they might "`repent and live.`"

I may acknowledge that notwithstanding "`tribulations have abounded,`" I humbly trust,
"`grace has also abounded;`" having been favored to get along thus far,
in the limits of this Yearly Meeting to the relief and peace of my own mind;
which I more and more feel to be of divine mercy.
Oh! it seems to me more clearly than ever before
that this treasure is in earthen vessels;
vouchsafed unto us for the honor of his own eternal name,
that the excellency of the power may evidently appear to be of God, and not of us:
that the creature may indeed be kept in the very dust.
I feel a sweet and heavenly unity with you, my dear sister.
O, it is a blessed thing to be scholars in the same school of Christ!
These are born of the incorruptible seed, and can,
and do suffer for and with each other; and with their divine Master for the body`'s sake,
which is the church;
and therefore in due time He will be unto them the "`resurrection and the life.`"
O! may you, and all the Lord`'s faithful servants be encouraged,
devotedly to persevere in his service;
for such may rest assured He will keep them in the "`hollow of
his holy hand,`" and "`no evil shall befall them,
nor any plague come nigh.`"

[.signed-section-closing]
Your friend,

[.signed-section-signature]
Joseph Edgerton.

--

Sixth-day.--At Middletown and Goshen meetings; and at Whiteland on Seventh-day,
which were solid good meetings.
Paid a visit to a dear young woman who has been confined two years and two months,
the most of the time in a recumbent position.
She appeared to be in a very peaceful state of mind;
and it was a privilege to be with her.
Also paid a visit to Yardley and Hannah Warner;
and feeling my mind drawn towards them in the love of the gospel; in the flowing thereof,
I was led in a sitting with them, to speak forth the language of encouragement;
and in a particular manner to Hannah.
O, I do believe the good hand is at work, and in due time, if faithfulness is yielded to,
there will be a coming forth in the ministry.

First-day, 28th.--At Willistown and Springfield; both favored meetings,
particularly the former.
Lodged at the house of my dear friends, Joseph and Hannah Rhoads.
Attended Darby Meeting on Second-day, and stopped at the house of Samuel Rhoads,
where I met with dear Hannah Gibbons, who is a lively-spirited handmaid of the Lord.
Arrived in the city in the evening, and lodged at the house of my kind companion,
James R. Greeves.

Thus closes the account of this visit,
except what is contained in the following extract of a letter to his wife:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Seventh Month 30th, 1844.

[.salutation]
My dear Wife:

My companion, James R. Greeves and myself,
have been diligently engaged in visiting meetings,
having had for four days past two meetings a day; and the weather being very warm,
I felt almost worn down last evening.
I think I never was more sensible of injury from hard labor;
but felt anxious to get through what is before
me by the time of Philadelphia Quarterly Meeting,
which will occur the first Second-day in next month.

We have but one meeting each for today and tomorrow, and on Sixth-day, two again.
We also expect to attend Abington Quarter, which will occur on the 8th of next month;
and the next day I think of turning my face towards home, and unless detained on the way,
may reach there by the 12th or 13th. My love to all.

[.signed-section-signature]
Joseph Edgerton.

--

[.asterism]
'''

[.embedded-content-document.letter]
--

[.letter-heading]
Letter to Ann Branson.

[.signed-section-context-open]
Sixth Month 21st, 1845.

[.salutation]
Dear friend, Ann Branson:

My spirit salutes you in the covenant of life,
desiring your encouragement in the work and service of the Lord;
having full unity with you therein;
and feeling much for you on account of the feeble state of your dear father`'s health,
as also, in my measure,
with you in the deep baptisms and trials to be endured by
those who go forth as ambassadors for the King of peace.
And very earnestly do I desire for you, as for my own soul,
that a firm and steadfast abidance may be known in Him who has hitherto helped,
giving an understanding of his will concerning us from day to day.
Oh, my soul can say, under some sense of feeling,
that the Shepherd of the sheep is good and
gracious--worthy to be waited for and followed,
in every step we take, with the most entire dedication.
Then, dear sister, go on in his service,
and I firmly believe that his own little dependent followers will be cared for,
and strength administered, day by day,
just in such a way and time as will give indisputable
evidence that it is the Lord`'s doing,
and marvellous in our eyes.

It has been my lot to witness a depth of suffering for some weeks past;
the enemy being permitted to buffet and upbraid; but through Divine mercy,
I seem to have got a little over it.
My soul feels humbly thankful to the Lord for his matchless mercy;
and may I be willing to follow Him through every permitted trial,
that "`neither heights nor depths, things present nor to come,`" may separate from Him,
the beloved of my soul.
Ah, the present is a peculiarly trying day to the Church.
Her living members realize it to be so.
May they be favored to keep near to her holy Head in
living exercise and prayer for the flock and family;
and thus a qualification will be received of Him,
to be as "`Saviors upon Mount Zion,`" by and through his immediate puttings forth,
both as regards the great and important duty of solemn worship,
as well as the exercise of the discipline of the Church.
For this compromising spirit of modified Quakerism has the same injurious,
lifeless tendency, both in worship and discipline.

It leads into a lifeless, frothy ministry,--not being under the cross,
but disposed to shun it; though, as to words, it may be pretty sound;
while to those whose ears can try words as the mouth tastes meat,
it is unsavory and superficial.
It also leads to a lifeless management of the discipline;
the Lord`'s power not being waited for,
a light and unfeeling routine of business in our
meetings for discipline is the consequence.

Oh, how the poor baptized members of the body--those who,
like the "`chosen in Gideon`'s army,`" are found bowed very low,
--do mourn because of the prevalence of such a spirit.
May they faithfully keep their ranks in righteousness,
for the Lord is on his way for their deliverance; yes,
the day will come when the "`watchmen on the
walls of Zion`" may "`send presents of this kind,
one unto another,`" with grateful acknowledgments that "`Truth
prospers,`"--that the "`Lord has done great things for us,
whereof we are glad.`"
Then, indeed, may it be said:
"`How beautiful upon the mountains are the feet of Him that brings good tidings,
that publishes peace; that brings tidings of good, that publishes salvation;
that says unto Zion: your God reigns.`"

Your lines of Ninth Month last, accompanied by a letter of more recent date,
came duly to hand, and were gratefully received.
I may say,
I have derived instruction from the writings of that devoted servant of the Lord,
John Barclay.
I earnestly desire to be found "`pressing after
the prize,`" which he kept so steadily in view;
and through the power of living faith was, no doubt, enabled to obtain.
Ah, indeed, there is a sweet unity with the living, faithful followers of the Lamb;
even those who, having "`fought the good fight,
and kept the faith,`" are entered into rest and peace.

The feeling of near and dear love attends your
dear father in the fellowship of the Gospel.
May the dew of heaven, which makes flourishing and fruitful in the house of God,
be his portion, even now, in old age, agreeably to the words of the Psalmist:
"`They that be planted in the house of the Lord, shall flourish in the courts of our God;
they shall bring forth fruit in old age; they shall be fat and flourishing.`"

[.signed-section-closing]
I remain, your friend,

[.signed-section-signature]
Joseph Edgerton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Letter to Thomas B. Gould.

[.signed-section-context-open]
Sixth Month 17th, 1846.

[.salutation]
Dear friend:

Yours of Eighth Month last came to hand,
together with some documents forwarded by you;
and I thought soon to have written a reply, but many engagements have hitherto prevented.
I hope, however,
that it has not been supposed to have originated
from a lack of tender love and sympathy for you,
and many other dear Friends in that part of the heritage;
but as the matter has revived this morning, with some degree of sweetness,
I very willingly communicate the desire of my heart for
your and your preservation in the unchangeable Truth;
believing that He who gathered us in the beginning from the many forms and ceremonies,
instituted by the wisdom, and in the will of man, into the covenant of light and life,
as we are faithful to Him, will never leave nor forsake us.

O, I do most earnestly desire, that all our dear Friends, both there and here,
as well as in every other part of the Lord`'s vineyard,
whose eyes have been anointed to see the deceivableness of unrighteousness,
whereby the enemy is endeavoring to lead away from the true foundation;
to modify our high and holy profession,
rendering it more agreeable to the views of other people,
that there may be less cross to bear,
may stand fast in that liberty wherewith Christ has made them free;
being willing to suffer, whether from pretended friends or open enemies;
and as Divine assistance is vouchsafed,
to rejoice in being accounted worthy to suffer for his great name and Truth`'s sake.
May the remnant in that part of the heritage,
who have had to drink deeply of the cup of suffering--the persecuted
little flock--be encouraged to lift up their heads in hope,
for the day of their redemption draws nigh.
Oh, keep inward to the Lord, moving in his counsel;
thus you will be kept in the meekness and gentleness of Christ, under his government,
which will do more for you than all the arguments that
can be adduced in the time and wisdom of man.

I feel deeply for you on the approach of your Yearly Meeting,
desiring that the blessed Head of the church may be near,
furnishing with wisdom and strength to move therein to his honor,
and the promotion of that cause which is the most
dignified that mortal man can participate in.
In a very lively manner do I remember the sympathy
which clothed my mind when with you a few years ago;
at which time, I trust, I was, in my measure, a sharer in the "`afflictions of Christ,
which are behind, for his body`'s sake,
which is the church;`" and witnessed the true Christian
sympathy whereby we are enabled to remember,
and to feel for those "`in bonds, as bound with them; and those who suffer adversity,
as being also in the body.`"

It is cause of deep humiliation to those who through the Lord`'s unutterable mercies
are brought into the blessed "`lot of inheritance,`" and to "`sit together in
heavenly places in Christ Jesus;`" that He has vouchsafed his loving kindness,
and tender compassion in giving them to know a settlement on
the "`Rock of Ages,`" and to feel at the same time,
that "`it is not by might, nor by power`" of their own, that they are favored therewith;
but of his abundant love:
hence in meekness and gratitude they will be found returning thanks unto God therefor,
while they will be led deeply to feel for,
and to pity those who have been captivated and led away
from the "`footsteps of the flock of Christ.`"

Many dear friends are very fresh in my remembrance,
to whom I desire a message of dear love in our Lord Jesus Christ.

[.signed-section-signature]
Joseph Edgerton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Letter to Ann Branson.

[.signed-section-context-open]
Second Month 10th, 1847.

[.salutation]
Dear friend Ann Branson:

Your very acceptable letter came duly to hand,
reviving feelings of gospel fellowship.
The poor tribulated followers of the Lamb are favored
to feel one for another in their respective allotments;
to drink together of the same cup, though it may be that of affliction:
and sometimes even the "`wine of astonishment`" may be therein.
O! if it were not for the mercy and compassionate regard of our holy "`high
priest and advocate with the Father,`" what would become of us?
He knows our frame; that we are but dust.

Amidst all the conflicts of flesh and spirit,
we cannot doubt the faithfulness of the Lord;
though He may cause to "`pass through the waters.`"
His presence, though unseen by us,
will be near to bear up and thus qualify his servants and handmaids for his service.
Ah! it is through "`deaths oft`" that they are brought into a capacity,
in which the King Eternal sees fit to entrust them with his treasures:
like the "`good scribe`" bringing "`forth out of his treasure things new and old:`"--new,
because in the fresh openings of divine life: and old, because it is of,
and from that which is from everlasting; that changes not.

My dear friend, I desire your encouragement in the work of the Lord.
May "`the arms of your hands be made strong by the hands of the mighty God of Jacob.`"
This is truly a day in which the baptized members of the Church are clothed
with mourning on account of the oppressed state of the true seed.
It is to be feared that many of the members who remained on
the side of Truth in a storm recently passed by,
are, nevertheless, so much on the surface--have so little of that living, upright zeal,
originating in a faithful attention to the voice of the good Shepherd,
which so eminently characterized the sons of the morning of our day--
that they are in a sad condition to bear another storm.
And it appears evident that the day is approaching that will try the foundation.
I have greatly desired that the "`watchers upon the walls of Zion,`"
who are standing in the authority and dignity of her King,
may be kept near unto Him,
whereby they may be qualified to attend to any little service required at their hands,
with that singleness of heart which becomes their high and "`holy calling.`"
It seems to me there never was a time in which the necessity
was more binding upon us to stand in our allotments,
with "`lamps trimmed`" and "`lights burning.`"

Though much poverty has of late been my portion, yet, at times, through Divine mercy,
light has sprung up, to the removing of every doubt.
Oh, how good it is to "`wait patiently for the Lord to incline his ear
unto us and hear our cry;`" to pluck our "`feet out of the miry clay,
and set them upon a rock;`" putting "`a new song into our mouths,
even praises unto our God.`"

My earnest desire for myself is, that I may be kept in the line of Divine appointment;
being willing to be stripped of every dependence,
save upon the almighty Arm of power immediately made known;
that in the steps yet to be taken, I may be enabled to adopt the passive language:
"`Not my will, but yours, be done.`"

Oh, it is no matter how much of the cross we have to bear,
how humiliating to the creature the leadings of the good Shepherd may be,
(as truly it is,
to be bound and carried where the natural part "`would
not,`") so that we may be found in the Divine ordering;
and,
though sensible that the "`Spirit bears witness in every city
saying that bonds and afflictions abide,`" be enabled to say:
"`None of these things move me; neither count I my life dear unto myself,
so that I might finish my course with joy, and the ministry,
which I have received of the Lord Jesus, to testify the Gospel of the grace of God.`"

I conclude, and remain your friend and companion in tribulation,
and desire to be in the faith and patience of Jesus Christ.

[.signed-section-signature]
Joseph Edgerton.

--
