== Chapter IX.

[.chapter-synopsis]
* Account of a visit to Philadelphia Yearly Meeting and its branches.

Having felt my mind drawn to visit, in the love of the Gospel,
some of the meetings composing the Yearly Meeting of Philadelphia,
as also to attend that meeting,
and having obtained the concurrence of Friends for that purpose, I set out,
leaving my dear wife and children, the 10th of Fourth Month, 1847,
and reached the city on the 14th of the same.
I attended meeting at Arch street the next day, wherein silence appeared to be my lot.
There was much vocal service; but if there were any mighty works done,
I was not sensible of it.

Sixth-day, 16th.--Attended the Meeting for Sufferings, to good satisfaction.

Seventh-day.--The Select Yearly Meeting; a low time.
Several communications to little purpose.
On entering upon the business of the meeting,
the clerk read all the minutes of the strangers present, except those from New England.
He then informed the meeting that there were several minutes from New England,
but as the subject of correspondence with that body was
referred by the minutes of last Yearly Meeting,
he thought it would be right to omit the reading of them, which was united with,
though several opposed it, urging the reading of them.

First-day, forenoon.--At the North Meeting.
Sat in silent suffering under the exercise of a light, frothy ministry.
In the afternoon, at the same place, to satisfaction.
Went to the house of our valued Friend, Ezra Comfort, Jr.;
walked over to see an aged blind Friend,
and had a solid season of retirement in the family.
I trust it was an opportunity of profit to some.

Third-day.--At Solebury and Wrightstown; the former, a good meeting; the latter,
a laborious time.
My mind was clothed with mourning on account of the unfaithfulness of some under our name.

Fourth-day.--Attended Monthly Meeting at Middletown.

Fifth-day.--At Falls, to satisfaction; Truth having the dominion.
Attended meetings at Byberry, Bristol, Trenton and Byberry again; the latter, a small,
but comfortable meeting.

Feeling my mind drawn towards the poor convicts in the Pennsylvania Penitentiary,
I proceeded there on Second-day, 26th, in company with my dear friend and companion,
Joseph Hobson, and also John Kite, where we found about three hundred prisoners.
Our friend, Thomas Scattergood, being warden, went with us,
and we visited a number of their cells;
had six different opportunities with the prisoners.
I felt constrained to press upon them the necessity of
attention to the gift of Divine grace in their hearts,
that would show them their sinful condition,
and lead them to repentance and amendment of life,
and thus be prepared when their time should expire, to go and sin no more.
After the close of the first sitting, we passed by the cell of a poor woman,
who called to the warden, saying she wanted to speak to the Friends.
We went into her cell, and found her with tears rolling down her cheeks,
and weeping aloud.
My feelings were turned towards her in tenderness,
and I told her to take heed to the gift of God in her own heart,
which had shown her the exceeding sinfulness of her ways,
that she might experience true repentance, and the forgiveness of her sins,
and have comfort in her solitary cell.
I felt peace for this act of dedication.

Third-day.--At Frankford Monthly Meeting, which was a good meeting.

Fourth-day, 28th.--At Germantown and Abington; the former was an open,
relieving opportunity; the latter, in the forepart, was heavy and laborious.
Found relief in faithfully discharging apprehended duty.

Fifth-day.--At Gwynedd Monthly Meeting; which was, through Divine mercy, a good meeting.
May thanksgiving and praise be returned unto Zion`'s King.
Lodged with our dear friend and father in the Church, Ezra Comfort.

Sixth-day.--At Plymouth; a favored meeting, the blessed Head of the Church being near.
The meeting at Horsham, on Seventh-day, was a time to be remembered,
because Truth reigned over all.
May the Lord have the praise;
and may all that is within me bow in humble prostration before Him
who is able to exalt his great and holy name over all opposition.
Rode to Plumstead, and attended meeting there on First-day, to satisfaction.

Second-day, 3rd of Fifth Month.--Attended Monthly Meeting at Buckingham; which,
through Divine mercy, was a heavenly meeting,
strength being given to labor honestly with the careless;
while the language of encouragement flowed freely to the mourners in Zion.

First-day, 9th.--Attended meeting at Trenton, to satisfaction.

Second-day.--At Evesham and Cropwell; both favored meetings.

Third-day.--At Haddonfield; from there towards Salem, to attend that Quarter.

Fourth-day.--Attended the Select Quarterly Meeting;
and the Quarterly Meeting for Discipline, on Fifth-day; which was a favored time.
May the praise be returned to Him who is "`Head over all things to his Church.`"
Lodged with our dear, aged friend, John Sheppard.

Sixth-day.--At Greenwich; which was a time, I trust, to be remembered.
Truth had the dominion.
Having felt my mind drawn towards the inhabitants of Bridgeton,
we had a meeting there in the afternoon, which was very small, though solemn and quiet;
and I trust the good cause did not suffer thereby.
Returned to Philadelphia, and attended the Southern and Northern meetings on First-day,
16th, which were favored opportunities, and greatly to my relief.
O! It is of the Lord`'s mercy that ability can be
received to labour in the church of Christ.

Second-day.--At Concord Select Quarterly Meeting, to our comfort.

Third-day.--At the Quarterly Meeting.
A season of renewed favor.
May my soul be bowed in prostration before the Lord,
and kept daily and hourly in a state of humility; knowing that it is of his mercy.

Went to Westtown, and lodged,
and had a satisfactory meeting in that Institution the next day.
The divine blessing rests upon it.
Went to the house of Aaron Sharpless; our dear friend Mary Kite living there.
Had a time of refreshment in an opportunity in the evening.
Went towards London Grove to attend the Western Select Quarterly Meeting there.
A time of favor.
Lodged at the house of Morris Cope.

Sixth-day.--At the Quarterly Meeting.
An open time.
Returned to the city,
and having felt my mind drawn towards the inhabitants not of our Society,
more particularly the laboring class, seamen, etc,
the matter was laid before the select members, which was united with,
and notice given of a meeting at Arch street on First-day evening.
Oh, the awfulness of the step!--the appointment of a meeting of that character.
My feelings could not be described;
but felt satisfied and peaceful in having given up to what I
believed to be the pointings of the good Shepherd.
Paid a number of visits to Friends in the city, to my own peace, and their comfort;
namely: E. Pitfield, S. Hillman, John Kite, etc.

First-day morning, 23rd--At Arch Street.
A solid meeting.
The spirit of supplication was poured out,
and strength given to intercede for the poor of the flock,
that their faith might be increased; that "`heights nor depths,
things present nor to come, might be able to separate them from the love of God.`"
That, as many had been removed from the church militant, to the church triumphant;
particularly of these who were pillars in the Lord`'s house,
that he would turn his hand upon the middle aged, and those that are younger;
and through the operation of the same Divine Power that made them what they were,
many might be fitted for their stations in the church, to his honor.
In the afternoon attended the same meeting, but was silent.

At the time appointed in the evening, at the meeting at Arch Street,
which was largely attended, and very quiet; and was to me a relieving opportunity.
O, how awful the responsibility of appointing meetings out of Society!
Surely none are sufficient for these things, but as they receive strength from on high.

Took leave of many dear friends at the close of
the meeting in a feeling of gospel fellowship,
and set out for home.
Through divine mercy we were favored to reach there on Fourth-day the 26th of the month,
and found my dear family well.
