== Chapter XI.

Account of a Visit to the Meetings Belonging to North Carolina Yearly Meeting.

Feeling my mind drawn to visit in the love of the gospel,
the meetings of North Carolina Yearly Meeting;
and having obtained the necessary certificate of the unity of Friends therefor;
I took a solemn leave of my dear wife and children, the 31st of First Month, 1849:
committing them, with my own soul, unto the Lord.
May He be pleased to strengthen her, who is my chief earthly comfort,
and endue her with fortitude and wisdom, to go in and out before our children;
and to keep them from evil, and cause the seed which He has sown in their hearts,
to grow and bring forth fruit to his praise.

Lodged at R. Cowgill's,
where my friend Abraham Packer met me in order to accompany me in my prospect.
Set out on Fifth-day morning, the 1st of Second Month,
and reached Red-stone Quarterly Meeting on Seventh-day; wherein sorrow covered my mind,
on account of the disunity occasioned by the
unsound writings that are sanctioned among us.
I had the reward of peace in attending to the portion of service required.

Attended meeting at Centre on First-day, to satisfaction;
and set out on Second-day morning towards Winchester; and arrived on Fifth-day,
the 8th. From there to Lynchburg, and rested one day.
There being a few individuals in the town who profess with Friends,
they were invited in to see us, and we had a religious opportunity together;
but was a low trying time on account of a lack of religious concern.
Left on Sixth-day morning for North Carolina,
and arrived at Hopewell on Seventh-day evening, and attended that meeting on First-day.
After resting a few days at the house of our dear friends Dougan and Asenath Clark,
we attended New Garden Meeting, to satisfaction.

Fifth-day 22nd.--At Centre; which though small, was a solid, good meeting.

Sixth-day.--At Back-Creek Select Quarterly Meeting;
and at the Quarterly Meeting for discipline the next day.
On First-day, attended a large public meeting at the same place,
wherein the Head of the church was pleased to give ability to
declare the "`unsearchable riches of Christ,`" in the
demonstration of the Spirit.
May the praise be ascribed unto Him alone to whom it is due.

Next atttended meetings at Uharee, Bethel, Pine-Ridge, Holly-Spring, Marlborough,
and Marlborough Monthly Meeting, held at Salem; the latter a time of favor.

First-day, Third Month 4th.--At Springfield.
Thank fulness clothed my mind this morning under a
sense of the unmerited mercy of the Head of the church,
in opening a way where there seemed to be none.
Truly my soul can in some degree of feeling, adopt the language of t he Psalmist,
"`What ailed you, O sea, that you fleddest?
you Jordan, that you were driven back?
you mountains, that you skipped like rams; and you little hills, like lambs?`"
May my soul bless and praise the name of the Lord our God,
who remains to be "`wonderful in counsel and excel lent in working.`"

First-day afternoon, at Kennet; wherein Truth reigned.
"`Return unto your rest, O my soul! for the Lord has dealt bountifully with you.`"

On the 5th and 6th at Piney-Woods and Deeg-River.
In the latter I was led to open the difference
between that faith which overcomes the world,
and that which is over come by the world.

Extract of a letter to Ann Branson:

Third Month 7th, 1849.

My beloved friend Ann Branson:--In a feeling of
that love which has long subsisted between us,
I address a few lines to you,
and acknowledge the receipt of yours at the hand of A. Packer, which was very acceptable,
and served as an encouragement to my deeply tried mind.

It has not, I think,
been my lot to experience deeper baptisms than have been my portion of late,
and particularly on our way to this land,--wisely dispensed, no doubt,
as a preparatory dispensation for the allotted portion of service.
Oh, may I be kept so near my Divine Lord and Master in deep travail of soul,
that I may be permitted to enter into sympathy and suffering with the seed,
which is borne down in many instances as a "`cart loaded,`" that I
may be so given up and devoted to his service in this journey,
that one hour may not be spent in gratifying the creature,
nor one thought indulged which does not centre in that submissive language:
"`Not my will, but yours, be done.`"

In going from place to place, we have had, to our great comfort,
the company of Him who formerly sent forth his disciples into "`every city
and place where He himself would come;`" and in the midst of deep exercise,
has renewed the "`cruse`" from day to day; so that if the query was addressed:
"`Did you lack anything?`"
the responding language, under a sense of unmerited mercy, must be: "`Nothing,
Lord;`" and yet, often stripped, and so empty as a vessel can be; and, perhaps,
I may indulge the hope that I am learning a
little of that lesson that an apostle speaks of,
when he says: "`I have learned in whatsoever state I am, therewith to be content.`"
Many are the exercises which the servants and handmaids
of the Lord have to pass through for Zion's sake,
as well as frequent baptismal washings, to make them clean and keep them so.
I desire, as regards myself,
that none of them may be with held which Infinite Wisdom may see fit for me; and truly,
my soul can, under a sense of the Lord's gracious dealings,
adopt the language of the Psalmist: "`What ailed you, oh, sea!`" etc.

Way has been made for us without any effort of our own, to my humbling admiration.
Last Second-day morning we paid a visit to our ancient friend, Mahlon Hocket.
He appears to be in a comfortable, innocent state of mind.
After spending a little time in pleasant conversation, the company dropped into silence,
at the close of which he said:
"`I must acknowledge that I feel thankful for this opportunity.
I have felt the savor of life to refresh my spirit.`"

My dear sister,
I hope you will be encouraged to a faithful
occupancy of the talents committed to your trust.
I feel myself to be a poor little one,
much more fit to be ministered unto than to minister; yet, perhaps I may say,
that there is encouragement for all the Lord's faithful servants,
to stand as with their loins girded, and their feet unfettered,
waiting and watching at their posts,
that when the command may be given to go forth into service, they may, with willing,
confiding hearts, commit them selves, and their all into his holy hand;
and as they stand in the obedience of faith, He will take care of them and his cause.

I remain, in the fellowship of the Gospel, your friend,

Joseph Edgerton.

Fourth-day, 7th.--At Concord, to satisfaction; and the three following days, at Centre,
Providence and Rocky River;
in the last of which strength was afforded to discharge allotted service;
though sadness covers my mind from meeting to meeting,
under a sense of the suffering of the true seed.
May the Lord of Sabaoth make a way for it,
that the Church may arise from the wilderness state she is in,
and shine in her ancient beauty.

First-day, 11th.--Were at Cane Creek, where was a large mixed assembly.
A Wesleyan Methodist minister having a meeting appointed at the same time,
not far from there, he deferred his meeting until afternoon,
and came with his company to Friends' meeting.
The meeting was held throughout in silence.
My Divine Master showed me plainly that the service He had for
me at this time was to set an example of silence;
though I had to warn Friends to be on their guard,
as I believed there was a snare laid to draw the
inexperienced from the Truth as we profess.

In the afternoon, at South-fork, wherein Truth reigned over all.
May the praise be ascribed unto the Lord alone, who is forever worthy.

Second-day, were at Spring Meeting, to satisfaction;
and set out on Third-day morning towards Contentnca,
and arrived at T. Kennedy's on Fifth-day morning,
in time to attend their mid-week meeting, at Neuse, which was very small.
You, O Lord, know how frequent and fervent my petitions are unto you for preservation!
You alone can keep me from falling, and give ability to do your will,
whether in labor or in silent suffering.
Oh, that "`patience may have her perfect work,`" that through all the bonds and
afflictions that may attend me in the embassy in which I am engaged,
your "`everlasting arm may be underneath,`" that I may
experience that "`tribulation works patience,
and patience experience, and experience hope,`" even that which "`makes not ashamed.`"

Sixth and Seventh-days, at Nahunta and Contentnea; which, though small,
were favored meetings.

First-day.--At Neuse again, which was large, and to the relief and peace of my mind.
Set out on Second-day morning towards Beaufort, and reached there on Fourth-day evening,
21st; and feeling my mind drawn towards the inhabitants of the town,
a place was procured, and notice given for a meeting in the evening,
which was pretty well attended.
The spiritual nature of the Gospel of Christ was set forth, I trust,
in the "`demonstration of the Spirit.`"

Fifth-day.--At Core Sound, with a few members, and some not of our Society,
to satisfaction.
I felt deeply for the honest-hearted there.

Seventh-day.--Had a meeting at the old Trent meeting house, with a company of people,
some of whom seemed to be as insensible of the solemnity and
dignity which becomes the duty of solemn worship,
as any I remember ever to have seen in a meeting.
Through Divine help I was enabled, in plain honest dealing, to discharge my duty,
and left in peace.

Second-day morning.---Started on towards Rich-square but were
detained at the Roanoke river nearly twenty-four hours by high wind.
During our stay at the river side we went into the hut of a poor old colored man,
who appeared sober and serious.
I asked him if he went to meeting.
He replied, "`No, he was too far off.`"
I asked whether he had any thought about being good.
He answered, "`Yes! the Lord has done something for a poor black man.
He showed me the fountain when I was there`"--pointing
to the place where he was in his hut at the time.
He asked me if I understood what he meant by the "`fountain.`"
I replied in the affirmative.
He said the time had been when he took delight in sinning, but now he did not.
I encouraged him to take heed to that which had showed him the
"`fountain,`" and it would preserve him from evil,
and enable him to live as he ought; and in the end he would be happy.
He seemed much tendered, and said, "`O, if people only could see! but they are blind.
I sometimes almost complain of them, but I ought not,
for I could not see until my eyes were opened.`"

We went to the house of one of the overseers of the slaves to get lodging.
I think I never suffered more on account of the cruelties
exercised towards the poor slaves than while there.
The females kept out ploughing in the cold and snow till after sunset;
and out next morning before sunrise; and they very poorly clad.
Will not the Judge of all the earth visit for these things.

Crossed the river on Fourth-day morning, and rode to Rich-square.
It being their meeting-day we attended, though quite late when we got in.
Finding it necessary to rest our horses, we tarried at J. Coxe's until Sixth-day morning,
and then went towards Piney Woods.

First-day, 1st of Fourth Month, were at that meeting; which, I trust,
was a season of favor to some present.

Fourth-day.--At Little River, which, though small, was owned by the Master of assemblies.
My spirit has been much depressed in passing through this land,
on account of the cruel system of oppression.
It led to very serious reflections,
and pained my heart to see the hardship practiced upon them by a merciless overseer,
who thus drives them, regardless of sex, through almost till kinds of weather.
I do fully believe that the Judge of all the earth will
not permit this outrage upon every feeling of humanity,
as well as Christianity,
but by terrible things in righteousness will answer and plead
with this highly favored nation until He "`break every yoke,
and let the oppressed go free.`"

Fifth-day and Sixth-days.--At Symonds Creek and Wells meetings, to satisfaction.

Seventh-day.--Attended the Monthly Meeting at Piney-Woods,
in which my mind was brought into deep exercise,
but strength was afforded to labor to the "`stirring up of the pure mind`" to
faithfulness in several particulars--the due attendance of our religious meetings,
in a lively exercise of mind;
the important duty resting upon parents in training up their children in the
nurture and admonition of the Lord was impressively treated upon;
and the importance of parents being clear of the blood of their children, set forth.

First-day, 8th.--At Beech Spring, which was a crowded meeting.
I was led to show the difference between the law that was written on tables of stone,
and the new dispensation, wherein the law is written upon the heart.
The meeting was to my relief and peace.

Lodged at N. Winslow's. Some of his children are members, but he is not.
Had some conversation with him in the morning, on the subject of holding slaves;
he having a number.
I queried with him whether he had not scruples in his mind on the subject:
he confessed he had, and that it was his intention to set them all free:
and acknowledged that he had put it off too long.
I encouraged him, as life was uncertain, to attend to it the first opportunity;
and he said he would.
I had peace of mind for this little act of dedication.

Returned to Rich-square on Third-day;
and felt easy to proceed towards Contentnea on Fourth-day morning; though,
as we passed through towards Pasquotank, I felt desirous to have a meeting,
which I mentioned;
but owing to the disunity occasioned by the unsound writings of J. J. Gurney,
there was no way opened for it.
I felt peace; believing I had done what was my duty to do.
I was thankful to the Lord to be accounted worthy to suffer for his name's sake,
in the support of the precious doctrines of the gospel,
for the maintenance of which our worthy fore fathers suffered so deeply;
every part and parcel of which is incumbent upon us faithfully to maintain,
even though it may be through much suffering.
Truly they are as well worth suffering for as when those
valiant sons of the morning stemmed the torrent of persecution;
being willing to sacrifice all that was near and
dear to them in this life--their liberty,
their estates,
and even life itself--rather than depart from those scriptural views of Christian
doc trine and practice which had been opened to them by the Day-spring from on High.
All that is within me capable of feeling,
is at times awakened on behalf of our beloved Society,
with desires that the Lord in his abundant mercy
would make bare his holy arm as in ancient days;
that everything that is not of his own pure spirit may
be washed out by the spirit of judgment,
and the spirit of burning, that we might become settled upon the "`Rock of Ages.`"

Attended Monthly Meeting there +++[+++probably at Contentnea],
and a public meeting on First-day: then proceeded towards New Garden,
where we arrived on Fifth-day, 19th, at the house of D. and A. Clark.

Attended Deep-River Quarterly Meeting on Seventh-day;
and the Select Quarter the day before; and the public meeting on First-day.
Our dear friends aforesaid went with us, and had good service.
The several sittings, particularly the two last, were seasons of favor.

Here he writes to his wife, the following being an extract thereof:--

New Garden, N. C, Fourth Month 23rd, 1849.

My very dear Wife:--We are now at the house of our valued friends D. and A. Clark,
in good health.
We arrived here on Fifth-day last from the east,
where I found two letters from the beloved partner of my life, which did me much good,
inasmuch as they bear clear evidence to my mind of the
continued care of the good Shepherd over you,
in keeping you in resignation and acquiescence to his blessed will;
and in enabling you to dip so feelingly into sympathy
with me in the arduous service in which I am engaged.
It has been refreshing to my spirit many times,
to be sensible that I have the prayers of many that are very dear to me;
even at times when it seemed much like going down among the "`iron
chariots`"--so much opposition in the hearts of the people;
and in many instances my eyes have seen the wonder-
working power of the Lord in opening a way for us,
to my humbling admiration.

May my soul forever bow in lowest prostration before Him whose work it is,
and not our own.
May He have the praise thereof, says my soul.
If we are favored to get along as well as we expect, I shall not probably write any more.

Your loving husband,

Joseph Edgerton.

Third-day, 24th.--At Hopewell;
in which ability was given to declare the "`unsearchable riches of Christ.`"

Fourth-day.--At New Garden Monthly Meeting; and at Dover Monthly Meeting on Fifth-day,
in which best help was afforded to discharge the allotted portion of service.
May the Lord be praised for his abundant mercy,
and the poor creature be kept forever in the dust.

Sixth-day.--Rode to Forbush, in Surrey County, and had a meeting there on Seventh-day,
at 10 o'clock; and at Deep Creek in the afternoon, to satisfaction.
Had the company of that dear Friend and "`Israelite, indeed,`" John Bond, at the latter,
to my comfort.
How comforting it is to have the company of those advanced in life, who,
like Simeon of old, are waiting for the consolation of Israel.

First-day.--At Hunting Creek; to the relief of my exercised spirit.

Second-day morning, 30th.--Set out on a lonely travel across the mountains into Tennessee.
Passed by what is called Fish-spring, which is situated between two high mountains,
on the bank of the Wataga River, in Carter County, East Tennessee.
It is a boiling spring, and emits water sufficient for a considerable mill stream.
The water is clear and cold,
and retains its clear appearance for some rods below where it runs into the river;
but the most remarkable thing connected with it is, considerable quantities offish,
principally black perch, are caught in a trap just below the spring.
They rise from this subterraneous fountain in the spring of the year,
so as to make it a source of income to the owner.
It is said that a part of this extraordinary spring is in the bed of the river,
and at low water can be seen boiling up, where, it is supposed,
the fish make their way into their unknown abode.
This fountain seems to be entirely unconnected with the river,
and no change discoverable between dry and wet weather.
We were favored to reach the settlement at New Hope on Sixth-day, the 4th of Fifth Month,
and attended meeting there on First-day, where were many not of our Society.
The truths of the everlasting gospel were opened, I trust,
in the "`demonstration of the Spirit,`" particularly
that of the universality of Divine grace.
Paid a visit in the after noon to a sick Friend, to the peace of my mind.

Second-day morning, set out for Lost Creek, and at tended that meeting on Fifth-day,
to the relief of my own mind.
From there to Newbury, and attended the Quarterly Meeting there on Seventh-day.
My blessed Master was near, and enabled me to discharge the service required.
May everlasting praise be given to Him alone.

So far as appears, this closes his labors in this journey.

Letter to his daughter:--

Seventh Month 6th, 1849.

Dear +++_______+++:--In feelings of dear and tender love,
you and your dear consort are often in my remembrance,
having no doubt of the extensions of heavenly regard to wards you;
and as you are kept in a daily exercise of soul before the Lord,
He will keep you and strengthen you for every service allotted.
I noticed with much interest in your lines to me when in a distant land,
your remarks relative to yourself.
I would have you endeavor to stand in the obedience of faith.
I doubt not, He whoso will is our sanctification, deals with us in perfect wisdom;
clothes us with an abiding sense of our utter helplessness and unworthiness;
and even sometimes gives to witness the truth of that Scripture,
"`I will allure her and bring her into the wilderness, and speak comfortably unto her.`"
I see no cause for you to be dismayed, but rather encouraged to trust in the Lord,
in "`the Lord Jehovah; for in Him is everlasting strength.`"

The present is a day of much painful exercise to the living members of the Church;
and deeply do I feel for those who are under the
preparing hand of the good Shepherd for service,
having in my measure had some experience therein; and I am satisfied there never was,
nor ever will be, but the one way of safety for these;
even an entire dependence upon the good Shepherd; committing the keeping of themselves,
and their all, in well-doing, as unto a "`faithful Creator,`" who is a tender Father,
and will lead them on; and though He may see fit to exercise them with purging seasons,
He will not administer one more than is necessary to bring about that
state of purity and fruitfulness which the great husbandman designs.
May you, my dear daughter,
be encouraged to trust in that Arm of Divine mercy
which you has felt extended towards and underneath you;
though you may at times be beset with doubts and fears respecting your getting along,
and be ready to adopt the language of one formerly: "`Oh,
that it were with me as in days past,`" when the
"`candle of the Lord shined upon my tabernacle.`"
Well satisfied I am,
that we are as much the objects of Divine regard in these seasons of discouragement,
as in the highest we can attain to.

Joseph Edgerton.

