== Chapter XII.

Account of a Visit to the Meetings of Redstone, Short-Creek,
Salem and Springfield Quarterly Meetings.

On the 24th of First Month, 1850, I left home in company with my dear friend,
R+++.+++ H. Smith, having the necessary certificate, to visit the meetings of Redstone,
Short-Creek, Salem and Springfield Quarters,
and to appoint a few meetings where there are no meetings of Friends.

Reached Westland on Seventh-day evening, 26th, and lodged at the house of George Smith.
Attended meetings on First and Second-days at Pike-Run, Centre and Providence.
The two last were favored meetings, the former not so much so; though, I trust,
it was a season of profit to some.

Third-day.--At Sewickly, which, through Divine mercy, was a good meeting.

Fourth-day.--At a Select Preparative, at Providence, to satisfaction.

Fifth-day.--At Monthly Meeting, in which heavenly good was graciously near,
to the comfort of many.
May the name of the Lord be praised, who alone is worthy.

Sixth-day.--At Select Quarterly Meeting at Redstone; a time of silent suffering.

Seventh-day.--The Quarterly Meeting for Discipline.
The "`unsearchable riches of Christ`" was declared in a
degree of that authority which Truth gives.

First-day, Second Month 3rd.--Again at Redstone, public notice having been given.
It was an open time in testimony.
In the afternoon, at Westland, to satisfaction.

Set out on Second day morning for Salem; the weather being extremely cold.
Reached the neighborhood of Carmel on Third-day evening;
and were at Elk-Run Meeting on Fourth-day forenoon, to satisfaction,
and at Carmel in the afternoon.
The notice not having been sufficiently extended, the meeting was very small,
and not to that relief which was desirable.

Fifth-day.--At Middleton Monthly Meeting; to the peace of my own mind.

Sixth-day.--At Select Quarterly Meeting at Salem; in silent suffering.

Seventh-day.--The Quarterly Meeting for discipline; to the peace of my own mind.

First-day, 10th.--At the same place; in which Truth was in a good degree in dominion.
The saints' rest was opened, I trust, in the "`demonstration of the Spirit.`"
May the Lord's name be praised.

Second and Third days, at Springfield.--O,
the depth of the exercise of my poor soul! on account of the disunity
occasioned by the unsound doctrines introduced among us.
May the Lord in mercy look down upon the low estate of his church; and when,
in his infinite goodness He shall see fit to say,
"`It is enough;`" may He "`turn our captivity as the streams in the south;`" that!
our poor stripped and peeled Society may become settled upon the ancient foundation,
to the glory of our God.
I was enabled in a good degree, to throw off the weight of the exercise resting upon me,
for which I feel thankful.

Fourth-day morning, set off for the settlement of Friends in George County,
and attended a meeting there the next day; a number of the neighbors came in,
and a heavenly meeting we had.

Sixth-day.--Had another meeting at a Friend's house, to the relief of my own mind.

First-day, 17th.--At Kendal; and the next day at Marlborough and Lexington,
in both of which my mind experienced relief.

Third-day.--At Goshen, and Springfield--favored meetings; particularly the former.
The glorious gospel of Christ,
which is the "`power of God unto salvation,`" was opened in
the "`demonstration of the Spirit and of power.`"

Fourth-day.--At Monthly Meeting at Salem, to my own peace.
I was led in a close manner to address parents
on the right training up of their children,
in the nurture and admonition of the Lord;
with warning to them not to indulge them in things
inconsistent with the plainness of our profession.

Having felt my mind drawn towards the inhabitants of the town,
I had a meeting appointed that evening at early candle-light, which was largely attended;
wherein the doctrines of the gospel were opened in the "`demonstration of
the Spirit and of power.`"
May the praise be given to the Lord our God.

At New Garden Monthly Meeting on Fifth-day;
the necessity of recurring to first principles, and to "`stand in the ways, and see,
and ask for the old paths, where is the good way, and walk therein,`" was set forth;
and I was favored to leave in peace.

Sixth-day.--At Sandy-Spring Monthly Meeting, to satis faction;
and at an appointed meeting at Augusta the next day, which was a laborious meeting,
in consequence of a divided state of feeling occasioned by the lack
of a testimony against the unsound writings heretofore alluded to.

First day, 24th.--At Salineville, to satisfaction;
and from there home to our own Quarterly Meeting.

Left home again on Seventh-day morning, the 2nd of Third Month, to finish my visit.
At Mount Pleasant on First day, at the usual hour.
My mind was clothed with mourning on account of the low state of the church;
but found relief in endeavoring to stand in the obedience of
faith in communicating that which appeared to be my duty to do.
In the afternoon, at the Boarding School, to satisfaction.

At Concord; the line of public service ran pretty close,
commencing with the Scripture language,
"`How much do you owe unto your Lord,`" showing how
many blessings and favors we have received of the Lord;
and how, like poor bankrupts, we have nothing to pay with.
That if a due sense of our poverty, and of the much we owe unto our Lord were felt by us,
we should be very careful how we censured one another,
but would rather cast the mantle of charity over the failings of others,
and be disposed to place a favorable construction on
the conduct of our brethren and sisters,
where it would admit of it.

Third-day.--At Short Creek, which was small.
On account of the existence of disunity, many of the members were not there.
But the Lord was with us and comforted our hearts together.
May his great and holy name be praised, says my soul.

Fourth and Fifth-days.--Were at Smithfield, and Cross-Creek, both of which were small,
and that disunity before-mentioned, mournfully to be felt;
but I was favored to find relief in attending to apprehended duty.
Our kind friend, Nathan P. Hall, being our pilot, we rode to his house near Harrisville,
and lodged.
After retiring to bed I slept comfortably until the latter part of the night, when,
on awaking, the love of my heavenly Father filled my heart,
and earnest breathings went forth unto Him on behalf of his afflicted church;
and many of her members were brought one by one to my remembrance,
in prayer for their preservation, as well as for my own soul,
and that of my dear partner in life.
O Lord! you know that, however feeble my efforts have been; and many weaknesses,
and shortcomings attending; yet I have endeavored to serve you "`with a perfect heart,
and with a willing mind.`"
O,
keep me in the low valley of humiliation! and enable me to "`finish my course with joy,
and the ministry which`" has been committed unto me.

Sixth and Seventh-days.--At Harrisville and West Grove, to satisfaction; and First-day,
10th, at Flushing; which was a favored meeting.
Dear Ann Branson had acceptable service.
The line of gospel ministry ran forth freely.

Second-day.--At Freeport and Guernsey; both favored meetings, particularly the latter.
May the praise be ascribed unto the Lord of heaven and earth.

Third-day,
12th.--Returned to our dear families with thankful hearts for
the many favors and blessings conferred upon us,
not only in preserving us as to the outward,
from the dangers of travelling through inclement weather,
but also in strengthening us for the allotted portion of service;
the present being a day in which the dedicated followers of the Lamb have often to
go mourning on their way on account of the disunity which has been occasioned by
the publication of unsound views relative to the doctrines of our Society,
by some under our name.

Found my dear family well: may the name of the Lord be praised, says my soul.

Letter to D. P.:--

Second Month 9th, 1851.

Dear friend D. P.:--Yours of Ninth Month last came to hand a short time since;
and though from one, who is, as to the outward, an entire stranger,
it was none the less acceptable;
the reading of which revived in me a sentiment long entertained;
that as the members of our Society are faithful to their God,
they will speak the same language, wherever located,
having one and the same blessed and glorious cause in view,
even the spreading of the redeemer's kingdom in the
earth in that way which has been opened to us;
and which our Society in its more pure and primitive days; so clearly saw,
and so faithfully adhered to.

Truly I can, in my measure, appreciate your feelings in regard to our beloved Society;
having been favored as we have with evident marks of the goodness and
mercy of our heavenly Father in gathering us to be a people;
who opened to our forefathers the spiritual nature of the gospel dispensation;
and has from age to age watched over,
and preserved his heritage from the snares of the enemy,
which have at times been very cunningly laid to lead us into a
compromise of the plain unsophisticated views of primitive Quakerism;
and to fritter down some of the very important testimonies, which are,
and always have been binding upon us as a people;
every part and parcel of which had their origin in the Truth.

Many who are "`waiting for the consolation of Israel,`"
are often bowed very low because of these things,
whose petitions are put up at times to the Lord of Sabaoth,
that He would by his overruling power remove more and more from our
borders this compromising spirit that loves the world's embraces,
and would eagerly shun the cross of Christ;
that He would clothe us individually with a portion of that living, upright zeal,
which was so conspicuous in the early gathering of our Society;
that the Church might again appear in her ancient beauty.

May we keep to our individual exercises,
looking unto Him who is able by his all-powerful word to control the boisterous elements,
and bring about the purposes of his own will in the purification of his people.
And may we not take comfort in the saying of our holy Redeemer:
"`Shall not God avenge his own elect, which cry day and night unto Him;
I tell you that He will avenge them speedily.`"

There is a heavenly cement that binds together the living
members of that body of which Christ Jesus is the Head;
the savor of a portion of which I felt rejoiced
in believing was conveyed through your quill.
Many waters cannot quench it; distance cannot part asunder,
nor destroy its heavenly virtue upon those who
are of congenial spirits.--united unto Christ,
and brought into that oneness which is of Him.
They truly are as "`epistles written in one another's hearts,
known and read`" in the light of the Lord, to their great comfort;
and under the fresh anointing they can feel for one another, reciprocating the language:
"`The Lord hear you in the day of trouble; the name of the God of Jacob defend you,
send you help from the sanctuary, and strengthen you out of Zion.`"

I thought I felt a freedom to pen a few lines
expressive of my cordial reception of yours,
together with some of my views and feelings respecting the state of our beloved Society,
the best interests of which lie near to our hearts.

Joseph Edgerton.

