== Chapter XIII.

[.chapter-synopsis]
Account of a Visit to Some of the Meetings of Philadelphia Yearly Meeting; Appointed Some Meetings in New England, and in Some of the Seaport Towns.

Having felt my mind drawn to visit in gospel love some
of the meetings of Philadelphia Yearly Meeting,
and also to appoint some meetings in New England, and in some of the seaport towns,
I set off (my dear wife bearing me company to St. Clairsville), the 12th of Fourth Month,
1851.
My dear friend, Ralph Cowgill, who expected to accompany me,
was taken with apoplexy on the morning of the day previous to setting off,
and died at nine the same evening, which was a great trial to me.
I spent some time with the family next morning before meeting,
and then took a solemn leave of my dear wife and daughter, and several other Friends,
and proceeded to Philadelphia.
I attended the Yearly Meeting, which was a favored season, and closed on Sixth-day,
the 25th. Went next day to see our dear friend, Christopher Healy, who was very low,
but green and bright in spirit, saying: "`I feel no condemnation,
but am waiting,--patiently waiting until my change comes.`"
A great comfort to be with him.
Attended the Falls Meeting on First day, to satisfaction,
and returned to the city on Second-day.
Attended Monthly Meeting for the Northern District; also the Southern,
and that of Arch street, as they came in course, to the relief and peace of my mind.

On Sixth-day, the 2nd of Fifth Month, I left for New England,
in company with my dear friend, Moses Bailey, of Bradford Monthly Meeting, Pa,
who had given up to the service; and we arrived at Westerly, Rhode Island,
the next morning.

First-day.--Attended the meeting at Hopkinton, which was a favored meeting.
A severe storm coming on, we were detained at the house of John Wilbur.

Third-day, 6th.--At South Kingston;
strength was afforded to discharge the portion of service required.
The word of encouragement flowed to the members of our religious
Society to be faithful in keeping up their religious meetings.
My soul has mourned over the devastating effects of a separating spirit,
which has carried off very many from the ancient doctrines of our religious Society;
in many places there being but few left.

Next, attended meetings at Warwick, North-Providence and Newport;
all of which were seasons of favor.

Seventh-day, 10th.--At Fall River; the forepart of which was rather dull and heavy;
but in the Lord's time, Truth arose into a good degree of dominion.
"`Praise the Lord, oh, my soul! and bow in humble prostration before Him;
for He lifts the beggar as from the dunghill,
and puts the song which is ever new into the mouths of his dependent ones.`"

Extract of a letter to E. B., written at this time:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Fall River, Mass., Fifth Month 10th, 1851.

[.salutation]
Dear friend, E. B.:

In the fresh feeling of that near unity,
which has long been felt between us, I salute you and your beloved M.,
and may inform you that I am well, and, through Divine mercy,
have been favored to get along to my own peace thus far.

The little remnant of sound Friends here are very glad to see us,
to whom the language of encouragement has several times flowed freely,
with the exhortation of our Divine Master: "`In your patience possess your souls.`"
May I be kept in the line of Divine appointment; and truly, it seems to me,
that my soul has cause to trust in, and rely upon the good Shepherd,
who has not been lacking in his merciful care in going before,
nor in qualifying for the service He requires.
I desire, on the one hand, not to hurry on too fast; and on the other,
not to stay longer than is right.

I often think of my dear family and friends in our little meeting at home,
with desires for their preservation and growth in the Truth;
believing that the truly exercised burden-bearers feel
the weight of the exercise to be heavy upon them,
their hands almost ready to hang down, and their knees to smite together;
but as they keep near unto Him, in whom is everlasting strength,
being willing to suffer with the seed of life,
which is under suffering in the hearts of many,
even as a "`cart loaded with sheaves,`" they will be permitted, in the Lord's time,
to reign with Him.
Oh, I feel very tenderly for these in my own little meeting at home.
May the Lord, in his mercy, strengthen them by his power in their inner man,
and so clothe them by his Spirit, both in meeting and out of meeting,
that they may keep their places in the authority of Truth;
being as "`Saviors upon Mount Zion,
to judge the mount of Esau,`" both in themselves and in others.

In the fellowship of the Gospel I conclude, with love to yourself,
your dear wife and children, and remain,

[.signed-section-closing]
Your friend in the Truth,

[.signed-section-signature]
Joseph Edgerton.

--

First-day, 11th.--At Westport, and North Dartmouth, to satisfaction.
Then to New Bedford, and had an appointed meeting with the few Friends there,
which was a season of instruction to many;
divine life being felt to spread over the meeting.

On first coming into the city, my mind was turned in gospel love towards the seamen,
which, being opened to my companion, and Friends, was united with,
and a meeting appointed on Third-day evening.
My mind was brought very low on account thereof,
but was enabled to cast my whole care upon the Lord,
with earnest breathings unto Him that He would be
pleased to keep me in the hollow of his holy hand,
and not permit his good cause to suffer by me.
The meeting assembled at the time proposed,
and though not so many of those of a seafaring life as was desirable, it was a quiet,
orderly meeting.
After a considerable time of silence, I arose with these words, "`This is life eternal,
that they might know you, the only true God,
and Jesus Christ whom you have sent;`" pointing out the way
whereby alone a knowledge of God and of Christ can be obtained,
even by attention to his spirit in the heart,
which will ever lead duly to appreciate the
benefit of what has been done for us without us,
as well as to submit to the working of his Spirit within us;
and thus know Him to be our complete Savior and Redeemer.
Was favoured to leave peacefully.

Extract of a letter to his wife, written at this place:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
New Bedford, Fifth Month 13th, 1851.

[.salutation]
My dear Wife:

I may truly say that I have been confirmed
abundantly in the sentiment that I have long entertained,
that the part of Society in this country,
termed the "`smaller body,`" is owned by the Head of the church.
We have been with them greatly to our comfort in several instances.
On my coming among them I greatly desired to be favored to feel where they were,
and whether they were owned by my divine Master;
and I have been well satisfied in that matter, and may say with gratitude of heart;
thus far I have been helped to get along to my own peace,
though I have had largely to partake of the cup of suffering;
but have been made willing to suffer with our dear Lord and Master.
What a pity that so many of the members of our beloved Society
should join in confederacy with that spirit which for years
has been striving to modify our high and holy profession.

[.signed-section-signature]
Joseph Edgerton.

--

Fourth-day, 14th.--At South Dartmouth.
Divine mercy was extended, to the tendering of many hearts.
Set out for Nantucket, and touched at the Elizabeth Islands, and Martha's Vineyard,
arriving safely at Peleg Mitchell's on Sixth-day evening.
Had a meeting at Siasconset--a fishing town on the Island; which,
through the Lord's goodness, was a favored season.
May He have the praise of his own works.
Bow low, O my soul, before Him in humble trust, that when He puts forth into service,
He will be near, and carry through to his own praise!

On First-day forenoon, the meeting was large,
and through the goodness of the Lord was a refreshing season.
That in the afternoon, though smaller, was a good meeting.
In both the Lord was near,
giving ability to open the doctrines of the everlasting gospel,
to the relief and peace of my own mind.
In the evening attended a funeral of a person who had been a member of our Society;
and during the meeting at the house,
the scripture language arose with an impression to communicate it,
"`No man has power over the spirit, to retain the spirit;
neither has he power in the day of death; and there is no discharge in that war.`"
Showing the great importance of accepting the gracious invitations of the Lord,
which are heard in the secret of the soul: "`My son give me your heart;
my daughter give me your heart;`" that we might know
Him to prepare us for the solemn period of death.

Feeling clear of the Island, we took a solemn leave of Friends, in great tenderness,
and embarked on a steamer on Second-day morning, the 19th,
and had a very pleasant passage, landing in the afternoon at New Bedford.
Took the rail-cars the next day for North Berwick, and had a meeting there,
to satisfaction.
Had a meeting at the Great Falls, which was an exercising time;
but was favored to throw off the burden resting upon me,
and felt a humble hope that the cause of Truth did not suffer.

Sixth-day, 23rd.--Called upon several Friends,
and my mind was led into deep sympathy with the burden-bearers,
and the word of encouragement flowed freely to them during several opportunities.
May the Lord keep his own little dependent children in his holy enclosure,
and make them "`joyful in his house of prayer, and fruitful in his fields of offering.`"

Seventh-day.--At Salem, to satisfaction.
Had an evening meeting for the sailors, which was a season of instruction.

First-day, 25th--At Lynn, in the forenoon.
The meeting, though small, was a season of Divine favor.
May my soul bless and praise the Lord for his many mercies.
In the afternoon had a meeting in Boston among the sailors, which was large,
and owned by our Divine Master.
The doctrines of the gospel were opened, I trust,
in the "`demonstration of the Spirit,`" to the comfort of many,
and proved a solemn meeting.
"`Return unto your rest, oh! my soul; for the Lord has dealt bountifully with you!`"

In the evening,
walked out into what is called "`Boston Commons,`"
where several of our dear Friends suffered martyrdom,
and contrasted, in my own mind, the great change of feeling since that day.
May the Lord, who has the hearts of all men in his hands,
and can turn them at his pleasure, carry on his great and glorious work,
until all cruelty and oppression, all war and bloodshed, may be done away,
and the peaceable reign of the Messiah be more and more conspicuously ushered in,
that the ancient prophecy may be fulfilled:
"`Nothing shall hurt or destroy in all my holy mountain.`"

Second-day morning.--Took the cars for Fall River, and had a meeting at Little Compton,
which was an open, refreshing opportunity.
Went back to Fall River, to the house of our kind Friend, Israel Buffinton.
Many Friends coming in, we had a cementing parting opportunity.

Third-day morning.--Took boat to Providence, and the cars to Westerly.
Had a meeting there in the evening, which, through Divine mercy,
was an instructive season.
May the Lord have the praise of his own work.
Took leave of Friends there, and went on the cars to Stonington,
where we took boat for New York, and had a very pleasant passage,
but for one circumstance.
Our steamer accident ally ran against a sloop, and rendered it unable to make its way.
Our captain gave orders for it to be lashed to our steamer, to tow it into New York,
which was accordingly done, and the men--except one--taken on board our vessel;
but the sloop soon filled with water, and went to the bottom.
A boat was hoisted out immediately and picked up the man left on the sloop.
Oh, the hardships and privations of a sea-faring life.

Arrived at New York about 7 o'clock, and took the cars at Jersey City for Rahway,
where we arrived in time to attend their midweek meeting; wherein, through Divine mercy,
strength was afforded to discharge the portion of service allotted;
setting forth the beauty and excellency of Divine worship,
and that those who are inwardly gathered unto Christ, and to his Spirit,
are at times favored to arise with the beloved disciple of our Lord,
and "`measure the temple of God, and them that worship therein,`" ever remembering,
that the court that is without is not to be measured, but left unto the Gentiles.

Sixth-day.--At a meeting at Plainfield, which was a season of Divine favor.
My dear friend, Moses Bailey, with whom I have travelled in great unity,
now feeling released, returned home, and my friend and fellow-laborer, Henry Wood,
concluded to take his place.

Seventh-day.--Went to Shrewsbury by way of New York, taking a steamboat from there,
and arrived in the evening.

First-day, Sixth Month 1st.--Were at meeting there;
and my mind was clothed with mourning, on account of the low state of the Church.
Several not members of our Society, came in, and the doctrines of the gospel were opened,
I trust, in a good degree of its own authority.
I was favored to leave in peace.

At Crosswicks Monthly Meeting on Third-day, to satisfaction;
and at Trenton in the evening, which was a time of renewed favor,
wherein Truth reigned over all, Oh,
that the praise may be returned unto Him to whom it is due.

Fourth-day.--At Springfield Monthly Meeting, held at Mansfield.
The Truth was in a good degree in dominion,
strength and utterance being given to declare the "`unsearchable riches of
Christ,`" in a degree of the "`demonstration of the Spirit and of power.`"
At Burlington in the evening; a low, trying time.
My soul mourns over the devastating effects of the
disunity occasioned by the spread of unsound doctrines.

Fifth-day.--At Evesham Monthly Meeting; which was a season of refreshment to many.

Sixth-day.--At Rancocus in the forenoon; wherein Truth reigned over all.
May the Lord have the praise of his own works.
In the evening at Mount Holly, which was an instructive opportunity.

Seventh-day.--At Upper Evesham Monthly Meeting, in which Truth reigned over all,
under the influence of which, the gospel was preached to the instruction of many.

May the Lord be praised, and my poor soul kept in the dust, for He alone has done it.

[.embedded-content-document.letter]
--

[.letter-heading]
Extract of a Letter to His Family.

[.signed-section-context-open]
New Jersey, Sixth Month 7th, 1842.

[.salutation]
My beloved Wife:

Yours of the 30th came to hand yesterday, which was truly acceptable.
I was also glad to have a few lines from the dear children.
I may inform you that I am well;
and have been thus favored ever since leaving my dear home, except some slight colds,
which I esteem a great favor among the many which are bestowed.

O! that I may never forget to return thanks therefor unto Him,
who has in his abundant mercy been near,
not only to bear up in seasons of deep baptism and trial,
but to give strength to perform his blessed will.
The former has been my portion in large degree;
but blessed be his name he has given a supply of that excellent gift--patience;
and thereby the bitter cups have been made more than tolerable.
And as respects the latter, I can say,
I have been favored to get along to the relief and peace of my mind; and what a favor;
when wading along under deep exercise; being pressed out of measure,
and beyond strength almost; to be enabled to throw off the burden where it belongs;
whether the people will hear, or forbear.
O! that I may be kept inward with the Lord; keeping a single eye unto Him,
that nothing may be omitted that ought to be done,
nor anything done which his holy Spirit does not lead into.
I am more and more confirmed in the belief that if we are inward,
watchful and fervent enough, we shall not be left to ourselves,
but an evidence will be granted of any intimation of duty required.

[.signed-section-closing]
I remain as ever yours,

[.signed-section-signature]
Joseph Edgerton.

--

At Easton on Seventh-day afternoon,
where the language of encouragement flowed freely to the exercised burden-bearers,
as well as a tender invitation to the unconcerned to enter into exercise,
and work out their salvation with fear and trembling before God.

First-day 8th.--At Cropwell in the forenoon:
the meeting was favored with the overshadowing wing of ancient goodness;
under which heavenly covering the burden-bearers were encouraged to stand as with
their feet firm in the bottom of Jordan until the people clean pass over;
that the service designed through them to the church might be realized;
and that they might experience the end of their faith, even the salvation of their souls.
The careless were tenderly invited to gather to, and obey God's gift in their hearts,
that they might be enabled to do their day's work in the day time.

In the afternoon, at Haddonfield;
many not of our Society coming in the meeting was large,
and that goodness which is both ancient and new was felt to be near,
solemnizing many hearts,
and affording ability to declare the "`unsearchable riches of Christ.`"
Let my soul forever bow before you, O Lord! in deep prostration:
you know the deeps through which it has been my lot to pass;
make me willing to bear them; yes,
even to rejoice in being accounted worthy to suffer for your great name's sake;
that I may more and more arrive at the situation in which I can adopt the language,
"`Not my will, O Lord, but yours be done.`"

Second-day.--At Haddonfield Monthly Meeting held at Newtown,
which was a season of divine favor.

Third-day.--At Chester Monthly Meeting; Truth reigned over all.
The language of inspiration through the Lord's servant, was opened and uttered:
"`For Zion's sake I will not hold my peace;
and for Jerusalem's sake I will not rest until the light thereof go forth as brightness,
and the salvation thereof as a lamp that burns.`"
The language of tender solicitude flowed freely to different classes present.

Had a satisfactory meeting at Westfield in the afternoon,
which was a season of renewed visitation to some.
The faith and faithfulness of Abraham was adverted to in that memorable
instance of his going to Mount Moriah to perform the command of the Lord;
who again appeared unto him in the solemn and welcome language,
"`Lay not your hand upon the lad;`" and turning him about,
saw a ram caught in the thicket, and he took it and offered it instead of his son.

Next attended Haddonfield Quarterly Meeting held at Evesham, which was a season of favor.

Sixth-day.--At Woodbury and Woodstown.
The former was a season of favor;
the way of life and salvation was opened in the demonstration of the Spirit.
The latter was a heavy, trying meeting, particularly the forepart of it.
There being many not of our Society present, for whose sakes, it appeared,
the spring of life was a little opened;
and some communication tending to stir up to faithfulness
while the day of visitation is lengthened out.

Seventh-day.--At Salem; which, through the Lord's mercy was a heavenly meeting.
May He be praised.

First-day, 10th.--At Greenwich--an open, good time.

Second-day.--Rode to Leeds-point, on the sea-shore; and had a meeting there the next day,
which, though small, was a favored season.

Fourth-day.--At Tuckerton and Barnegat, to a good degree of satisfaction,
which closes my prospect in New Jersey.

Attended the Meeting for Sufferings in Philadelphia on Sixth-day;
and feeling my mind drawn towards the in habitants of the city,
particularly those in a sea-faring life;
I felt most easy to acquaint my friends therewith; which being united with,
way opened to hold a meeting on First-day afternoon, 22nd;
to which many of that class came;
and through divine mercy it was a solid instructive season.
Set out the same evening for home, and arrived at the house of our son-in-law,
John Thomasson on Third-day evening, 24th;
where I met my beloved wife to our mutual joy and rejoicing.
Arrived at my own home the next day; O, may my soul bless and praise the name of the Lord!
