== Chapter XV.

[.chapter-synopsis]
Testimony of Somerset Monthly Meeting. At Somerset Monthly Meeting, 20th of Fourth Month, 1871.

A Testimony concerning our late beloved friend Joseph Edgerton,
was read to our edification; which is directed to be forwarded to the Quarterly Meeting.

[.signed-section-signature]
James Edgerton and Elizabeth Livezey,  Clerks

[.signed-section-context-close]
At Stillwater Quarterly Meeting, 31st of Fifth Month, 1871.

A Testimony concerning our late beloved friend Joseph Edgerton--
approved by Somerset Monthly Meeting--was produced and read,
and directed to the Meeting for Sufferings.

[.signed-section-signature]
Asa Garretson, and Hannah Tatum, Clerks

=== Testimony

It is instructive and encouraging to those who are passing through
the trials and conflicts incident to a life of self-denial,
and the daily cross; to have held up to their view the upright walk,
and consistent example of those who have trodden a similar path before them;
and who now rest from their labors, and their works do follow them.

We believe it is due to survivors, and succeeding generations,
thus to commemorate the goodness and mercy of our God
in his dealings with his dependent children,
who have endeavored to follow Him in the way of his requirings,
if haply others may be induced to give in their names to serve the Lord,
and to come forward under the operation of his humbling and preparing power;
and be enabled thereby to dedicate their time and talents to the promotion
of his great and glorious cause of truth and righteousness in the earth.

This, our dear friend, was born on the 10th day of the Ninth Month, 1797,
in Wayne County, North Carolina.
His parents, James and Sarah Edgerton, were members of our religious Society;
and concerned to train up their children as consistent Friends: and their conscientious,
watchful care appears to have been blessed to them.

In a memorandum dated Fourth Month 1st, 1836, he says:
"`The remembrance of their pious and watchful care over their numerous family,
is fresh with me at this day;
frequently calling them together to wait upon God in silence for his holy help; and this,
though at times in great weakness, as I well remember hearing my dear father say,
was blessed to us.`"

Very little account is left us of his early years;
but there is good ground to believe that he was in a good degree,
mercifully preserved from the many evils which abound in the world,
and strengthened to dedicate the prime of his life to
the cause and service of his dear redeemer.

In the year 1818, he was married to Charity, daughter of John and Miriam Doudna,
and settled within the, limits of this meeting,
where he continued to reside until a few months before his decease.
In this connexion he found a true help-mate in his varied and deep baptisms,
who gave him up freely to the service to which he was called.

In the twenty-fourth year of his age, he first appeared as a minister;
but being naturally of a very diffident disposition, he endured many conflicts,
the enemy seeking to cast down, and thereby destroy the good work thus begun;
and for several years he struggled on, under much discouragement.
But He who is all-sufficient for his own work,
and sees and knows the secrets of all hearts,
saw that his disobedience was through weakness and fear, instead of willfulness,
and eventually made "`the depths of the sea a way,`" and enabled him to
overcome and rise above the discouragements and suggestions of the destroyer,
and come forth in the work whereunto he was called.

He was acknowledged a minister by Somerset Monthly Meeting in the year 1833,
and travelled extensively in that capacity a great part
of the time during several subsequent years;
being drawn in gospel love to labor in all the Yearly Meetings on this continent,
and was frequently engaged under the same constraining influence to visit
meetings and families within the compass of his own Yearly Meeting.

Thus devoted to the cause and service of his divine Master,
he was enabled to leave all and go forth,
not doubting but He who had graciously promised to take care of those left behind,
would be near to perform.
But when a release was granted,
and he permitted to return from the field of labor abroad,
and share in the domestic duties, he was diligent in business,
"`laboring to provide things honest in the sight of all men.`"

He was an affectionate husband,
a tender and indulgent father towards those objects of
tender solicitude committed to his trust,
earnestly desiring, that as they grew in years,
they might experience a growth in grace--might "`take root downward,
and bring forth fruit upward.`"

The love and unity that should subsist among brethren, lay very near his heart,
and he was frequently led to rehearse in the hearing of his friends,
the language of the Psalmist:
"`Behold how good and how pleasant it is for brethren to dwell
together in unity! it is like the precious ointment upon the head,
that ran down upon the beard, even Aaron's beard;
that went down to the skirts of his garments; as the dew of Hermon,
and as the dew that descended upon the mountains of Zion;
for there the Lord commanded the blessing, even life forevermore.`"

His countenance in meetings manifested a weighty concern of mind for the arising of
the well-spring of life in those assembled for the solemn purpose of Divine worship.
He was valiant for the Truth;
standing forth in unflinching support of the doctrines and
testimonies as promulgated to the world by our worthy predecessors.
The cleansing, purifying power of the Lord Jesus,
in his inward and spiritual appearance in the heart,
he was frequently led to bring to view,
and to bless and magnify the name of the Lord for this unspeakable gift,
as "`a crown of glory and a diadem of beauty unto the residue of his
people,`" as a fundamental doctrine of the Christian church.

In the Twelfth Month of 1855, in the ordering of divine Providence,
his beloved partner in life was removed from works to rewards;
and though this was felt by him to be an afflictive bereavement,
yet the firm belief that she had exchanged a scene of
suffering and sorrow for one of joy and peace,
sweetened the bitter cup, and he was mercifully sustained at that trying time.

In the Fourth Month, 1857, he was married to Anna M. Brantingham;
and in the Fourth Month, 1865, under an apprehension of duty,
they removed to Coal Creek Monthly Meeting, Iowa.
But his sojourn among his friends there was of short duration;
yet he was frequently and fervently engaged on
their behalf during the few months allotted him.

He was taken ill about the 17th of Tenth Month, 1865;
but for several days no serious apprehensions were entertained as to the result.
The symptoms becoming more alarming, medical advice was obtained;
but the means used did not arrest the disease.
Observing the anxiety of his wife, he said: "`I want you to be comforted.
I have not seen that this is to be my last illness;
but desire to rest in the will of the Lord.`"

On Fourth-day morning, he thought he was better; but the night following,
the symptoms were more unfavorable.
On seeing the concern manifested by those around him, he said: "`Be patient,
and trust in Divine mercy.`"
During his illness he several times said: "`My dear,
we are under the protecting care of a merciful Caretaker,
who is worthy to be trusted in.`"

Fifth-day, he was much worse, and suffered exceedingly;
but not a murmur escaped his lips,
though evident to those about him that his bodily suffering was extreme;
yet the serenity and composure of his countenance evinced that
his mind was centred on heaven and heavenly things.

On Sixth-day night, being asked how he was, he answered: "`Pretty comfortable.`"
It was rejoined, "`You are suffering in body, but comfortable in mind.`"
He replied, "`Yes; I never felt more comfortable in my life.`"

On Seventh-day; the physician informed him that his recovery was considered doubtful.
He calmly replied, "`I can say, the will of the Lord be done.`"
On a letter being written to some of his absent children,
he was asked whether he had anything to say to them.
He answered, "`Not now.
My children have not to wait till this late period to know my mind concerning them.`"
Addressing his wife, he said, "`I want you to let your dependence be on the Lord.
I feel for you all that a beloved husband can feel.`"
He requested the seventh chapter of Luke read,
which relates the circumstance of the woman washing the Savior's feet with tears,
and wiping them with the hairs of her head.
He said, "`Oh,
He is a dear Savior! one that we ought to love and serve all the days of our lives.
We cannot devote too much of our time or our faculties to his service.`"

His concern for his children and friends, was that they might be faithful,
and let none of the precious testimonies of this Society fall to the ground; remarking:
"`There are many manifesting so little concern for themselves and their children.`"

First-day morning, he repeatedly enquired the time of day; and said,
"`I do not want anyone to stay from meeting that can go.
We will have our meeting here.`"
After the reading of a psalm, he addressed such of his children as were present,
in a very impressive manner, saying, "`I leave it as my dying testimony;
and I wish to impress it upon you,
not to let any of the doctrines and testimonies that
were committed to this people in the beginning,
fall to the ground.
I want you to be plain in your houses; plain in your dress, and plain in your diet;
be watchful over your dear children;
bring them up in the nurture and admonition of the Lord.
It is the duty of parents to pray for their children:
and it is the duty of children to pray for their parents: 'pray without ceasing,
and in everything give thanks:' seek to know from where all true prayer comes,
for what comes from God will draw to God.
When you rise in the morning,
turn your minds inward to the Lord before entering upon the duties of the day.
I want you to be as way-marks to others.`"

To some young people who were present,
he had considerable to say in regard to their dress, conduct, and conversation;
and several times expressed the desire that our lives
and conversation might be such as to bring glory to God.
At one time he repeated the language of the apostle,
"`Who shall separate us from the love of Christ,`" etc.--and again,
"`Trust in the Lord forever, for in the Lord Jehovah is everlasting strength.`"

He travailed in spirit for the welfare of his friends while in health,
and in sickness it was not abated;
still assuring them that if they were engaged to put their trust in Divine Mercy,
they would witness the "`everlasting arms`" to be round about,
and "`underneath,`" for their support and preservation.

The words, "`Glory!
Glory!
Glory! come, Lord Jesus, come,`" were among the last that were distinctly understood;
and soon after passed away like one falling into a sweet sleep,
on the 30th of Tenth Month, 1865;
leaving his friends the consoling belief that he has
entered into the mansions of everlasting rest and peace.
