== Chapter I.

[.chapter-synopsis]
* Early Life and Labors in the Ministry.

It has been on my mind to leave some account of the gracious
dealings of my Heavenly Father with me from my youth,
which have been many, and eminently marked with his unbounded love towards me,
for my gathering into the fold of everlasting rest.

I was born the 10th day of the Ninth Month, 1797, in Wayne County, North Carolina,
of pious parents, members of our religious Society, James and Sarah Edgerton,
whose godly care over their numerous family was blest to us.
My father filled the station of an elder for
many years to the satisfaction of his friends.
He was a loving husband and a tender father;
and his heart and house were ever open to receive the
messengers of the glad tidings of the gospel of peace,
giving up cheerfully divers times to accompany
such in the work whereunto they were called.

In the year 1805, my father removed with his family to the State of Ohio,
and settled in Belmont County, which, being a new country,
many privations and hardships were our portion.
Religious meetings were remote, but through all,
a consistent example was maintained in the
attendance of both First and week-day meetings.

In the fore part of the Twelfth Month, 1824, he was taken ill of what proved to be asthma.
He uttered many sweet and heavenly expressions, saying at one time,
"`Tell all my dear friends who may inquire after me, that I die in peace.`"
Thus he continued in a lively frame of mind until the 21st of First Month, 1825,
when he quietly departed this life in the 61st year of his age,
leaving the solemn impression:
"`Blessed are the dead which die in the Lord from henceforth; yea, saith the Spirit,
that they may rest from their labors, and their works do follow them.`"

But to return to my own account.
Being sheltered by pious parental care,
I was preserved from many of the follies and vanities
which young people are too frequently drawn into,
and was early visited by the day-spring from on high.
Once as I was at my innocent play,
my mind was secretly turned to meditate upon divers of the patriarchs, such as Abraham,
Isaac and Jacob, how the Lord blessed them;
with the impression that if I would be good and serve Him, I should be his servant;
accompanied by a desire that He who is thus gracious to the children of men,
might by his watchful care over me keep me from evil.

The families of Friends where my father settled were scattered, and the meetings,
of course, at a distance from some of the members, being five miles from us.
We generally attended twice a week, and I became attached to walking,
as I thought it better suited to silent meditation;
and many sweet seasons I had in going and returning from them.
Convinced I am,
that if our beloved young people were more concerned to
retire into the closet of their own hearts,
they would experience preservation from so close
an attachment to the vanities of the world;
and the good hand of Israel's Shepherd would he turned upon them,
preparing them for the service of this day,
and their final acceptance with Him in the world to come.

Thus I grew up, and though, as I have before stated,
I was preserved from many of the follies and vanities incident to youth,
yet many times I deviated from the monitions of that
witness for God which cannot be removed into a corner,
one of which was as follows: Being questioned concerning one of my elder brothers,
relative to the subject of marriage, I, in order to screen him, answered in the negative,
which was a deviation from the truth, and occasioned bitter remorse and condemnation.
I have often been struck when I have observed in others
a similar deviation in regard to this subject,
and I have thought it would be much better to withhold
entirely than to deviate from the truth with a view to secrecy;
He with whom we have to do being always present,
sees and weighs our words and actions as well as thoughts.
O that the children of men would receive the reproofs of instruction, and be wise,
redeeming the time, because the days are evil,
that their peace might be as a river and their righteousness as a mighty stream.

I was early impressed with the danger of associating with persons of light,
irregular conduct, and felt the pure witness rise against joining in company with them.
I was, however, preserved from much desire therefor;
having felt the sweet incomes of Divine love to my soul,
quietness and retirement were very desirable to me;
and at the presentation of danger of falling into such company,
I was brought into much exercise, crying unto the Lord for preservation;
and He was pleased by his secret hand to guide and guard my youthful steps.
My heart is at this time filled with thanksgiving and praise
unto Him who was pleased to care for me in early life,
bringing me to see and understand his blessed will concerning me,
and has been pleased to carry on the work in the way that He has chosen,
even in the way of the cross;
bringing me to see my lost and undone condition without Him;
that it was through his everlasting love to my soul that He was pleased to
visit me in the waste howling wilderness of my natural state,
and draw me to his Son, our Lord Jesus Christ, who is the only way to eternal glory.
My soul bows in awful reverence before Him,
because of his loving kindness in leading me about and
instructing me in the path of self-denial.
May He be pleased to carry on his work until all the dross, the tin,
and even the reprobate silver may be removed,
together with the strong will of the creature,
that is so much opposed to the government of Immanuel;
that He may subdue all things unto himself, even every thought,
to that obedience wherein He comes to rule and reign over all.

I was preserved in a good degree in plainness, not having, to my recollection,
deviated from plain Scripture language at any time; and as to deportment and apparel,
I was not suffered to deviate far from the simplicity of the truth as it is in Jesus.
And although I often found myself very deficient in
faithfully observing the monitions of the witness for God,
yet He was pleased to pass by my disobedience and renew his favors to me,
causing his peace to flow into my heart.
Often on lying down at night his love has distilled into my quiet habitation,
and strength has been given through the pouring
forth of the spirit of grace and of supplication,
to give thanks for past and present favors, and to intercede for a continuance thereof,
before closing my eyes for sleep.

In the 19th year of my age, the Lord was pleased to show me in a meeting at Captina,
where I belonged,
that if I were faithful I should have to declare to others what He had done for my soul,
at which I was broken into tenderness even to tears, feeling, indeed,
as a child for that great work.
In the 21st year of my age, I was married to Charity, daughter of John and Miriam Doudna,
an amiable and pious young woman, and we settled at Ridge, near Barnesville,
Belmont County, Ohio.

Being in limited circumstances,
we found it necessary to labor diligently for sustenance for ourselves and family;
nevertheless a desire prevailed at times that I might not suffer even
the things we stood in need of to gain the first place in my seeking,
fully believing in the promise of our Holy Redeemer,
"`Seek first the kingdom of God and his righteousness,
and all these things shall be added unto you.`"

I was often brought to feel something of what I had felt some
years before in regard to appearing in the ministry,
but nature shrunk from it time after time,
even after the impression was so clear that there could be no excuse;
yet how did I plead to be excused until his judgments, in deep distress of mind,
were poured upon me,
and the creature was brought down to a willingness to obey his holy requiring,
which was in the 24th year of my age, in a meeting at Ridge,
where I first opened my mouth in a few words, beginning with the promise of the Almighty;
"`I will abundantly bless the provision of Zion;
I will satisfy her poor with bread,`" with some other words.
I sat down in great sweetness of mind; but afterwards I gave way to discouragement,
for Satan, who is ever ready to frustrate the work of Divine grace in the heart,
infused various reasonings, trying to persuade me that I was mistaken,
and brought to view divers instances of some who had be gun and run well for a time,
and then made shipwreck of faith and a good conscience.
Thus I struggled on for many years, while divers faithful friends were concerned for me.

In this interval I was placed in the station of an Elder,
which caused very humbling feelings; sensible at the same time that if I were faithful,
my service would be in a very different line.
Still continuing under great exercise of mind,
I often promised to give up if ever the impression was so clear again;
but when the time came I found myself in the same condition.
At one time my disobedience coming very heavy upon me,
my mind was impressed with the belief that my day of visitation was nearly over.
Yet He who is marvellous in his dealings to the children of men,
saw that my thus holding back was more from a fear of running before my guide,
and was pleased to pardon my disobedience and restore comfort to me.
Thus the Lord dealt with me according to his wonted goodness,
and gave me strength to come forth again in a few words,
seven or eight years after my first appearance;
and the peace I was permitted to feel surpassed anything I had ever experienced,
the savor of which continued with me for some days, attended with that sweet language,
"`Because thou hast been faithful in this thing, in blessing I will bless thee,
and in multiplying I will multiply thee.`"
May my spirit ever bow in the lowest prostration before Him who has
plucked my feet out of the mire and clay and set them on a rock,
and, I trust, hath in degree established my goings.
Everlasting praises to his great name, now, hence forth and forevermore.

My family having increased,
and being frequently on appointments in the services of Society,
with the prospect of being called from home on account of my own exercises,
brought me at times under much thoughtfulness about my dear family.

At one time I well remember, when alone, my mind being turned inward,
the overshadowing wing of Divine Power was spread over me,
and this language intelligibly impressed my mind:
"`If thou wilt give up to follow my holy leadings,
I will be with and bless thee and take care of thy dear wife and children in thy
absence;`" the sense of which heavenly canopy is fresh with me at this time.
May I never forget his loving kindness to me in various ways.

Thus I was through the Lord's unmerited mercy enabled
to make some advancement in the way of self-denial,
in being accounted a fool for the sake of my Lord and Master;
and yet many discouragements were thrown in the way.
But through Divine Mercy I was helped to overcome them,
being satisfied that He who giveth gifts unto men, will, if waited upon and followed,
enable to come up in the occupancy thereof to the praise of his own eternal Name.
May I, together with all who apprehend themselves called to speak in the great Name,
be careful to speak in the openings of divine life,
wherein our movements will be in his power;
thus preservation will be experienced from mistaking the forward
activity of the creature for the putting forth of the good Shepherd.
The eye of the mind being single unto Him, our vision will be clear,
and ability given to move on step by step, to the honor of his great and eternal Name,
casting every crown at his feet, sensible that all power, majesty,
might and dominion are due unto Him who hath all power in heaven and in earth;
that indeed we have this treasure in earthen vessels,
that the excellency of the power may be of God, and not of us.
Here all self-exaltation is shunned as deadly poison, and the creature laid in the dust,
and the Lord alone exalted.

I attended to the service required of me in different ways;
it being a time of great distress in our Society,
many having gone off in the erroneous doctrines of Elias Hicks; it was much shaken,
and various appointments were made by the Yearly, Quarterly and Monthly Meetings,
to endeavor to strengthen the things that remain that were ready to die.
I also several times visited divers of the Quarterly Meetings under a concern of my own,
with the concurrence of my friends at home,
to the peace of my own mind and to the satisfaction of Friends.

He was recorded a minister in the Fifth Month, 1833, near which time,
under date Tenth Month 27th, he writes:
"`A minister of the Gospel should be entirely given up to serve his Lord and Master,
although it may be trying to flesh and blood.
O, may I be preserved in the hollow of his holy hand,
attentively waiting for the unfolding of his Divine will,
that I may experience a being brought into his banqueting house,
where his banner over me may be love.
And as this is vouchsafed,
whether it may be the Lord's will that I should remain pretty much at home,
and take part with my dear wife in training up a numerous family,
or whether He may send me to any part of his heritage, I am content,
so that I may through dedication of heart be permitted to finish my course with joy,
and the ministry that may have been received of the Lord Jesus.`"
