== Chapter X.

[.chapter-synopsis]
* Account of a visit to the families of Chesterfield Monthly Meeting, and the meetings of Red-Stone Quarter.

Having felt my mind drawn to visit in the love of the gospel,
the families of Chesterfield Monthly Meeting, and the meetings of Red-stone Quarter,
and having the concurrence of our Monthly Meeting therein,
I left my dear family under great discouragement of mind;
but He whose compassions fail not, condescended in mercy to bear up my tribulated spirit.
My valued friend Edmund Bailey bearing me company, we reached Chesterfield,
and attended the Monthly Meeting there, the 15th of Fourth Month, 1848.
It was a painful, trying meeting; and silent as to ministry.

In looking towards the accomplishment of the
awfully solemn duty of going from house to house;
it appeared to me to be my place to proceed without any pilot.
This was owing to party feeling,
and a disposition for too much talking one about another;
and we found best help to be near from place to place,
and ability afforded many times to dip into the states of families and individuals,
to our great humiliation, and, I trust, it was a renewed visitation to many.
May praise and thanksgiving be returned unto Him who gave the ability,
to whom alone it is due.
We visited one hundred and forty families in less than two weeks,
and returned to my dear family on the 29th instant, in peace;
though much fatigued and worn down, both in body and mind.

First-day, Fifth Month 14th, 1848.--In our meeting at Ridge,
the fore-part was rather dull and heavy; but life sprang up,
and strength was given to labor in some degree of that
ability which is from Him who is the Head of his church,
setting forth the necessity of bearing the cross of Christ,
that we might inherit the crown: and the meeting ended well.
May I be preserved in the path of allotted duty,
being willing to endure the refining baptisms that may be permitted to attend;
that when He who is the resurrection and the life may see meet,
the shield may be anointed with heavenly oil,
to the praise and the glory of his great name.

First-day,
21st.--Favored with something of those refreshings
which come from the presence of the Lord,
in silent waiting in our meeting today at Ridge.
O,
may I be preserved in an earnest breathing and travail of soul before
the Lord! that I may be thoroughly washed in the river of judgment,
and enabled to show forth the praise of Him who hath "`called
to glory and to virtue;`" that in thought,
word and deed, all may be brought to the obedience of Christ.
In viewing retrospectively the mercies of a gracious God,
all within me was humbled before Him,
with earnest petitions to be preserved near unto Him,
who is the resurrection and the life.

Sixth Month 4th.--Set out for Red-stone, in company with my dear friend, Ralph Cowgill.
Arrived in the neighborhood of Westland the 6th, and attended meetings at Westland,
Pike-Run, Sewickly, Providence, Centre and Red-stone;
some of which were favored meetings, particularly, Providence and Centre.
In some of the others my mind was clothed with mourning on account of
a root of bitterness and disaffection which has crept in,
in consequence of the unsound doctrines of Joseph John Gurney--or modified
Quakerism--one of the deeply laid snares of the enemy of the church,
to prevent her from filling that place and
station designed for her by her glorified Head.
O, may He, by the brightness of his coming, destroy every false covering,
that the people may see through these snares, and make their escape!

Returned home peacefully the 13th of the month, and found my dear family well.

[.embedded-content-document.letter]
--

[.letter-heading]
Letter to Ann Branson.

[.signed-section-context-open]
First Month 13th, 1849.

[.salutation]
Dear friend Ann Branson:

Feeling my mind drawn towards
thee in true Christian sympathy and gospel fellowship,
I have been induced to pen a few lines to thee; believing that speaking one unto another,
even in this way, when it is done from the fresh openings of the good Shepherd,
is strengthening to poor pilgrims who feel for one another,
and at times pray for one another.
O,
may I be preserved an object worthy a place in the minds of
the living! whatsoever may be the trials that attend;
and truly I can say I never needed it more than at this time,
and although my portion of late has been trials and deep provings,
I hope never to distrust the goodness and mercy of the Lord; which unworthy as I am,
I have been a sharer of in days past.

But to go forth on such an embassy as the one before me
is enough to bring the creature very low,
feeling my great weakness for such a service.
Many times could I say with that deeply tried servant of the Lord, Thomas Scattergood,
"`If thou, O Lord! go not forth with me, take me not hence.`"
There is, however, a revival of faith, at times,
in the unfailing mercy of the good Shepherd;
and the poor soul is strengthened to look forward in humble hope that divine
support will be vouchsafed to fulfill the service that may be required;
and be preserved from doing harm; which,
with the language of "`unprofitable servant`" indelibly fixed upon my heart,
is all I ask.
My portion very often has been a sense of extreme poverty,
yet the remembrance of my dear friends is at times very precious,
of which number thou art one;
having no doubt of thy concern to be found faithful to thy divine Master;
neither have I any doubt of his watchful care over thee.
Mayst thou be encouraged under whatever trials and afflictions may attend thee,
whether they be spiritual or temporal, to follow the good Shepherd whom thou hast known,
when He hath put forth, to go before; and to be mouth and wisdom, tongue and utterance.

Ah! there is a place of safety for all the Lord`'s faithful servants and handmaids;
where they may not only experience their "`place of defence to be the munitions of rocks;
bread to be given them,
and their waters sure,`" but to be so replenished with
heavenly virtue as to be as "`saviours upon Mount Zion,
judging the Mount of Esau,`" that the "`kingdom may be the Lord`'s.`"

Amidst the trials which abound at the present day,
it is a comforting reflection that all these things will come to an end:
that the Lord will make a way for his own oppressed seed,
and cause the afflictions that are meted out to
conduce to the purification of the church:
that she may be seen coming up from the wilderness "`leaning upon her beloved;
fair as the moon, clear as the sun, and terrible as an army with banners.`"
I do believe that brighter days are coming; may patience then as well as faith hold out;
and entire dependence be placed in the unfailing mercy of the Shepherd of Israel, who,
in his own time will redeem his faithful children out of all their troubles.
I have often thought of thy dear aunt E.,
and have no doubt her exercise of spirit on behalf of herself and the church,
comes up as a sweet memorial before God.
Give my love affectionately to her.

[.signed-section-closing]
I conclude, and remain, I hope, thy true friend,

[.signed-section-signature]
Joseph Edgerton.

--
