== Chapter XIV.

[.chapter-synopsis]
* Account of a visit to the meetings of Redstone, Salem and Springfield Quarterly Meetings.

I left home the 25th of First Month, 1853, having the concurrence of my friends at home,
in order to perform a religious visit to the meetings of Redstone,
Salem and Springfield Quarters.
Arrived at Westland on the evening of the 27th. The next day, rode to Brownsville,
and thence to Sandy Creek, among the Allegheny Mountains,
where formerly there had been a meeting of Friends, but was discontinued.
Feeling my mind drawn to have a meeting in that neighborhood,
and our wishes being made known, the Methodist Society in a village near by,
kindly offered their meeting-house, as also their meeting hour, for our accommodation.
We accepted the offer, and a meeting was held on First-day, the 30th,
which was largely attended; and the doctrines of the gospel were opened, I trust,
in the "`demonstration of the Spirit and of power.`"

May the Lord alone be praised for his own works, for they only can praise Him.

Second-day.--At Centre; a time of renewed favor,
the tendering love of God being felt in a good degree to prevail.

Third-day.--At Redstone and Westland; both relieving opportunities.
At Pike Run my lot appeared to be to set an example of silence.

Fifth-day.--At Providence Monthly Meeting, to satisfaction.

Sixth-day.--At the Select Quarterly Meeting;
and at the Quarterly Meeting for Discipline the next day; which,
though a season of deep exercise, proved to be relieving to my poor, tribulated mind.
May my soul bow in humble prostration before Him,
who regardeth the afflictions of his people, and will, in his own time,
"`turn their captivity as the streams in the south.`"

First-day morning, 6th of Second Month.--Set out for Sewickly Meeting,
notice having been forwarded of our expectation of being there.
We were favored to arrive in time, which proved an open, relieving opportunity.
May my soul always retain a lively remembrance of the
goodness and mercy of my Divine Lord and Master.

G+++.+++ G. going with us, we set out on Second-day morning for Salem, by way of Pittsburgh;
and feeling something about a meeting there, our kind Friend, Frederick Maerkt,
offered his house to hold it in.
A number of the neighbors and serious people were accordingly invited; and,
through the Lord`'s mercy, it was an open time.
May He have the praise.

Reached Middleton on Fourth-day evening,
and attended Monthly Meeting there the next day, where we met with our dear friend,
Ann Branson.
Ancient and ever lasting goodness was near, solemnizing the hearts of many.
The meeting closed in solemn prayer.
May praise and thanksgiving be ascribed unto the Lord.

Sixth-day---Attended the Select Quarterly Meeting at Salem;
and the Quarterly Meeting for Discipline the next day; which was a favored meeting.

Had a youths`' meeting in the afternoon of First-day, 13th, which, I trust,
proved a time of renewed visitation to some.
Deeply have I been led to feel for this interesting class of our Society,
in this day of great liberty and liberty-seeking.

Second-day.--Attended the Select Quarterly Meeting at Springfield,
and the Quarterly Meeting for Discipline the next day.
Deep suffering was my portion in both on account of the great disunity
occasioned by the reception of unsound doctrines in our midst;
but through the Lord`'s unmerited mercy,
I was strengthened to throw off the burden of exercise which weighed heavily upon me.

Fourth-day.--Went to the settlement in Geauga
County and had a meeting there the day following,
which was a time of instruction to some.
Ann Branson and company were there with us.

Sixth-day evening.--Had a meeting at Ravanna, to the relief of my mind.

First-day, 20th.--Had an appointed meeting at Middleton,
to which many not of our Society came;
and the everlasting gospel was declared in its own power.
May the Lord have the praise.

Second-day.--At Carmel,
where the blessed Master was pleased to qualify
to declare the "`unsearchable riches of Christ.`"

[.asterism]
'''

From this time forward but little account of the life and religious
labors of our dear friend appears to have been kept by his own hand;
or, if so, it cannot be found.
It appears, however, from the records of his Monthly Meeting,
that he was liberated at various times to travel in the service of his Divine Master,
within the limits of different meetings,
in accordance with his apprehension of religious duty.

In the year 1853, after returning from the above described service,
he was liberated to visit in gospel love the meetings
belonging to Short-Creek and Stillwater Quarterly Meetings.

In the Twelfth Month of the year 1855,
he was subjected to one of the severest of earthly trials,
by the removal of his dear companion and bosom friend from works to rewards.
She had been a true helpmate to him, and tender wife;
and great was their unity and harmony in their daily
walks together for a term of over thirty-seven years,
and his loss was, therefore, keenly felt, yet borne with becoming resignation.

Her illness was lingering; and ultimately assuming a neuralgic character,
was very painful; even so extreme during the last few months of her life,
as to produce spasms.
She was favored, however, in great measure, to retain her faculties,
and though one not apt to speak of her religious feelings,
she at divers times uttered comfortable and instructive expressions.

Some months prior to her decease,
being brought so low by internal hemorrhage that her recovery was despaired of,
she remarked to her husband: "`I thought last night I was almost gone,
and I felt very peaceful.
I have had an opportunity during the past winter to review my past life,
having been frequently alone in my chamber; and although I am a poor creature,
I have not been able to see anything in my way.
I am willing to go.`"
After this, however, she rallied a little, and for a time gained some strength,
yet her sufferings continued; in the midst of which,
she said she could adopt the language of the poet:

[verse]
____
"`There is mercy in every place,
And mercy+++--+++encouraging thought+++--+++
Gives even affliction a grace,
And reconciles man to his lot.`"
____

In the progress of her disease, she became entirely blind,
to which great privation and trial she was, through Divine mercy, resigned, saying:
"`I think I can say, I feel resigned to my situation.`"
At one time, being asked how she felt, she replied: "`I feel poor;
but feel no condemnation.`"
A short time before the attack, which in about a week terminated her life, she remarked:
"`I think nature must soon give way, and I am satisfied,
and willing that it should be so.`"

She was firmly attached to the doctrines and testimonies which
the Lord has required the Society of Friends to uphold;
and labored in the sphere allotted her for their support.
Being favored with a sound and discriminating judgment;
through obedience to the requirings of her divine Master,
she was qualified to take an active part in the administration of the discipline;
and was instrumental in maintaining the cause of Truth,
to the comfort and encouragement of Friends, and the benefit, of the church.

In contemplating the removal of this dear friend, the Scripture language may be adopted,
"`Our light affliction which is but for a moment,
worketh for us a far more exceeding and eternal weight of glory;
while we look not at the things which are seen, but at the things which are not seen.`"
"`For we know that if our earthly house of this tabernacle were dissolved,
we have a building of God--an house not made with hands, eternal in the heavens.`"

But to return to the religious services of the subject of this Memoir, we find,
that in 1856,
he was liberated to visit the families of
Friends composing Short-Creek Quarterly Meeting:
and in 1858, to visit the families of Sunsbury Particular Meeting.
In the Second Month of 1859, with the approbation of his Monthly Meeting,
he appointed a meeting for the inhabitants of Barnesville;
and in the Fourth Month following,
he felt his mind drawn to appoint a few meetings in Iowa,
for which service he was liberated by his Friends at home.

Under date of Eleventh Month 12th, of this year, he thus writes to his dear friend,
Ann Branson:

[.embedded-content-document.letter]
--

[.salutation]
Dear friend Ann Branson:

In the fellowship of the gospel, I salute thee, desiring for thee as well as for myself,
the blessing of preservation in this day of accumulated trials and
discouragements to all the living members of the church of Christ:
for so it seems to me, it is, and has been for a long time: and,
if it were not for a token of good now and then in mercy extended,
what would become of them?
These seasons are no doubt intended by Him who is "`wonderful in counsel,
and excellent in working;`" to sustain through the
trials which are permitted to attend their path;
even as it was with the servant of the Lord in old time,
when he laid himself down under a Juniper tree,
and requested for himself that he might die; and as he lay and slept,
the angel of the Lord fed him with bread and water,
and he went in the strength thereof forty days;
and when the Lord showed him that He had a service for him,
his feelings were very much depressed; when he broke forth in the language;
they "`have thrown down thine altars, and slain thy prophets; and I, even I only am left;
and they seek my life to take it away.`"

The present stripped and peeled state of our Society is cause of much sorrow;
but my dear friend, some of us, and I trust, a goodly number up and down,
have been favored to see in the light of the Lord the necessity of upholding a
faithful testimony against these innovations upon our doctrines and testimonies,
which have been the ostensible cause of all our troubles.
But when we do our duty and no headway can be made,
let us take comfort in the Scripture declaration; "`The foundation of God standeth sure,
having this seal, the Lord knoweth them that are his.`"
If it were right for Friends to bear testimony against said innovations;
which I have never for a moment doubted; it does appear to me,
if right things were carried out,
there would be a willingness to own such as have been
contending for the same faith and testimonies,
that we have.
But while I mourn over our present condition,
I desire that I may be favored to do my duty faithfully;
and as it is my desire for myself, so it is for all the Lord`'s faithful children.
O! it is no wonder if these feel something like that described by the Psalmist;
"`By the rivers of Babylon, there we sat down; yea, we wept when we remembered Zion;
we hung our harps upon the willows in the midst thereof.`"
But as we keep our ranks in righteousness,
whether a state of suffering or rejoicing be our portion;
in a day that is approaching we shall be accepted in the Beloved.
That it seemed with me in the fresh flowings of my Heavenly Father`'s love,
to salute thee, and to desire thy encouragement, as also my own,
in the service allotted us, believing that He who hath called us,
still regardeth the low estate of his children; and when He maketh up his jewels,
"`He will spare them as a man spareth his own son that serveth him.`"

Oh! blessed and praised be the name of Israel`'s God for his abundant mercy,
in opening to our worthy forefathers the beauty and
excellency of this last and lasting dispensation;
and has opened, and does open the same unto us, as we walk by the same rule,
and mind the same thing.

[.signed-section-closing]
I am, as ever, thy friend in the Truth,

[.signed-section-signature]
Joseph Edgerton.

--

[.offset]
In 1860 he visited Pennsville Quarterly Meeting, and most,
or all of the meetings composing it.
Also, in the same year, he visited in gospel love,
the Quarterly Meetings of Salem and Springfield, and the meetings belonging thereto.
In 1861, he visited the Quarterly Meetings of Redstone and Pennsville,
and some of their branches;
and in the latter part of the same year he performed a visit
to the families of Friends of his own Monthly Meeting,
so far as way opened. In the First Month, 1862,
he visited Pennsville Quarter and the meetings belonging thereto, as way opened for it;
a short account of which is found in his own hand,
as follows:

Having felt drawings of duty in my mind,
and having the concurrence of my friends therein, I proceeded,
in company with my dear friend, Edmund Bailey, towards Pennsville,
and arrived in the neighborhood on Fourth-day evening.

Fifth-day.--Attended Monthly Meeting there, which was,
through the continued mercy of the Shepherd of Israel, a good meeting.
May his great name be worshipped and adored who is forever worthy, saith my soul.
And not feeling easy, I had a meeting appointed the next day, general notice being given,
which was a favored time, the Lord`'s power being over all,
and giving ability to declare the "`unsearchable riches of Christ.`"
Went that evening to our dear friend, William Dewees`'s, where we rested comfortably.

Seventh-day.--Attended Chesterfield Monthly Meeting,
which was a time of instruction to many;
also at the public meeting at that place on First-day, which proved,
through the Lord`'s mercy, a heavenly meeting,
and ended in thanksgiving and praise unto Him who "`gave us
the victory through our Lord Jesus Christ.`"
My mind was clothed with sweet and heavenly peace.

On Second-day, had a meeting at the house of our dear friends,
Edward and Lydia McConnell, in a new settlement of Friends, not far from Plymouth.
The meeting was much crowded,
many being there who were entirely unacquainted with our Society;
and through the Lord`'s eternal power, the way of life and salvation was opened to them,
and the doctrines and testimonies which Truth led our forefathers into, explained,
to the peace of my own mind.
May the Lord be praised for all his works.

[.offset]
The following is an extract of a letter to some of his children, written near this time:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
First Month, 1862.

[.salutation]
Dear children, J. and A.:

I have for some days past thought of writing to you,
but being crowded with other engagements, it has been deferred until now.
I often think of you in that far distant land,
and earnestly desire your preservation on every hand; and I do believe,
as you are rightly concerned to seek for Divine aid, it will be given you.

I sometimes, when in meeting, have remembered your little company,
while tears have trickled down my cheeks,
and mental petitions have been put up unto our Heavenly Father,
that He might be with you,
and strengthen you to keep your places individually to his own praise,
and to your own peace; and I have had to believe, that if you act faithfully your part,
He will keep you by day and by night,
and nothing shall be permitted to draw you from that
safe abiding-place spoken of in holy Scripture:
"`His place of defence shall be the munitions of rocks; bread shall be given him;
his waters shall be sure.`"

Our Meeting for Sufferings convened last Fourth-day at Stillwater,
on the subject of the awful condition of our beloved country,
involved in war and bloodshed:
and upon a concern for the preservation of our members in a
conduct consistent with our high and holy profession.
A minute of advice was prepared to subordinate meetings, and to our individual members,
and four hundred copies directed to be printed.
I will send some to you when they are ready.

[.signed-section-closing]
Your affectionate father,

[.signed-section-signature]
Joseph Edgerton.

--

[.offset]
He again writes to the same, under following date, an extract being as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Seventh Month 4th, 1862.

[.salutation]
Dear children, J. and A.:

We had the reading of a letter from you today,
which was very pleasant, as you are often in our thoughts,
as well as subjects of conversation, hoping, and desiring for you as for our own souls,
the blessing of preservation; for truly, the present is an awful day.
Oh! that all of us may, by watching unto prayer,
be preserved from everything that would dim the beauty of Zion,
or obstruct our own peace.

I often think of you, my dear children, and of the little meeting there, with a mind,
at times, possessed of fears that you may not at all times hold it to the honor of Truth.
But let me say to you, be not over-much discouraged at the smallness of your number,
nor yet at your weakness and shortcomings,
but let each one endeavor in that portion of living faith vouchsafed to you,
to follow our Lord and Master, who will be "`strength in weakness, riches in poverty,
and a present help in the needful time.`"

I can say, my spirit is often with you, though far distant in body.
May the Lord bless you with the blessings of heaven above,
and with that of the earth beneath,
in such proportion as is consistent with his pure and holy will,
that you may be enabled to "`honor Him with your bodies and your spirits,
which are his.`"

We lately went with our dear brother and daughter to St. Clairsville,
and attended meeting there on First-day, which was very small, no doubt less than yours.

[.signed-section-closing]
I conclude, with love to all, as though named,

[.signed-section-signature]
Joseph Edgerton.

--

[.offset]
Another extract of a letter to the same:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ninth Month 9th, 1862.

[.salutation]
My dear children J. and A.:

Your truly acceptable letter came duly to hand.
We often think of you in these awfully trying times;
and hope you will be strengthened to keep your places,
and uphold our Christian principles.
It seems to me that the language of the Prophet Jeremiah to Baruch,
is applicable to us at the present day, "`Seekest thou great things for thyself:
seek them not:
thy life shall be given thee for a prey in all places whither thou goest.`"
If we can be favored to witness our life given unto us, both spiritually and temporally;
and can have bread to eat, and raiment to put on, we ought therewith to be content,
and to be thankful to the great Giver of every good and perfect gift.`"

How are you getting along in your little meeting?
I often think of you in that far distant land;
and my heart is frequently poured out in mental
petitions to our Almighty Father in heaven,
that He may keep you, and vouchsafe of his peace and Holy Spirit,
to soothe and comfort you in your lonely situation;
and to make you strong to bear all the trials that may
be permitted to attend you in this cloudy and dark day.
I have learned from letters lately received that
drafting will likely ere long take place there.
If any of my sons should be of the number,
let them always treat the government officers with due respect,
and avow their conscientious scruples, and adhere to them;
that as a Society we have always borne a testimony against war;
and may the Lord strengthen you to uphold it to the honor of his great and worthy name.

[.signed-section-closing]
From your affectionate father,

[.signed-section-signature]
Joseph Edgerton.

--

[.offset]
We further find that in 1863 our dear friend again felt drawn to
visit in gospel love the Quarterly Meetings of Salem and Springfield,
and was liberated for the service accordingly;
and in 1864 he visited the meetings composing those quarters:
and in the same year he again visited Pennsville Quarterly Meeting,
and the meetings belonging thereto;
which is the last service of the kind we find any account of.

[.offset]
Two extracts of letters to his children written in this year, here follow:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Fourth Month 17th, 1864.

[.salutation]
Dear children J. and A. E.:

We often think of you and the rest of our folks in the west.
O! how pleasant it would be to be near to you and to all our children,
and be a comfort and strength to each other.

You are now differently circumstanced from what you have been;
mingling in a neighborhood of old acquaintance, many of whom, I trust,
are desirous to be found living up to our high and holy profession.
O! that it might be so with all in that land as well as in this;
for many eyes are upon us, and if we could be favored to live up to our profession,
we should be kept within the holy enclosure, where no "`evil could befall,
nor plague come nigh.`"
O, for this place of safety! the "`munitions of rocks,`" where "`bread may be given`" us,
and our "`waters be sure.`"

Even though we are an isolated body, not in correspondence with any other Yearly Meeting,
yet his everlasting arm will be underneath for our support,
as we are faithful to Him who hath called us to glory, and to virtue.

[.signed-section-closing]
Your affectionate father,

[.signed-section-signature]
Joseph Edgerton.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ninth Month 26th, 1864.

[.salutation]
Dear children, J. and A. E.:

Yours of the +++_______+++ came duly to hand, and was acceptable,
as it is always pleasant to hear of your welfare; and I may inform you that we are well;
and although it will be a great trial to break up here, and leave friends and relations,
and go into that far distant land,
yet I have believed it would be consistent with the Divine will so to do;
trusting in the goodness and mercy of Him who hath fed me all my life long unto this day,
both spiritually and temporally.

[.signed-section-closing]
Your affectionate father,

[.signed-section-signature]
Joseph Edgerton.

--

[.offset]
Having joined himself in marriage with Anna M. Brantingham,
in the Fourth Month of the year 1857,
as appears in the testimony of Somerset Monthly Meeting concerning him,
they jointly requested,
and obtained a certificate of removal for themselves
and family to Coal Creek Monthly Meeting,
Iowa, in the spring of 1865;
and accordingly removed there in the Fourth Month of that year,
believing it their duty to do so;
but his sojourn amongst his friends and relatives there was of short duration;
yet it appears he was frequently and fervently engaged in the exercise of his gift,
on their behalf, during the few remaining months of his life.

[.offset]
We find two letters, which were written during this time, extracts of which here follow:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Iowa, Fifth Month 7th, 1865.

[.salutation]
Dear children, John and E. Thomasson:

Your very acceptable letter came duly to hand,
and this may inform you that we are all well.
We lodged last night in our own house,
and you may suppose it was very pleasant to get to housekeeping again.
The meeting-house today was about full, as it generally is on First-days;
and I believe there is a goodly number of well-concerned Friends here;
but on the part of many others there is cause of deep exercise,
with which my heart has been clothed in rather a remarkable degree,
and a door of utterance, with a measure of the heavenly unction,
has been witnessed in labor amongst them,
to my own relief and confirmation that our being here is in the ordering of Him
whom I have been endeavoring to serve ever since the days of my childhood;
though I have nothing to boast of but weaknesses and shortcomings.

My dear daughter E., I notice thy remarks touching thy own state,
as being that of poverty and destitution.
And it is with me, dear child, to say:
cast thyself into the arms of Him who knoweth the integrity of thy heart,
and whom it has been thy desire for years gone by,
to serve with "`a perfect heart and a willing mind;`" and although thou may
have lingered a little behind for fear of going before thy Guide,
and thus brought trouble and distress of mind, yet, dear child,
remember thou art in "`very good hands,
who is "`touched with a feeling of our infirmities,`"
and as a "`father pitieth his children,
so the Lord pitieth them that fear Him.`"
Thy dear father has trod the same path before thee,
and can bear testimony to the goodness and mercy of our Heavenly Father;
and if it be his pure and holy will that thou shouldst be engaged in
declaring to others what the Lord hath done for thy soul,
He will renew his visitations and enable thee to arise
and acquit thyself in his pure and holy sight;
and thus learning by the things thou hast suffered,
be enabled to come forward in service to thy own peace, and to the benefit of the Church,
as well as to the advancement of the kingdom of our dear Redeemer.

I often remember my dear friends at Ridge,
and believe that the "`everlasting arms will be underneath`" all who
are rightly concerned to follow their Divine Lord and Master.
May they all be enabled to serve Him, for it may be truly said: "`The harvest is great,
but the laborers are few; pray ye, therefore,
the Lord of the harvest that He would send forth laborers into his harvest.`"
I do believe He hath come and hath called, and is calling, in an especial manner,
to some, to devote their hearts more unreservedly to Him, which, if they would obey,
Ridge Meeting would increase in the life, if not in number;
though I do not intend to convey the idea that Divine favor has not been witnessed there.
No; the remembrance of the many bedewing seasons witnessed at dear Ridge,
humbles my heart, and causes tears of gratitude to flow freely.
May He still continue to bless the little remnant there, and enable them,
under a sense of the continuance of his mercy, to say:
"`Hitherto the Lord hath helped us.`"
So, in dear love to you and the children, I am, as ever,

[.signed-section-closing]
Your affectionate father,

[.signed-section-signature]
Joseph Edgerton.

--

[.asterism]
'''

[.embedded-content-document.letter]
--

[.letter-heading]
Letter to Ann Branson.

[.signed-section-context-open]
Iowa, Seventh Month 21st, 1865.

[.salutation]
Dear friend, Ann Branson:

We heard a few days ago of thy safe arrival at home;
and the feeling of love so pervades my mind, that I thought I might,
in that liberty which the Truth gives, say,
that thou wast often the companion of my mind during thy embassy to a foreign land;
and I did believe that thy divine Lord and Master,
who called thee forth into that service, would be with thee,
and keep thee in the hollow of his holy hand,
and cause thee to witness the truth of that Scripture language:
"`He that goeth forth and weepeth, bearing precious seed, shall, doubtless,
come again with rejoicing, bringing his sheaves with him.`"

No doubt, thou can say with thy poor correspondent,
that there is great need of a deeper indwelling of soul before the Lord,
on the part of many amongst us;
on which account those who are waiting for the consolation of Israel, like Simeon of old,
are often bowed down, and can adopt the language: "`Spare thy people,
O Lord! and give not thine heritage to reproach,`"

Oh, there is need for Friends to keep their ranks in righteousness,
and not be drawn aside from a faithful,
upright maintenance of the doctrines and testimonies which have distinguished the
living members of our Society from its first rise to the present time.
I see no reason why Friends should now desert the cause,
or in any way connive at these departures from primitive Quakerism,
which was the occasion of the trouble that has been hanging over us so long.

I sometimes call to mind the circumstances of former years,
when thy dear father was united with many of us
in raising up a standard against the enemy,
through whose agency those unsound doctrines had been sown broadcast in our midst.

Although I feel the need of the prayers of my dear friends,
that I may be kept in the line of Divine appointment,
and be enabled so to "`finish my course,`" and the little gift of "`ministry
which I have received of the Lord Jesus,`" as to win the prize;
yet I can say,
I often feel longing desires for my dear friends
with whom I have been associated many years,
some of whom are as bone of my bone, and flesh of my flesh in the heavenly kindred,
that they might be "`steadfast, immovable, always abounding in the work of the Lord,
knowing that their labor is not in vain in the Lord.`"
Thou knowest, dear friend,
that there are many things to discourage the faithful followers of the Lamb;
but we may remember, that He, our ever-living and compassionate Redeemer,
is "`touched with a feeling of our infirmities,`"
and is able to succor us under all our trials,
both of flesh and spirit.

[.signed-section-signature]
Joseph Edgerton.

--

[.offset]
In the Tenth Month following the above writing,
our dear friend was taken dangerously ill,
and departed this life on the 30th of the same;
a special account of which is contained in the following
Testimony of Somerset Monthly Meeting concerning him.
