== Chapter XVI.

[.chapter-synopsis]
Address to the Members of The Society of Friends.

At the Meeting for Sufferings of Indiana Yearly Meeting, held at White Water,
near Richmond, Wayne County, Indiana, Ninth Month 27th, 1841.

A copy of the following Address to the Members of the religious Society of Friends,
by Joseph Edgerton, was received from the Meeting for Sufferings of Ohio Yearly Meeting,
and a minute of that meeting, stating that the address had been examined and approved.
The address thereupon was read, and satisfaction and unity with it was expressed.
It was proposed and united with that five thousand copies be
printed for the use of the members of our Yearly Meeting.

[.signed-section-closing]
Extracted from the minutes.

[.signed-section-signature]
Thomas Evans, Clerk.

[.embedded-content-document.address]
--

[.letter-heading]
Address to the Members of the Society of Friends.

[.salutation]
Dear Friends and Brethren:

In that love and life wherein is
our union and fellowship in Christ Jesus our Lord,
I salute you, desiring that He may enrich you with his heavenly blessings,
and enable you to stand fast in that liberty wherewith his disciples are made free.
So will ye answer the end for which our religious
Society was gathered together in the beginning,
by bearing as an ensign before the nations,
a testimony to the peaceable reign of the Messiah,
and to the spiritual nature of his glorious gospel.

As a living, upright zeal is daily maintained for our own growth in grace,
for the promotion of the cause of truth and righteousness on the earth,
and for the glory of God,
we shall feel that we have abundant cause to bless and praise
his holy name for accounting us worthy to receive such tokens
of his gracious regard as have been extended to us as people,
from one generation to another.
When our forefathers, through a powerful visitation from on high to their souls,
were drawn from the lifeless forms and ceremonies that had
crept into the Church during a long night of apostacy,
and in a true hunger and thirst after righteousness, met together in small assemblies,
reverently to wait upon Christ Jesus, the true Teacher of the children of men,
they found to their great comfort that which they sought after.
The Lord gave them to see the unsatisfying nature of a man-made ministry,
and to understand that under this glorious gospel dispensation,
it was a prerogative that Christ had kept in his own hands,
who is head over all things to his Church, to raise up and qualify his own ministers,
each of whom must acknowledge with the Apostle, in regard to the gift bestowed upon him:
"`I neither received it of man, neither was I taught it,
but by the revelation of Jesus Christ.`"^
footnote:[Galatians 1:12]

Through the teachings of the Holy Spirit,
our forefathers were led into that plain way of worship,
which has distinguished us as a religious Society from that day to this.
The Lord was with them, and wrought mightily for them;
and notwithstanding the persecutions they suffered at
the hands of wicked and unreasonable men,
their number greatly increased.
In a short time many able ministers were raised up among them,
who went forth to and fro with the glad tidings of the gospel of peace and salvation;
and visited souls, who had been waiting for the consolation of the Israel of God, could,
under a feeling of Divine favor, through them, adopt the language:
"`How beautiful upon the mountains are the feet of him that bringeth good tidings,
that publisheth peace; that bringeth good tidings of good, that publisheth salvation;
that saith unto Zion, thy God reigneth!`"^
footnote:[Isaiah 52:7]
These bold, faithful advocates, and valiant sufferers for the cause of Christ,
were favored with a clear view of this last and lasting dispensation,
and its spiritual nature and design; and very remarkable it was, that in their ministry,
in their disputations with their opposers, and in their writings,
they all spake the same language,
and all advocated the same views of the doctrines of the gospel.
This is a confirming evidence that they were illuminated by the one spirit,
and thus in the mercy, wisdom and goodness of the Lord our God,
they were brought forth under a special qualification to hold
up a pure and perfect standard of Christian doctrine,
agreeably to the Holy Scriptures.

Strong have been my desires that we may not become weary of
that way of worship which we have learned of our Divine Master,
nor yet of those scriptural views of the doctrines of Christ and his apostles,
which have been believed in and upheld by this Society,
from its first rise to the present day.
Dear friends, the daily cross must be experienced, whereby being crucified to the world,
we may be made to follow the blessed Captain of
salvation in the straight and narrow way of self-denial.
Then, with an eminent apostle, we shall be enabled to say: "`I am crucified with Christ,
nevertheless I live; yet, not I, but Christ liveth in me,
and the life which I now live in the flesh, I live by the faith of the Son of God,
who loved me, and gave himself for me.`"^
footnote:[Galatians 2:20]
As Christ comes to live in us, and to rule and reign in us,
all that is high and lifted up will be laid low,
and we shall become willing to be of no reputation, after the example of Him, "`who,
being in the form of God, thought it not robbery to be equal with God,
but made himself of no reputation, and took upon Him the form of a servant,
and was made in the likeness of men; and, being found in fashion as a man,
He humbled himself, and became obedient unto death, even the death of the cross.`"^
footnote:[Philippians 2:6-8]
Thus, and thus only, can we answer the design of our Heavenly Father concerning us,
steadily to maintain those testimonies,
which He has made it our duty to bear to the
world for his glorious name and truth's sake,
in this new covenant dispensation.

It appears to me there never was a period,
when the necessity was more urgent for us to be found at our posts;
"`Let your lights so shine before men, that they may see your good works,
and glorify your Father which is in heaven.`"^
footnote:[Matthew 5:16]
Let none be ashamed of a deep and reverent silent waiting in our assemblies,
for a qualification to perform acceptable worship unto God,
nor yet of our meetings that are held throughout in silence,
when it is the blessed Master's will that it should be so;
but let us show that we believe in, and do experience the truth of his saying:
"`Without me ye can do nothing.`"
He alone hath brought us into the blessed lot of our inheritance,
to sit under his teachings, who is indeed our great prophet,
the minister of the sanctuary, and of the true tabernacle which the Lord hath pitched,
and not man.
He hath brought us to feel the sweet and heavenly harmony
experienced by the true worshippers within the temple,
who are gathered in his name, out of the world, out of its worship and ministry,
and out of the activity of the creature.
May we support unsullied this excellent testimony to
the spiritual nature of gospel worship,
and may the Lord by his divine power open more and more
the understandings of the children of men,
to come to partake of the blessed fruit thereof, "`For, from the rising of the sun,
even unto the going down of the same, my name shall be great among the Gentiles;
and in every place incense shall be offered unto my name, and a pure offering.`"^
footnote:[Malachi 1:11]
As we are faithful,
our ever-adorable Head will still continue to bless the provision of Zion,
and satisfy all her poor with bread,
and by his Divine presence He will cause our religious
assemblies still to continue to be holy convocations unto Him,
and to the rejoicing of the Israel of God.

Many have been the exercises of my mind for several years past,
because of a spirit that in some parts of the Lord's heritage,
is exalting itself above the cross of Christ.
It is a spirit which is delusively deceptive,
and would insinuate that the doctrines which have been believed in and
upheld by us ever since it pleased the Lord to gather us to be a people,
are involved in mysticism,
and that our worthy predecessors were not clear
in their understanding of Christian doctrine.
Be aware, dear friends, of this spirit, and of those who are actuated by it;
for it is manifest, and will more and more appear that they are in the mixture,
and their vision is not clear.
They have not experienced the efficacy of the one baptism,
which cleanses from all defilement,
and brings into the situation of little children
depending upon their Heavenly Father for sustenance,
for strength and ability to follow Him in the way of his holy commandments, to his honor,
and their own present and eternal welfare.

Let us hold fast the profession of our faith without wavering,
and keep out all murmuring and complaining.
Some for want of duly maintaining the watch,
have in great measure lost that sense and feeling of divine things which they once had,
and are very ready to find fault with the living, exercised members of the body,
whose eyes are anointed to see the situation and danger they are in, and who,
through the constraining love of the gospel are at
times engaged to labor with them for their restoration,
even as such who must give account of those over
whom the Holy Ghost hath made them overseers.
These complainers will cry out in language similar to
some discontented spirits under the legal dispensation,
"`Ye take too much upon you.`"^
footnote:[Numbers 16:3]
But the power of Truth is over them,
and all the living members who keep their places in the body,
by that living sense which they receive from God, are over them and all their murmurings.
Oh, that such might submit to the teachings of Christ in their own hearts.
This is the only way whereby such can be restored into the unity of the body,
into the fellowship of the gospel, and into a living sense of divine and heavenly things.
As any come upon this ground of faithful obedience,
great reduction of self will be experienced,
and their dependence will be entirely fixed upon the source of Divine light, life,
wisdom and intelligence; Christ in them the hope of glory.

Dear friends, as you search diligently with the spirit or candle of the Lord,
you will find the root and cause of all your
murmurings and discontent is within yourselves,
and you will feel that in Divine mercy, the healer of breaches,
and restorer of paths to dwell in, is waiting to be gracious to you,
to bring you into the enjoyment of the heavenly life,
and to know the flowing of the living sap from the true vine,
in which all the faithful members abide, and wherein their unity and fellowship stands,
agreeably to that beautiful simile used by our blessed Lord and Saviour Jesus Christ:
"`I am the true vine, and my Father is the husbandman.
Every branch in me that beareth not fruit, He taketh away;
and every branch that beareth fruit, He purgeth it that it may bring forth more fruit.`"
"`Abide in me, and I in you.
As the branch cannot bear fruit of itself, except it abide in the vine, no more can ye,
except ye abide in me.`"^
footnote:[John 15:1-2, 4]

All the branches that abide in the vine, partake of the same life-giving sap;
and the fruit brought forth by them is of the same good kind,
to the praise of the great Husbandman.
In this blessed and heavenly unity all the members of the body
are strengthened to go forward in their respective services;
and they know that there is no room for complaining, nor for any to say,
because I am not the hand, or the eye, or the ear, I am not the body.
The different members, feeling a portion of the same virtue, act unitedly,
and rejoice or suffer together,
as may be consistent with the will and wisdom of our ever-adorable Head.
May this sweet and heavenly fellowship more and more spread amongst us,
that those branches, which,
having ceased to draw the due portion of sap from the living vine,
are in a dry and withered condition, nigh to being taken away, may be restored to life.
Then from living experience, such may adopt the language:
"`Truly our fellowship is with the Father, and with his Son, Jesus Christ.`"^
footnote:[1 John 1:3]
May the Church arise from that wilderness state wherein she has been long clothed
as with a sable garment because of her backsliding sons and daughters,
and come forth in that beauty that adorned her in the first breaking
forth and spreading of this day of gospel light and power.
Blessed, honored and magnified over all, be the name of our God,
who is waiting to be gracious unto us, visiting us again and again by his Spirit,
that all may come and partake of the waters of life freely.

Unto you, dear friends, who are sitting at ease in Zion,
I have a word from my Divine Master, who is grieved because of your lukewarmness.
He hath visited you by his day-spring from on high;
He hath shown you the necessity of taking up your daily cross,
and of following Him in his spiritual appearance in your hearts.
But how have you slighted these visitations, not regarding the afflictions of Joseph,
spiritually; endeavoring to satisfy yourselves with being members of a Society,
that has been favored from its beginning hitherto.
Oh, dear friends, let me warn you in the fear of that God,
who has indeed been good and gracious to this people,
as also to all the families of the earth, be aroused from this state of carnal security,
and avail yourselves of the visitations that are yet extended to you.
My spirit hath mourned and been in heaviness
because of this abomination that maketh desolate,
whereby so many are slain upon the barren mountains of Gilboa,
where there is neither dew nor rain, nor fields of offering.
Earnestly do I desire that you may return unto the Lord, who will have mercy upon you,
and to our God, for He will abundantly pardon.

Take heed to the teachings of his blessed Spirit,
which teacheth us as it did the early Christians, "`that denying ungodliness,
and worldly lusts, we should live soberly, righteously and godly in this present world;
looking for that blessed hope, and the glorious appearing of the great God,
and our Saviour Jesus Christ; who gave, himself for us,
that He might redeem us from all iniquity, and purify unto himself a peculiar people,
zealous of good works.`"^
footnote:[Titus 2:12-13]
As you daily live, and act, agreeably to these instructions,
you will see the exceeding sinfulness of a state of forgetfulness of God,
from whom we receive every blessing, both spiritual and temporal.
Yea! the blind eyes will be opened, and deaf ears unstopped;
the lame man shall leap as an hart, and the tongue of the dumb sing.
You who have been lame and halting, as to a perfect and upright walking before God,
will, through his eternal power, come forth, walking and leaping,
and praising Him for his abundant mercies.
As you love and cherish this humble and obedient state,
the good Shepherd will lead you in the way that you should go,
and reveal to you in his own wisdom the mysteries of his kingdom.
Then with the saints of old, you will be able to say, "`In the way of thy judgments,
O Lord, have we waited for thee; the desire of our soul is to thy name,
and to the remembrance of thee.`"^
footnote:[Isaiah 26:8]
A living, upright zeal as a garment will be your clothing;
you will be zealous of good works,
and faithful in the support of the testimonies which our blessed
Master has made it our duty to bear in the sight of a wicked world.

Oh, remember how displeasing a state of lukewarmness was, in the primitive times,
for which one of the churches received this severe rebuke: "`I know thy works,
that thou art neither cold nor hot; I would thou wert cold or hot.
So then, because thou art lukewarm, and neither cold nor hot,
I will spew thee out of my mouth: because thou sayest, I am rich,
and increased with goods, and have need of nothing;
and knowest not that thou art wretched, and miserable, and poor, and blind, and naked.`"^
footnote:[Revelation 3:10,15,17]
This is the language of the same Spirit to you: "`I know thy works.`"
He knows your works, that they are but dead works.
You go to meeting; many of you come before Him as his people,
and yet your hearts are far from Him,
your minds roving upon objects very foreign from Him, or sunk into a state of stupor.
Others cannot leave their farms, their merchandise, and employments,
to meet with their brethren and sisters in a public
acknowledgment of their dependence upon Him,
who knoweth all the fowls of the mountains,
and whose are the cattle upon a thousand hills.

Every blessing that we enjoy flows from Him.
Because of these things the Spirit is pleading with you in the language:
"`I counsel thee to buy of me gold tried in the fire, that thou mayest be rich;
and white raiment, that thou mayest be clothed.`"^
footnote:[Revelation 3:18]
Gold tried in the fire; the fire of God's jealousy is kindled in Zion;
his furnace is in Jerusalem, where all his children, both sons and daughters,
are purified, and given to possess durable riches and righteousness,
the righteousness of God, which is the saints' clothing.
May these things sink deep into your hearts,
that through unfeigned repentance towards God,
and a living faith towards our Lord Jesus Christ,
you may come forth in the beauty of holiness, showing forth the praises of Him,
who hath called us to glory and virtue.
"`Thine eyes shall see Jerusalem a quiet habitation,
a tabernacle that shall not be taken down;
not one of the stakes thereof shall ever be removed,
neither shall any of the cords thereof be broken.
But there the glorious Lord will be unto us a place of broad rivers and streams;
wherein shall go no galley with oars, neither shall gallant ship pass thereby.
For the Lord is our judge, the Lord is our lawgiver, the Lord is our king;
He will save us.`"^
footnote:[Isaiah 33:20-22]

You, dear friends, whose eyes have been blinded by the god of this world,
as to the true spiritual vision, who have given way to a worldly spirit,
and are eagerly pursuing your plans to get rich,
and to make yourselves and families great in the earth;
remember the visitations of a gracious and
merciful Creator in the days of your tenderness,
when by his good Spirit He showed you the danger
of an undue love and pursuit of lawful things.
Return unto Him who is, in unutterable mercy, still holding out the inviting language:
"`Return unto me, and I will return unto you, saith the Lord,
and heal your backslidings and love you freely.`"
My spirit travails for the welfare of Zion, and the enlargement of her borders,
that we who are making this high and holy profession,
may give a practical illustration of the efficacy of true religion on the mind,
and show that we are redeemed from the world and an eager pursuit of the things of it.
The apostle saith, "`They that will be rich, fall into temptation, and a snare,
and into many foolish and hurtful lusts, which drown men in destruction and perdition;
for the love of money is the root of all evil; which while some coveted after,
they have erred from the faith, and pierced themselves through with many sorrows.`"^
footnote:[1 Timothy 6:9-10]
Experience has confirmed the truth of the declaration, even in regard to many who,
in the days of tenderness, manifested religious concern; and who,
had they continued therein, would have become serviceable members in the body.
But by giving way to a desire to be rich,
they have embarked in more extensive trade and business than they were able to manage,
which has resulted in grievous failures, almost to the ruin of themselves and families,
and to the reproach of our high and holy profession.
Hence we see the necessity of attending to the limitations and
directions of truth in our temporal business,
which if sought after, will not be withheld.
It is not with the wealthy and affluent only that this worldly spirit proves a snare;
for the dealer in hundreds may as completely
become its victim as the dealer in thousands.
He that has but very little of this world's goods may be as fully carried away with it;
may have his heart as completely set upon it, as he who possesses his tens of thousands.

Therefore the injunction of our blessed Lord applies to all:
"`Seek ye first the kingdom of God, and his righteousness,
and all these things shall be added.`"^
footnote:[Matthew 6:33]
Then as the good things of this life are increased,
the heart will be open and ready to communicate to the relief of the poor.
As good stewards of the gifts of a gracious Providence,
we shall not spend them in the gratification of our own carnal desires,
but as those who must one day give account of our
stewardship to Him from whom all blessings flow.

And dear friends, as we have seen clearly that we must not run in our own time and will,
in the great duty of worship,
so neither can we in the support of the other testimonies which are dear to us,
and to the upholding of which the Head of the Church hath bound us.
For in so doing we should be denying Him the right of
being Head over all things to his Church.
Merely having our eyes open to see the wickedness and abomination there is in the land,
is not a sufficient qualification for us to go to work to remove it.
Should such a course be pursued by us,
it might and would fare with us as it did with some in the primitive days, who,
desirous of working, presumed to call over him that had evil spirits, the name of Jesus,
whom Paul preached.
But they were answered, "`Jesus I know, and Paul I know, but who are ye?`"
And so the man possessed with evil spirits fell upon them, and they escaped wounded.
So I have no doubt such as presume to run and act in their own way and time,
will be wounded in the best life,
and the precious cause of truth will not be advanced there by.

Our ancient and well known testimonies against slavery and intemperance,
are particularly in my view at this time,
and I rejoice that the Lord has prospered the work so far,
and opened the hearts of the people so generally in the community,
to see the iniquity thereof.
These are subjects in which our religious Society has long felt a deep interest,
and has travailed and labored therein, having first endeavored to clear its own hands.
With gratitude, humility and fear be it spoken, the Lord hath made way for us,
and given us a good degree of place in the hearts of those in legislative authority.
The present is a day of great excitement on the subject of slavery,
the evils of which we deeply deplore,
both on account of the misery it entails on its victims,
and the enormous weight of guilt that is attached to its supporters.
Our blessed and holy Head is calling us to keep close to Him in a body,
out of the excitement, the whirlwind, and the fire;
where we may be clothed with that spirit which breathes "`glory to God in the highest,
and on earth peace, goodwill toward men.`"^
footnote:[Luke 2:14]

Dear friends for whom I travail in spirit, and for whom the Lord hath opened my heart,
and laid upon me a necessity to write this epistle, keep out of the excitement,
join not with the popular associations of this day of commotion, for if you do,
instead of experiencing a growth in the truth,
and bringing forth fruit more and more to the praise of the great Lord of the harvest,
you will lose ground as to the divine sense and feeling He hath favored you with.
Joining with those who do not believe in the
immediate direction of Christ in such matters,
and therefore do not wait for it, you will be very likely soon to become like them.
As the prophet declared of Ephraim, "`Ephraim,
he hath mixed himself among the people,`" "`strangers
have devoured his strength and he knoweth it not.`"^
footnote:[Hosea 7:8-9]
Thus you will be led on, it is to be feared,
and violate other very important testimonies which have distinguished
our profession from the first rise of the Society to the present day.
Instead of forwarding the work by such mixing, we shall lessen our influence as a body,
and I fear ultimately be found among those who retard the coming of
that day when every bond shall be broken and the oppressed go free.

Dear friends in this righteous cause,
may that living upright zeal that is of the Lord's own kindling,
so influence all our movements,
that it may manifestly appear that we are the followers of the Lamb,
and under his peaceable government.
Then we shall feel for our fellow-men of the African race,
and whilst under divine direction and assistance,
we pray for them that the Lord may visit them in their affliction,
and that He may hasten their enlargement and final
deliverance from the iron yoke of oppression,
we shall also desire for the slave dealer and slave holders,
that their hearts may be opened to feel the exceeding sinfulness of such a practice,
that whilst a door of mercy is open for them,
they may repent of their deeds and amend their lives.
May the Lord of the whole earth, who hath the hearts of all men in his hands,
and can turn them at his pleasure, so influence those in legislative authority,
that their enactments may be promotive of the cause of freedom,
and of the coming of the kingdom of his dear Son,
when universal justice and mercy may flow as a river,
and the day dawn when it may be said,
"`The kingdoms of this world are become the kingdoms of our Lord, and of his Christ,
and He shall reign forever and ever.`"^
footnote:[Revelation 11:15]

And now, dear friends,
it rests with me to make some remarks on the exercise of the Discipline.
The great end and design thereof, is, that things may be kept decently and in order;
that no reproach may attach to our holy profession; and that we may watch over,
one another for good.
Where any, through unwatchfulness,
turn aside from the footsteps of the companions of Christ,
those members who keep their places, will feel it their duty to seek their restoration,
agreeably to the apostolic exhortation, "`Brethren, if a man be overtaken in a fault,
ye which are spiritual restore such an one in the spirit of meekness,
considering thyself lest thou also be tempted.`"^
footnote:[Galatians 6:1]
Here we find this great duty and service confided to those that are spiritual,
that are under the government of the spirit of Christ.
Such, indeed, will feel the weight of the succeeding language,
"`in the spirit of meekness, lest thou also be tempted.`"
As delinquents are labored within this restoring spirit of Christian love,
though it may not at the time have the desired effect,
yet I doubt not it will often prove like bread cast upon the waters,
which will return after many days.
And such as have been engaged in this friendly and Christian duty and service,
as they have been faithful, receive a reward therefor.
But oh, how important it is, that those who do step aside,
should not suffer any wall of partition to get up between them and their best friends;
those members of the body, who, under divine influence,
are engaged to labor for their restoration.
When hardness and bitterness are permitted to grow in individuals,
they place themselves very much out of the way of help.

Seeing then that the work is the Lord's,
that He only can qualify us rightly to support the discipline,
let us look daily unto Him,
that He may clothe us with his own spirit and
strengthen us for every part of the service assigned,
furnishing us with that wisdom which is from above; which "`is first pure,
then peaceable, gentle, and easy to be entreated, full of mercy and good fruits,
without partiality, and without hypocrisy.`"
I have no doubt but that the light and unfeeling manner in
which the discipline in many instances has been exercised,
has been an inlet to very great weakness in the church.
Individuals have risen up, and obtained considerable influence,
not from religious weight and feeling, but from good natural parts,
and their quickness of understanding the letter of discipline,
and are even sticklers too, in the observance thereof.
Yet such not having experienced the one baptism,
whereby all the living members of the body are
raised from dead works to serve the living God,
are a great hindrance in the good and necessary work of
exercising gospel order in the church of Christ.
Hence the great necessity of a deep and fervent exercise in these meetings.
Those only who are spiritual, who are in a good degree under the government of Christ,
can to advantage be made use of in restoring such as may have been overtaken in a fault.

And dear friends,
as our meetings for discipline were first established by divine authority,
for the preservation of good order in the church of Christ,
it is only as they are held and maintained under the
same influence that the blessed end can be realized.
Hence we see the need there is for us in an individual capacity in such meetings,
as well as those held especially for divine worship,
to feel the presence of our holy Head to strengthen us for his service.
O, I have lamented that in some there is a disposition to move and act in their own time,
way, and wisdom, whereby the standard is lowered, meetings are greatly injured,
and the living in Israel burdened.
Where the right authority is maintained, each member keeping in his proper place,
looking to, and waiting upon our blessed Master, who is jealous of his honor,
and will be Head over all things to his church,
a divine and heavenly covering is often felt to
overshadow and to bring into the oneness of spirit.
Through this, such, whose business it is to speak and act publicly,
are strengthened according to the sense and feeling they are favored with,
to discharge their duty; whilst others by the inward weight and travail of their spirits,
bear up their hands, and so the work is carried on in the unity,
and life spreads and prevails.

Then dear friends,
let us strive together that our meetings for discipline may be
held in that authority in which they were first set up,
where the excellency of the wisdom of our great Head is seen and experienced,
enabling each member of his body to keep in its place;
for although there is a blessed liberty in these meetings,
all having an equal right to speak as the renewed sense
of feeling which may be afforded shall warrant,
yet it does not follow that all should speak on a particular subject,
but only as they may feel inclined by the Spirit of Truth;
or at least have a freedom in the light so to do.
Hereby we shall be preserved on the one hand
from a superabundance of expression of sentiment,
which has a tendency to carry off the weight of such meetings,
and on the other hand from falling into a dull
and protracted prosecution of the business,
which is also a great disadvantage.
As all keep in the life in that true authority wherein clear discernment is known,
we shall be favored to see how much is enough.
Sometimes a very few voices on a subject leaves
the meeting in a better situation than more.
We should keep in the meekness and gentleness of Christ
suffering no warmth of the creature to prevail,
which brings distress in meetings, wounds those who give way to it,
and grieves the spirit of the Lord.
As there is an abiding in that which gives the dominion and preserves
all the living members in the bonds of sweet and heavenly peace,
due submission one to another will be our blessed experience,
even in honor preferring one another.
In the business of meetings for discipline, after we have given our views clearly,
it is then our duty to leave it with the meeting, and cheerfully submit to its judgment,
whether the subject makes its way in the minds of those present,
according to our wishes or not.
Thus the bonds of Christian fellowship are preserved, and in true dignity maintained,
to the peace and prosperity of the church, and to the praise of her adorable Head.

Before closing this fruit of my unfeigned love, I feel constrained to address you,
dear friends, in the earlier walks of life,
to exhort you to faithfulness to the gift or spirit of God,
that is given to every man to profit withal;
which is a swift witness for Him against all unrighteousness and ungodliness of men,
reproving therefor, and rewarding for well doing.
This, dear friends, is the only way that a growth in grace can be known,
or a knowledge of things spiritual and divine can be obtained, "`for,
whatsoever is to be known of God is manifest in man,`" by that divine
light which enlighteneth every man that cometh into the world.
O mind and take heed to this light, and you will grow in grace,
and in that knowledge which accompanies salvation.
You will be favored more and more to see the beauty of holiness,
and the excellency of that divine law spoken of by the Psalmist,
"`The law of the Lord is perfect, converting the soul; the testimony of the Lord is sure,
making wise the simple.
The statutes of the Lord are right, rejoicing the heart;
the commandment of the Lord is pure, enlightening the eyes.`"^
footnote:[Ps. 19:7-8]
As you become willing to submit to this all powerful, heart-cleansing regenerating word,
the simple will be made wise unto salvation,
and their eyes enlightened by his pure and holy commandment,
to see the mysteries of his kingdom, which is to be known in the heart,
and therefore is not, "`meat and drink, but righteousness,
peace and joy in the Holy Ghost.`"
"`The fear of the Lord is clean enduring forever;
the judgments of the Lord are true and righteous altogether.`"^
footnote:[Ps. 19:9]

O dear friends, as you become willing to be taught in the school of Christ,
you will be preserved in his holy fear,
which is clear and free from that slavish dread of man,
by reason of which so many are ashamed to take up the cross and appear that plain
self-denying people which is consistent with our high and holy profession.
"`The judgments of the Lord are true and righteous altogether.`"
Your understandings will be opened feelingly to acknowledge to the truth,
"`even more to be desired are they than gold, yea, than much fine gold;
sweeter also than honey, and the honeycomb; moreover by them is thy servant warned,
and in keeping of them there is great reward.`"^
footnote:[Ps. 19:10-11]
A blessed and heavenly reward is experienced by all the diligent,
persevering and faithful students in Christ's school,
and He will lead them forward from less to more, establish, strengthen and settle them,
upon that foundation that cannot be shaken.

O, dear young friends, for whom I travail in the spiritual life,
be faithful to the Lord who hath bought you and all
mankind with the price of his own precious blood.
We are, therefore, not our own, but his, and ought to live unto Him,
and glorify Him with our bodies and our spirits which are his.
As this is the case you will, from settled conviction in your own minds,
become faithful testimony bearers,
be a great strength and comfort to your elder brethren and sisters,
who are bearing the ark of the testimony; yea,
be one in spirit with them in our religious assemblies,
partaking in that blessed harmony which the worshippers within the temple,
those who are gathered out of the world, out of its spirit,
out of its worship and ministry,
and are sitting under the heavenly ministry of the
minister of the sanctuary and of the true tabernacle,
do experience.
Then there would not be an ear open to hear the "`Lo, here is Christ, or lo,
he is there.`"
Having seen and heard and learned of Christ the way to the Father,
you will have no desire for any thing further.

You, dear young friends, who have, through the visitations of our Heavenly Father,
made covenant with Him, by some sacrifice,
my spirit travails that your faith and patience may be increased.
Remember the exhortation of the apostle, that whereunto you have attained,
walk by the same rule and mind the same thing.
As a tender father, the Lord will lead on in the path of self-denial,
the way of the daily cross, and your desire will be,
that He may take the whole government of your hearts, turn his hand upon you,
and purge away all the dross, the tin, and the reprobate silver.
The prophet in allusion to this glorious Gospel dispensation and day of Christ, says,
"`He shall sit as a refiner with fire, and as a fuller with soap,
and He shall purify the sons of Levi,
and they shall offer unto the Lord an offering in righteousness.`"
Thus as you yield yourselves unto Him in his spiritual appearance in your hearts,
waiting daily upon Him,
you will be strengthened to run in the way of his commandments and not to be weary,
and walk uprightly before Him, and not faint.
He giveth life and strength to his people, and his ways are ways of pleasantness to them,
and all his paths are peace.

It was the saying of an experienced servant of the Lord in former time,
"`It is good for a man that he bear the yoke in his youth,
he sitteth alone and keepeth silence because he hath borne it upon him,
he putteth his mouth in the dust if so be there may be hope.`"
All that have ever tried it have found it so.
Those who bear the yoke of Christ, who sit alone and keep silence,
in a deep and reverent sense of their own unworthiness,
and of the goodness and mercy of the good Shepherd,
will increase more and more in divine knowledge.
So dear friends, be faithful and watchful, and obedient to the reproofs of instruction,
which are the ways of life.
This blessed Spirit of Truth is inviting you in this language,
"`Receive my instructions and not silver, and knowledge rather than choice gold.
For wisdom is better than rubies,
and all the things that may be desired are not to be compared to it.
I, wisdom, dwell with prudence, and find out knowledge of witty inventions.
The fear of the Lord is to hate evil; pride and arrogance,
and the evil way and the froward mouth do I hate.
Counsel is mine and sound wisdom; I am understanding; I have strength.
By me kings reign and princes decree justice.
By me princes rule and nobles, even all the judges of the earth.
I love them that love me, and those that seek me early shall find me.
Riches and honors are with me; yea, durable riches and righteousness.
My fruit is better than gold, yea, than fine gold, and my revenue than choice silver.
I lead in the way of righteousness, in the midst of the paths of judgment,
that I may cause those that love me to inherit substance.
And I will fill their treasures.`"

It has been a source of deep concern to me for many years,
to observe so much latitude given to a disposition to get together
into companies unnecessarily on the first-day of the week;
which day being set apart for our religious improvement,
should be spent in a way that might conduce to our advancement in a life of piety.
I believe that many on being thrown into such companies have lost
that feeling of tenderness and religious concern which they once had,
and have been led on in vanity and folly,
until they have compromised the testimonies of truth in plainness of dress, and address,
and finally have been carried away from our religious Society.
I fervently desire you may be preserved in the Lord's holy fear,
remembering the apostolic exhortation, "`The end of all things is at hand,
therefore be ye sober and watch unto prayer.`"
Dear friends,
as much as may be retire to your respective
homes after your religious meeting on First-day,
and spend the afternoon in pious reading and meditation upon the law of the Lord.

One thing more rests with weight upon my mind, and that is,
to exhort you to be very careful what books you read,
as the experience of many has proved the truth of the testimony of the apostle,
"`Evil communications corrupt good manners.`"
I would therefore caution you to avoid those light and vain publications,
the direct tendency of which is to lead away from God's law, and vitiate the mind,
and increase a disrelish for divine and heavenly things;
as well as those which under a character professedly religious,
yet have mixed up in intimate connection,
sentiments at variance with the doctrines of the Gospel as professed by us;
and are calculated to entangle and bewilder the mind,
and obstruct a growth in the root of life.

In the first place I would encourage you to read the Holy Scriptures,
which are a declaration of those things that are most surely to be believed,
and are profitable for doctrine, for reproof, for correction,
and for instruction in righteousness,
that the man of God may be perfect thoroughly furnished unto all good works;
and are able to make wise unto salvation, through faith which is in Christ Jesus.
As they are a testimony of the things, and not the things themselves,
but are in subordination to the spirit from whence they sprang,
they are therefore to be received as such, read, believed in, and fulfilled,
and He that fulfills them is Christ.
The daily reading of these invaluable records,
with the mind directed to their blessed author,
is a source of much comfort and strength to the Christian traveller.
Be diligent herein, not only in a collective manner in your respective families,
but in a more private way, that you may grow in grace.
Next to these read the approved writings of our religious Society,
that you may be familiar with its history,
and the different testimonies which have been upheld by us from the be ginning, hitherto.
Thus will you become acquainted with the upright zeal with
which our dear forefathers were strengthened earnestly to
contend for the faith once delivered to the saints;
and through which they themselves were enabled to overcome the world,
and all the powers of darkness.
By their patient and faithful suffering they show to us a
practical illustration of the testimony of the apostle,
"`Who shall separate us from the love of Christ?
Shall tribulation, or distress, or famine, or nakedness, or the sword?
Nay, in all these things we are more than conquerors through Him that loved us.
For I am persuaded that neither death, nor life, nor angels, nor principalities,
nor powers, nor things present, nor things to come, nor height, nor depth,
nor any other creature shall be able to separate us
from the love of God which is in Christ Jesus our Lord.`
In the end they were favored with a blessed assurance of a glorious immortality,
and could adopt the language, "`O death, where is thy sting?
O grave, where is thy victory?`"

As these writings in the usual way are scarce in many neighborhoods,
I would recommend to your attention and perusal the Friends' Library,
now in publication in Philadelphia,
under the care of the Meeting for Sufferings of that Yearly Meeting;
in prosecution of a concern which has rested for many years upon
Friends in the different parts of this continent as well as in Europe.
As it is a work calculated to be so eminently useful in
the promotion of virtue and religion in the earth;
I have desired its general circulation, and particularly that our junior members might,
as much as may be, avail themselves of the opportunity of making it their own.
For it will be a source of instruction and comfort to
themselves and their children after them.

In conclusion, dear friends, the Lord, in his abundant, love,
hath from time to time given us renewed evidences of his gracious regard,
and particularly in delivering us out of many tribulations occasioned by those, who,
for want of keeping under the daily cross,
in a state of humility and entire dependence upon the good Shepherd,
have gone from the life, lost that place and station they once held,
and have become great enemies to the church.
May the remembrance of these things sink deep into our hearts,
and animate us individually to seek after and walk in the good old way,
the way of faithfulness to our God: for truly He is good to Israel,
even to such as are of a clean heart.
And this I have to say to you from Him, that as this people keep to first principles,
walk by the same rule, and mind the same thing that they did in the beginning,
no weapon formed against them shall prosper.
But He will by his Almighty power still encamp round about,
and shield from the fiery darts of Satan.
Thus our Society, together with the testimonies which have been upheld by it,
will remain,
and generations yet unborn shall praise and magnify
that God who hath wrought wondrously for us.
"`May the God of all grace, who hath called us unto his eternal glory, by Christ Jesus,
after that ye have suffered awhile, make you perfect, establish, strengthen,
settle you.`"

[.signed-section-closing]
To Him be glory and dominion for ever and ever. Amen.

[.signed-section-signature]
Joseph Edgerton.

--
